### ISSUE TITLE
Recursion Limit Reached

### ISSUE THREAD

**Issue by philzook58** [tefra/xsdata#1008]
A file describing the schema for (ironically) the [termination competition](https://termination-portal.org/wiki/Termination_Competition) doesn't seem to terminate.

```
xsdata generate  https://raw.githubusercontent.com/TermCOMP/TPDB/master/xml/xtc.xsd
#.. a couple minutes
RecursionError: maximum recursion depth exceeded
```
Ubuntu 22.04
```
$ xsdata --version
xsdata, version 24.4
```

**Comment by tefra** [comment]
That's an interesting case a `xsd:group` with an inner self reference

**Comment by tefra** [comment]
Hi @philzook58 

The fix is on main, I also took the liberty of adding the tpdb in the samples [repo](https://github.com/tefra/xsdata-samples/tree/main/tpdb).

**Comment by philzook58** [comment]
Thanks!!
