### ISSUE TITLE
extending the SOAP Config NamedTuple...

### ISSUE THREAD

**Issue by rvalyi** [tefra/xsdata#1009]
Hello,

Recently you changed the xsdata.formats.dataclass.client.Config from a dataclass to a NamedTuple. However I'm having hard times trying to get my subclass Client, called FiscalClient(Client), use my own config class: FiscalConfig(Config):

```python
class FiscalConfig(Config):
    pkcs12_data: bytes = None
    pkcs12_password: str = None
    server: str = "undef"

class FiscalClient(Client):
    def __init__(
        self,
        config: Config,
    ):
    self.config = FiscalConfig(**config)
   # ... call super etc...
```

If I inherit the xsdata SOAP Config, then either my custom attributes are not taken into account (if I use the origin Config#from_service method for instance), either Config#new complains that it doens't know attributes defined in FiscalConfig like in the constructor above:

```Config.__new__() got an unexpected keyword argument 'ambiente```

It seems it boils down to how Python NamedTuple works: https://stackoverflow.com/questions/44287623/a-way-to-subclass-namedtuple-for-purposes-of-typechecking

Some posts like this one also suggest to use dataclass instead. I could do what I wanted when config was a dataclass. Is there a good reason it changed to NamedTupĺe? Do you have any hint how one can use its own SOAP config class? (I could work around it putting the attributes in FiscalClient directly but it looks strange). Thanks.

**Comment by tefra** [comment]
Honestly, I never thought people would subclass the config, I will revert that part

**Comment by rvalyi** [comment]
Well that makes sense. For instance for us we need to mount a pkcs12 certificate to comunicate with the Brazilian Fiscal Authority (using requests-pkcs12). They also use wildcards extensively so we need to override how the response is parsed... If you are curious this a very alpha version of what I did: https://github.com/akretion/brazil-fiscal-client/tree/main
but yes a dataclass Config would make things cleaner I believe. Other than that as usual kudos for the terrific work with xsdata!

**Comment by rvalyi** [comment]
Also a dumb question: why did you separate the Config class from the Client class at all? It seems one config is always bound to a client and never used elsewhere so I wonder the why.

**Comment by tefra** [comment]
Apparently for allowing people to extend the config, and then forget all about it :) Any suggestions to improve the API are welcomed!

**Comment by tefra** [comment]
Thanks @rvalyi!
