### ISSUE TITLE
Do not lose data during serialization after parsing

### ISSUE THREAD

**Issue by sedrew** [tefra/xsdata#1011]
Hello,I'm using fail_on_unknown_properties=False. Since arguments in my models may not be registered in my xml, but I need to save this data during serialization.

How to save xml elements that are not specified in the xsdata model during parsing so that they are not lost during serialization?

Update:

I'm trying to achieve this with a Wildcard.
My base class

```python
@dataclass
class BaseSchema:

    any_elements: List[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any"
        }
    )
```

But namespace don't wrote in local element attribute 

I get is
```xml
    <p:extLst>
      <p:ext uri="{BB962C8B-B14F-4D97-AF65-F5344CB8AC3E}">
        <p14:creationId val="3561048925"/>
      </p:ext>
    </p:extLst>
```
I need
```xml
  <p:extLst>
    <p:ext uri="{BB962C8B-B14F-4D97-AF65-F5344CB8AC3E}">
      <p14:creationId xmlns:p14="http://schemas.microsoft.com/office/powerpoint/2010/main" val="3561048925"/>
    </p:ext>
   </p:extLst>
```

**Comment by tefra** [comment]
Hi @sedrew can you post the whole excerpt please, from only that output I don't see what's the different both xml outputs are equivalent.

**Comment by sedrew** [comment]
I'm trying to overwrite slide from powerpoint. I did some additional research and found out that the namespace problem is not related to a powerpoint reading error. I found out that the Wildcard order does not match the original file. Because of this, powerpoint cannot read this xml.

<img width="302" alt="image" src="https://github.com/tefra/xsdata/assets/47116568/9578f063-ed7a-46a8-8906-ad9648510f3e">
<img width="305" alt="image" src="https://github.com/tefra/xsdata/assets/47116568/99b4ccff-8a92-4672-80f8-cf8fe0656fbb">


[after_parser.txt](https://github.com/tefra/xsdata/files/14978300/after_parser.txt)
[after_power_point.txt](https://github.com/tefra/xsdata/files/14978302/after_power_point.txt)

Not a problem for reading powerpoint:
<img width="1343" alt="image" src="https://github.com/tefra/xsdata/assets/47116568/c50b5915-666f-4b4f-93a8-6599bc37e406">

**Comment by sedrew** [comment]
> Hi @sedrew can you post the whole excerpt please, from only that output I don't see what's the different both xml outputs are equivalent.

How do I save index positions in XmlVar for elements during parsing?

For example, one `Sp` element in xml may be located at the beginning, the other at the end of the root

<img width="377" alt="image" src="https://github.com/tefra/xsdata/assets/47116568/e9ea1365-a062-413e-a4d1-368eb165eab2">


```python
@dataclass
class SpTree:
    class Meta:
        name = "spTree"
        namespace = (
            "http://schemas.openxmlformats.org/presentationml/2006/main"
        )

    nv_grp_sp_pr: Optional[NvGrpSpPr] = field(
        default=None,
        metadata={
            "name": "nvGrpSpPr",
            "type": "Element",
            "required": True,
        },
    )
    grp_sp_pr: Optional[GrpSpPr] = field(
        default=None,
        metadata={
            "name": "grpSpPr",
            "type": "Element",
            "required": True,
        },
    )
    sp: List[Sp] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "min_occurs": 1,
        },
    )

    any_elements: List[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any"
        }
    )
```

**Comment by tefra** [comment]
For repeating choices, on sequences that the order might change you can use compound fields 

https://xsdata.readthedocs.io/en/latest/models/fields/#elements
https://xsdata.readthedocs.io/en/latest/codegen/config/#compoundfields

**Comment by sedrew** [comment]
Thanks, It helped me.
```python 
    shapes: List[Union[NvGrpSpPr, GrpSpPr, Sp]] = field(
        metadata={
            "type": "Elements",
            "choices": (
                {"wildcard": True, "type": object},
                {"name": "sp", "type": Sp},
                {"name": "grpSpPr", "type": GrpSpPr},
                {"name": "nvGrpSpPr", "type": NvGrpSpPr}
            )
        }
    )
```
