### ISSUE TITLE
xsdata generate file.xsd fails: AttrsFilters.field_definition() missing 1 required positional argument

### ISSUE THREAD

**Issue by bicobus** [tefra/xsdata#1045]
xsdata version 24.5

Trying to generate from and xsd file, which previously was working fine, generate this error:

```
  File ".venv/lib/python3.11/site-packages/xsdata/formats/dataclass/templates/class.jinja2", line 45, in top-level template code
    {%- set field_definition = obj|field_definition(attr, parent_namespace) %}
^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AttrsFilters.field_definition() missing 1 required positional argument: 'parents'
```

**Comment by tefra** [comment]
Hi @bicobus can you try with the latest version of the xsdata-attrs?
https://github.com/tefra/xsdata-attrs/releases/tag/v24.5

**Comment by bicobus** [comment]
Ah, that did it. For some reason, I depend on xsdata-attrs and only xsdata updated to v24.5. I guess because the major version changed.

Thanks for catching that.
