### ISSUE TITLE
Question: Ability to add ` field(repr=False)` for specific fields?

### ISSUE THREAD

**Issue by afuetterer** [tefra/xsdata#1050]
Hi, a quick question: Is it possible to define in the config, that some fields of the autogenerated dataclasses should not be part of the repr method?

I would like to have the repr method, but actually for inspecting the objects, I don't need all the fields in the output. Does this make sense?

**Comment by tefra** [comment]
It would be extremely difficult and painful to add this in main library @afuetterer 

I strongly believe `__repr__` should return a string representation that can be executed and return exactly the same value.

**Comment by afuetterer** [comment]
Alright, I see. Let me close this then.
