### ISSUE TITLE
A way to not output tags with nillable="true" and minOccurs="0" ?

### ISSUE THREAD

**Issue by guillaumealgis** [tefra/xsdata#1063]
Hi, 

Is there a way to control the behavior of the serializer (XML serializer in my case) when handling elements declared with both `nillable="true"` and `minOccurs="0"` ?

The doc says for a `nillable` field :

> Specify if the field has to be present in the serialized result even when it doesn't have any meaningful content.

However if the field is also declared `minOccurs="0"`, it's perfectly valid to simply ignore the element in the final XML output.

For example, given this schema :  

```xml
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="elements">
      <xs:complexType>
        <xs:sequence>
          <xs:element minOccurs="0" name="foobar" nillable="true" type="xs:string"/>
        </xs:sequence>
      </xs:complexType>
    </xs:element>
</xs:schema>
```

I can generate two XML snippets like so :  

```py
from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig

from nillabletest import *  # my package generated from the .xsd

config = SerializerConfig(encoding="utf-8", ignore_default_attributes=True, indent="  ")
serializer = XmlSerializer(config=config)
tree = Elements(foobar="hello, world!")
print(serializer.render(tree))

print("--------------")

tree = Elements()
print(serializer.render(tree))
```

Which gives : 

```xml
<?xml version="1.0" encoding="utf-8"?>
<elements>
  <foobar>hello, world!</foobar>
</elements>
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<elements>
  <foobar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
</elements>
```

In the second scenario (no value given to `foobar`), I would prefer the resulting XML not to contain the `<foobar>` tag at all :  

```xml
<?xml version="1.0" encoding="utf-8"?>
<elements>
</elements>
```

Which is still valid against the original .xsd, but I see no way to instruct the XMLSerializer to give this output.
Am I missing something?

Thanks for your help, and for this massively helpful project!

Cheers,

**Comment by tefra** [comment]
Hi @guillaumealgis, this is not a very common scenario, I actually have zero examples of this pattern including the w3c tests suite 🙄 

Since both outputs are valid, xsdata will follow the minimum output approach! The update is on main.

**Comment by guillaumealgis** [comment]
Thanks a lot @tefra , this indeed solved our issue! 🎉

> this is not a very common scenario, I actually have zero examples of this pattern including the w3c tests suite 🙄

Yes, I'm not surprised. We are working with a massive .xsd from hell on which we have zero control. Lots of weird and nonsensical things keep popping up 🙃. But so far `xsdata` has been really solid handling all of that.

Cheers!

**Comment by tefra** [comment]
Hi @guillaumealgis if it's a public one I would love to add it in the samples repo https://github.com/tefra/xsdata-samples

**Comment by guillaumealgis** [comment]
It is : https://github.com/ansforge/TestContenuCDA-3-0/tree/main/infrastructure/cda

It's sort of a French interpretation / adaptation of the [HL7 CDA R2 spec](https://www.hl7.org/implement/standards/product_brief.cfm?product_id=515)
