### ISSUE TITLE
XmlDuration def to_timedelta

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#1064]
Would be nice to have a `to_timedelta`, it probably looks easier than it is since XmlDuration has Years and Months as property too.

**Comment by tefra** [comment]
python timedeltas don't support years, months, if they were we wouldn't have to add our custom XmlDuration 😭

**Comment by skinkie** [comment]
> python timedeltas don't support years, months, if they were we wouldn't have to add our custom XmlDuration 😭

Is that also the reason it doesn't have a `to_totalseconds` because you cannot truthfully compute the seconds without knowing what year it is?
