### ISSUE TITLE
Split choice elements into virtual attributes

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#1065]
Choice elements have been consolidated into single attributes. Under this single attribute a specific element is hosted to fulfill the xs:choice. Would it be possible to approach this from a different direction, being: all possible choices would be exposed as an attribute, where the attribute name is predictable?

Now:
```
choice1_choice2 = Choice1()
```
Requested the ability to:
```
choice1 = Choice1()
choice2 = None
```

**Comment by tefra** [comment]
I don't get it @skinkie you can disable the compound fields if you don't care about ordering

**Comment by skinkie** [comment]
I'll explore if _disabling_ does what I am asking for. Due to the general approach in the schema I am using, ordered output is sometimes mandatory. Generally speaking if it is a list of choices, order must be adhered.

**Comment by skinkie** [comment]
@tefra disabling compound fields is indeed what I am looking for. I'll open a new issue.
