### ISSUE TITLE
How to parse multiple xml. For multiple xml merge

### ISSUE THREAD

**Issue by luojiaaoo** [tefra/xsdata#1080]
I want to create wrap for arxml of autosar, but I can not find way to deal with two arxml.

Like:
parser.parse(source,clazz,ns_map)
source can not be Tuple or List

from autosar.arxml import Arxml
from autosar.autosar_00043 import Autosar

```python
arxml = Arxml(Autosar)
xml_autosar_cannm = arxml.parse(r"E:\CanNmConfiguration.arxml")
xml_autosar_canif = arxml.parse(r"E:\CanIfConfiguration.arxml")
a = arxml.render(xml_autosar_canif)
print(a)
```

How to code, thank you very much.

**Comment by tefra** [comment]
Your best bet is to parse the documents with lxml and manually merge the trees manually and then use the [tree](https://xsdata.readthedocs.io/en/latest/data_binding/tree_serializing/) serializer.

Another option is to use xml [inclusions](https://xsdata.readthedocs.io/en/latest/data_binding/xml_parsing/#xml-inclusions)
