### ISSUE TITLE
Question: alternative serialisation/deserialisation

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#1083]
This project is about (de)serialisation of XML and some other formats into dataclasses. Given that the deserialisation into dataclasses requires some heavy lifting I wonder if there are any other (for example binary) representations that would take the contents of a properly parsed object into a dataclass for storage or distribution.

Hence: I want to use the generated classes, but don't want to go back into XML to store the modified results, and then parse it again when required. XML -> dataclass -> intermedate presentation -> dataclass -> (eventually) XML.

Anything already available that quickly can do this job?

**Comment by tefra** [comment]
pickle maybe?
https://docs.python.org/3/library/pickle.html#module-pickle

**Comment by skinkie** [comment]
Just benchmarked deserialisation with pickle, which is 2.5x faster than string deserialisation with xsData (towards the same xsData object).
