### ISSUE TITLE
Missing mandatory XML attributes are ignored while decoding the XML

### ISSUE THREAD

**Issue by rachare** [tefra/xsdata#1089]
### XML Sample 
xml: https://xsdata.readthedocs.io/en/latest/codegen/samples_modeling/#sample-1

### Generated output
Generated output: https://xsdata.readthedocs.io/en/latest/codegen/samples_modeling/#output

Generated output have the correct **"required": True** for **BeginArea.id** field of type **Attribute**

```
@dataclass
class BeginArea:
    class Meta:
        name = "begin-area"
        namespace = "http://musicbrainz.org/ns/mmd-2.0#"

    id: Optional[str] = field(default=None,metadata={"type": "Attribute","required": True,},)
    name: Optional[str] = field(default=None,metadata={"type": "Element","required": True,},)
    sort_name: Optional[str] = field(default=None,metadata={"name": "sort-name","type": "Element","required": True,},)
```
However if the ID filed is removed in the XML as below **(remove mandatory id field)**, xml decoding do not throw any exception and assigns the default value **None** as below. Ideally it should throw exception or Warning.

```xml
      <begin-area>
        <name>Bonn</name>
        <sort-name>Bonn</sort-name>
      </begin-area>
```

```python
BeginArea(id=None, name='Bonn', sort_name='Bonn')
```

**Comment by rachare** [comment]
Even removing the name field altogether as below also assigns **None** to **name** 
Expectation would be to fail if the mandatory field is missing

 ```xml
<begin-area id="b86b7e97-c4e2-4ec2-942b-5a6cd8eea1da">
  <sort-name>Bonn</sort-name>
</begin-area>
```

```python
BeginArea(id='b86b7e97-c4e2-4ec2-942b-5a6cd8eea1da', name=None, sort_name='Bonn')
```

**Comment by tefra** [comment]
I can't wait python 3.9 eol lol

https://xsdata.readthedocs.io/en/latest/faq/#why-non-nullable-fields-are-marked-as-optional

Dataclasses prior to 3.10 raise a TypeError when a field without a default value follows a field with a default value, that's why xsdata has to mark all fields as optional.

Enable the `kwOnly` in the https://xsdata.readthedocs.io/en/latest/codegen/config/#format

**Comment by rachare** [comment]
Thanks a lot @tefra for correcting me :).
