### ISSUE TITLE
SOAP Body sometimes generated with mandatory `fault` field

### ISSUE THREAD

**Issue by mmakaay** [tefra/xsdata#1093]
**Context**

I am currently investigating if I can use xsdata for consuming a SOAP service that I have to integrate with. So far, I see a lot of good stuff. I'm using xsdata-pydantic, and am very happy with the generated Pydantic schema classes. I was quickly able to build a request to send using these.

**Issue**

Parsing the response using the built-in Client fails. When using `client.send(...)`, validation fails on the output message that is returned from the service:

```
1 validation error for Body
fault
  Field required [type=missing, input_value={'can_response': CanRespo...cel.'), request_uid='')}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```

It tells me that the `fault` field is required, but the service does not return a fault element.

**My current work-around**

I found out that the broken behavior is related to `kw_only = True` (see my updated in this thread). I was able to get SOAP calls working by:

- not using `pydantic` but `dataclasses` as the format (because `pydantic` enforced `kw_only = True`;
- not using `xsdata --kw-only` for generating the schema classes.

**Comment by mmakaay** [comment]
Here's a way to reproduce the issue:

Create an empty directory.
Inside that directory, generate classes for a simple public SOAP service:

```
$ mkdir test-xsdata-client
$ cd test-xsdata-client
$ xsdata --output pydantic 'https://www.dataaccess.com/webservicesserver/NumberConversion.wso?WSDL'
```

In the same directory, add the following testscript:

```python3
#!/usr/bin/env python3

from xsdata.formats.dataclass.client import Client, Config
from xsdata.formats.dataclass.context import XmlContext
from xsdata.formats.dataclass.parsers import XmlParser
from xsdata.formats.dataclass.serializers import XmlSerializer

from generated import *

context = XmlContext(class_type="pydantic")
serializer = XmlSerializer(context=context)
parser = XmlParser(context=context)

client = Client(
    config=Config.from_service(NumberConversionSoapTypeNumberToWords),
    parser=parser,
    serializer=serializer
)

response = client.send(
    NumberConversionSoapTypeNumberToWordsInput(
        body=NumberConversionSoapTypeNumberToWordsInput.Body(
            number_to_words=NumberToWords(ubi_num=1234)
        )
    )
)

print(response)
```

**Actual output**

When running this script, send() fails with a "fault field required" error.

**Expected output**

```
body=Body(number_to_words_response=NumberToWordsResponse(number_to_words_result='one thousand two hundred and thirty four '))
```

**Comment by mmakaay** [comment]
After generating dataclasses instead of pydantic classes, and after switching to the default XML serializer and parser, the test code worked just fine. Thus, the issue only shows up with Pydantic.

this might suggest that the bug report should have been filed under the xsdata-pydantic repository. Leaving it in here though, since the code that adds the wsdl:Fault is part of the xsdata repository code.

**Comment by mmakaay** [comment]
Found an interesting lead.

When using:
```
xsdata generate 'https://www.dataaccess.com/webservicesserver/NumberConversion.wso?WSDL'
```

I get this fault definition in a response `Body`:

```python3
fault: Optional[
    "NumberConversionSoapTypeNumberToDollarsOutput.Body.Fault"
] = field(
    default=None,
    metadata={
        "name": "Fault",
        "type": "Element",
    },
)
```

So here the fault field is optional. However, when I use the following:

```
xsdata generate --kw-only 'https://www.dataaccess.com/webservicesserver/NumberConversion.wso?WSDL'
```

the fault definition becomes:

```python3
fault: "NumberConversionSoapTypeNumberToDollarsOutput.Body.Fault" = (
    field(
        metadata={
            "name": "Fault",
            "type": "Element",
        }
    )
)
```

When running the dataclasses-based test script from the previous post, the output is:

```
TypeError: NumberConversionSoapTypeNumberToWordsOutput.Body.__init__()
    missing 1 required keyword-only argument: 'fault'
```

**Note:**
When using pydantic output, it doesn't matter if I include a kw-only flag or not; the pydantic generated code always has the `fault` field as mandatory.

**Comment by mmakaay** [comment]
The code that decides to not add `None` in the type hint is from `xsdata.formats.dataclasses.filters`:

```python3
def field_type(self, obj: Class, attr: Attr) -> str:
    
    ------8<------
    
    if attr.is_nillable or (
        attr.default is None and (attr.is_optional or not self.format.kw_only)
    ):
        return f"None | {result}" if self.union_type else f"Optional[{result}]"
        
    return result
```

Since I can make it work when switching only `kw_only`, logic dictates:

  - `attr.is_nillable` is `False`
  - `attr.default` is `None`
  - `attr.is_optional` is False

Why is `kw_only` a factor here? From the perspective of dataclasses, it is no problem AFAICS:

```python3
>>> import dataclasses as d
>>> @d.dataclass(kw_only=True)
... class X:
...     value: None | str = d.field(default=None)
...
>>>
>>> X()
X(value=None)
>>> X(value=None)
X(value=None)
```

**Comment by tefra** [comment]
Thanks for reporting @mmakaay
