### ISSUE TITLE
xsdata generating circular dependencies

### ISSUE THREAD

**Issue by raminmiraftabi** [tefra/xsdata#1094]
With the attached schema files when generating the s421 bindings a circular dependency is created in S100_gmlProfile to s100basegml which does not exist in the schema files. This feels like a bug.

I have also attached the generated s100_gml_profile.py which has the problematic code commented and now at least allows the imports to take place.
[xsdata-bug.zip](https://github.com/user-attachments/files/17774207/xsdata-bug.zip)

Please note, the s100* schema files are not the original ones used, these have some changes that have taken place when trying to isolate the issue and ensure that the issue isn't in the S-100 reuse of GML namespace.

**Comment by tefra** [comment]
Can you please include the config, command you are using?

**Comment by tefra** [comment]
xsdata comes with different output styles with the purpose to overcome circular imports in schemas. Experiment with those please.
https://xsdata.readthedocs.io/en/latest/codegen/config/#structure


If none of them works for you, please re-open with more info, like the config you are using, the full schemas and the specific error.
