### ISSUE TITLE
Recursion limit for complicated XSDs

### ISSUE THREAD

**Issue by nimish** [tefra/xsdata#138]
For some truly cursed XSDs -- HL7v3 for example -- this tool tries to consolidate and flatten types recursively. However, the complexity is too much and python kills it for hitting the recursion limit or it simply segfaults/hits OOM.

[This](https://github.com/CONNECT-Solution/Common-Types) is the gauntlet of XSDs, no tool at all works besides XJC/JAXB and even then they don't do the unions correctly.

**Comment by tefra** [comment]
Thanks for reporting @nimish 

I am a bit blocked on this in python an inner class can't extend the outer class, unlike java.

The only solution I 've come up so far is to actually break the inner class, but that's easier said than done.

```python
class Foo:
   pass

    Class Bar(Foo):
        pass
```

**Comment by nimish** [comment]
Is being an inner class needed? Can you just generate it outside with an extended name?

**Comment by tefra** [comment]
No the concept is pretty straightforward take the inner class and promote it to the root classes.

It's more of a design issue I guess, the flattening procedure just merges simple types, attributes, groups but it stops there, it doesn't change the root classes tree and by following that naive approach I think in the end I am avoiding a lot of collisions with names, imports.

The second design issue is that up until the CodeWriter class no language specific conventions have applied yet, leaving room in the future for I don't know maybe add generators for java, node.

Despite all that I don't think there is a `nice` way to deal with this https://stackoverflow.com/a/39077925

This is a sample that demonstrates the issue just for reference.

msData/particles/particlesEb041.xsd

```xml
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="foo" 	xmlns="foo"> 
<xsd:complexType name="foo">
		<xsd:sequence>
			<xsd:element name="foo"/>
			<xsd:element name="bar" minOccurs="0">
				<xsd:complexType>
					<xsd:complexContent>
						<xsd:restriction base="foo">
							<xsd:sequence>
								<xsd:element name="foo"/>
							</xsd:sequence>
						</xsd:restriction>
					</xsd:complexContent>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
</xsd:complexType>

<xsd:element name="root" type="foo" />

</xsd:schema>
```

**Comment by tefra** [comment]
I just tried to run the generator against some of the xsd from the  Common-Types / HL7V3 you suggested @nimish actually it's a genuine case of very complicated schema and not because of the known issue I posted above.


I am going to add a simple dept limit on the circular dependency check.
