### ISSUE TITLE
More HL7v3 enum fun -- Unknown enumerations

### ISSUE THREAD

**Issue by nimish** [tefra/xsdata#151]
This one's harder to pin down, but in the Connect types repo, if you try to run (in the NE2008 directory) `xsdata --package hl7 multicacheschemas/` xsdata will crash with:

`xsdata.exceptions.AnalyzerError: Unknown enumeration RoleClassPassive: @enum@RoleClassMutualRelationship.PROV` 

which I can't quite figure out how to fix internally. It may have to do with the recent enum changes. I don't quite see what it's trying to do with the `@` prefixed class name

**Comment by tefra** [comment]
Thank you very much @nimish for your help!

There were multiple issues with the two previous fixes for enumeration unions and the correct default value generation.

I created a new repo to specifically test the generator against the common-types and I am looking for a way to automatically trigger it during pull requests, that collection of schemas is one of the most complex I have encountered.

https://travis-ci.com/github/tefra/xsdata-common-types
