### ISSUE TITLE
Document how to render Wildcard elements correctly

### ISSUE THREAD

**Issue by nimish** [tefra/xsdata#157]
Wildcard elements are both common in schemas and a little tricky to handle correctly in most generation libraries.

In the [WS-Security 1.0 schema](http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd), the element `SecurityTokenReference` must accept any element as a child. In particular, `KeyIdentifier` is a common one required by the Basic Security Profile 1.1 when referring to a SAML Token.

However, when rendering an STR using `XmlSerializer`:

```python
stref = SecurityTokenReference()
ki = KeyIdentifier()
ki.value = "test"
stref.any_element.append(ki)
ser = XmlSerializer()
ser.render(stref)
```
an `<any_element ... >`  tag is generated, rather than the `<KeyIdentifier ... >`

```xml
<?xml version='1.0' encoding='UTF-8'?>
<ns0:SecurityTokenReference xmlns:ns0="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
  <any_element>test</any_element>
</ns0:SecurityTokenReference>
```

This is the generated class for `SecurityTokenReferenceType`:

```python

@dataclass
class SecurityTokenReferenceType:
    """This type is used reference a security token.

    :ivar any_element:
    :ivar id:
    :ivar usage:
    :ivar other_attributes:
    """
    any_element: List[object] = field(
        default_factory=list,
        metadata=dict(
            type="Wildcard",
            namespace="##any",
            min_occurs=0,
            max_occurs=9223372036854775807
        )
    )
    id: Optional[str] = field(
        default=None,
        metadata=dict(
            name="Id",
            type="Attribute",
            namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
        )
    )
    usage: List[str] = field(
        default_factory=list,
        metadata=dict(
            name="Usage",
            type="Attribute",
            namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd",
            min_occurs=0,
            max_occurs=9223372036854775807
        )
    )
    other_attributes: Dict[QName, str] = field(
        default_factory=dict,
        metadata=dict(
            type="Attributes",
            namespace="##other"
        )
    )
```

**Comment by tefra** [comment]
For wildcard fields the parser is not yet smart enough to pick up any model in the target namespace, in most of the cases it will use `xsdata.formats.dataclass.models.generics.AnyElement` to bind the document data.

But in your case that you know the correct model the serializer should have picked that up correctly. I am going to set this as a bug.

The workaround is a bit ugly but works by accident because of the generic object has a qname field

```python
In [1]: from lxml.etree import QName 
   ...:  
   ...: from foo import SecurityTokenReference, KeyIdentifier 
   ...: from xsdata.formats.dataclass.serializers import XmlSerializer 
   ...:  
   ...: stref = SecurityTokenReference() 
   ...: ki = KeyIdentifier() 
   ...: ki.qname = QName("http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "KeyIdentifier") 
   ...: ki.value = "test" 
   ...: stref.any_element.append(ki) 
   ...: ser = XmlSerializer(pretty_print=True) 
   ...: print(ser.render(stref))                                                                                                                                                                                                              
<?xml version='1.0' encoding='UTF-8'?>
<ns0:SecurityTokenReference xmlns:ns0="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
  <ns0:KeyIdentifier>test</ns0:KeyIdentifier>
</ns0:SecurityTokenReference>
```

Thanks for reporting @nimish

**Comment by nimish** [comment]
Thanks. To be clear any element i correctly parsed, it's just that on generation it should be replaced with whatever is in  that element. The schema requires it to be extensible

**Comment by tefra** [comment]
I am really excited @nimish you are dealing with some aspects of xml schema like unions and wildcards that I really haven't worked in a production level before and as such xsdata has a lot of caveats in these `edge` cases.

Keep them coming!
