### ISSUE TITLE
SAML 2.0 xsd's break if generated all at once

### ISSUE THREAD

**Issue by nimish** [tefra/xsdata#165]
* Download https://docs.oasis-open.org/security/saml/v2.0/saml-2.0-os-xsd.zip
* run `xsdata --package saml .` in the unzipped directory

xsdata 20.5.4 breaks with ```xsdata.exceptions.SchemaValueError: Schema class `Annotation` unknown real name.```

I think this is due to some of the `xs:redefine` containing a `xs:annotation` element, but I'm not sure how to work around it/fix it

**Comment by tefra** [comment]
nice!
