### ISSUE TITLE
SOAP 1.2 xsd generated Envelope class not referring to correct child elements

### ISSUE THREAD

**Issue by nimish** [tefra/xsdata#166]
Generate classes from https://www.w3.org/2003/05/soap-envelope

Envelope is the root element of all soap messages:

```python
@dataclass
class Envelope:
    """
    :ivar header:
    :ivar body:
    :ivar other_attributes:
    """
    class Meta:
        namespace = "http://www.w3.org/2003/05/soap-envelope"

    header: Optional[str] = field(
        default=None,
        metadata=dict(
            name="Header",
            type="Element"
        )
    )
    body: Optional[str] = field(
        default=None,
        metadata=dict(
            name="Body",
            type="Element",
            required=True
        )
    )
    other_attributes: Dict[QName, str] = field(
        default_factory=dict,
        metadata=dict(
            type="Attributes",
            namespace="##other",
            required=True
        )
    )
```

The header/body child elements should refer to the correct `Header` and `Body` types, which refer to wildcard any_elements as needed.

**Comment by nimish** [comment]
I'm not totally sure this is a bad thing, since arbitrary xml is needed, but it is kind of odd

**Comment by nimish** [comment]
It also looks to be relevant to https://github.com/tefra/xsdata/pull/135 -- I'm trying to basically replace my hacked up `zeep` replacement that can deal with some deeply cursed XSDs, so having a good SOAP envelope model is key

**Comment by tefra** [comment]
I have a roadmap for wsdl but I believe that will take some time to even start having a working version. For my own use I simply wrote the models manually last year at that time it was failing all over the place and I forgot to try it again lately.

The issue is correct thought it shouldn't have reset the type to str for no reason but the fix is seems quite simple.

nice one!
