### ISSUE TITLE
XInclude processing

### ISSUE THREAD

**Issue by hcw70** [tefra/xsdata#207]
Dear authors of xsdata.

I need to process a XML document which is assembled from others by means of XInclude 
(http://www.w3.org/2001/XInclude).

LibXML and python seems to handle that, but via xsdata it does not work with this.

```
<?xml version="1.0" encoding="UTF-8"?>
<MessageDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xxx.de/config/xxx msgdb/xsd/MessageDB.xsd"
    xmlns="http://xxx.de/config/xxx"
    xmlns:xi="http://www.w3.org/2001/XInclude">
    
    <xi:include href="MessageDB-Example-lib.xml"/>
    
    <module name="MotivatinExample1">
   </module>
 </MessageDB>

```

Maybe it is sufficient to follow one of:
https://lxml.de/1.3/api.html#xinclude-and-elementinclude

or 
http://effbot.org/zone/element-xinclude.htm
?

Maybe it would be good to have that as a ParserConfig option?

**Comment by tefra** [comment]
I need to read more on this but it looks interesting, can you share the original schema as well?

Maybe that's easier than it looks to integrate...

**Comment by hcw70** [comment]
The actual schema is not important. 
How it works is that the XML processor reads the pointed-to file and puts it into the xinclude location.
 If you are using lxml or elementtree this should be that simple as given in the links.

**Comment by tefra** [comment]
The XmlParser is using the lxml.etree.iterparse 
https://github.com/tefra/xsdata/blob/af8508b23281a4817bbfdf514322425c60b99f51/xsdata/formats/dataclass/parsers/xml.py#L45

Do you know if the lxml xinclude is supported with iterparse?

**Comment by hcw70** [comment]
Dunno. Maybe just try to do like this (from the lxml link)

```
tree = etree.parse(data)
tree.xinclude()

```

**Comment by tefra** [comment]
Yeah I don't want to switch from iterparse to parse for performance reasons, but let me check if there is a workaround...

**Comment by tefra** [comment]
Hey @hcw70 give it a try pr #210 let me know how it works for you :test_tube:

**Comment by hcw70** [comment]
@tefra The diff looks great! I will give it a try after my vacation. Thanks for fixing!
