### ISSUE TITLE
empty attributes are removed in generated XML

### ISSUE THREAD

**Issue by gjvc** [tefra/xsdata#230]
Hello,
First of all, thank you for a wonderful project.  It's a great leap forward over walking XML trees via ElementTree findall() and such.

I am using it to generate a configuration for a system.  This is a legacy application and as such has many quirks.  One such quirk is that it needs to see an empty attribute in an element like this

    <element something="hello" else="there" amount="" symbol="ABC" />

The problem I'm having is that `amount=""` is getting removed and does not appear in the generated XML, even when I set it to "".  I would expect it to be removed if it were set to None in Python, but i'm setting it to the empty string and that is what I would like to see that in the XML.  I'm using xsdata version 20.7 on python 3.8.5.

**Comment by tefra** [comment]
You are right the serializer is ignoring empty strings as well, that doesn't sound right.

Let me run a few tests to see if we can change this default behavior or if we need to add some sort of configuration there.

Same behavior for v20.8 as well

**Comment by tefra** [comment]
Out of curiosity @gjvc are you working with a schema definition or do you write the models yourself? Also did you encounter an issue with v20.8 and didn't upgrade?

**Comment by gjvc** [comment]
> Out of curiosity @gjvc are you working with a schema definition or do you write the models yourself? Also did you encounter an issue with v20.8 and didn't upgrade?

Thank you very much for the quick response!  I am using an XSD generated from a RelaxNG grammar via the "trang" tool.

I tried v20.8 to see if it fixed this problem, but held of making this problem report until I'd gone through the documentation one more time :-)

**Comment by tefra** [comment]
Can you share how that attribute is defined in the xsd?

**Comment by gjvc** [comment]
Currently it is defined in the XSD

       <xs:attribute name="orderQty" type="xs:integer"/>

**Comment by gjvc** [comment]
I have just tried your fix via this in my etc/pip/requirements.txt file

    -xsdata==20.7
    +git+https://github.com/tefra/xsdata.git@issue-230

...and it looks like it works great.  Thank you very much for the amazingly quick fix. :-)

**Comment by tefra** [comment]
awesome man, I also confirmed with the w3c-test-suite that the updated behavior still produces valid xml instances.

I am going to merge it to master, and it will be included in the next release v20.9
