### ISSUE TITLE
Support python 3.6

### ISSUE THREAD

**Issue by gjvc** [tefra/xsdata#241]
I would like to be able to use xsdata with pypy.  I can't right now, because pypy does not work with lxml.  I see that you are making an effort to use less lxml.  If you have a completely lxml-free version, I would be very happy to test it for you :-)

**Comment by tefra** [comment]
Awesome @gjvc I think there a few more steps to have a completely lxml-free version, but I think I got the parser working with the native `xml.sax.handler.ContentHandler`  see #240 

The codegen tool is still using the default handler which is lxml, if you have managed to generate the models through another venv or if you are using custom models give it a try and let me know what you thin.


```python
from xsdata.formats.dataclass.parsers import XmlParser
from xsdata.formats.dataclass.parsers.handlers import SaxHandler

parser = XmlParser(handler=SaxHandler)  # Native python 
p.parse("some/file.xml", Books)
```

I haven't checked xsdata with pypy, does lxml fail on the setup or during usage?

**Comment by gjvc** [comment]
Well.  Good and bad news.  It's late here, so I'm sorry if this is not crystal clear.

I'm using pypy3 on Debian bullseye/sid.  Looks like lxml and pypy3 are actually playing well with each other at installation/wheel build time and runtime, so please forget my comment above -- looks like the historic problems have been resolved. (Google for lxml and pypy3 to see the sort of problems people were having)

Note that the python version of pypy3 is "Python 3.6.9".  This is not Python 3.7, so I have had to install the dataclasses module from pip https://pypi.org/project/dataclasses/.  But, when I use version 0.7 of dataclasses I get lots of these warnings from xsdata:

`warning: Unassigned parsed object ElementName
`
where "ElementName" is a legitimate element name as per the grammar. I also get a lot of "object is not iterable" errrors running code which previously worked on python3.8 with python 3.6 and dataclasses 0.7

I'm a bit stuck right now with all this yak-shaving.  I might see if there is an early 3.7 version of pypy I can use. 

The next thing to do is to test cpython 3.6, xsdata, and dataclasses 0.7 from pypi. I see from the front page of xsdata that you only support python 3.7 onwards.  pypy is only at 3.6 right now, so bringing this issue back on-topic (finally), this problem reduces to supporting python 3.6 via dataclasses 0.7 from pypi.

whew.

**Comment by tefra** [comment]
There is an issue with the typing module and `bool` type for some reason, that's why I never officially added support for python3.6.

See pr #242

**Comment by gjvc** [comment]
This looks good.  I will test some more and report back.  Thanks once again :-)

**Comment by tefra** [comment]
Well it has a drawback you can not use `typing.Union` safely because of the 3.6 issue.

I am not sure how to proceed here I definitely don't want to offer a monkey patch...
I would rather add a notice for py36 users or something.

**Comment by gjvc** [comment]
Thank you very much!
