### ISSUE TITLE
Gerated names should match XSD names

### ISSUE THREAD

**Issue by hcw70** [tefra/xsdata#260]
When processing my XSD, which contains types like

```
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    elementFormDefault="qualified"
    xmlns="http://deuta.de/config/DeutaMsgDatabase"
    xmlns:d="http://deuta.de/config/DeutaMsgDatabase"
    targetNamespace="http://deuta.de/config/DeutaMsgDatabase">

    <xs:element name="MessageDB" type="TMessageDB">
...
    </xs:element>
    <xs:complexType name="TMessageDB">
...
    </xs:complexType>

```

i would have expected to have the xsdata class to be named `TMessageDB`, but it actually is `TmessageDB`.

Since i am trying to migrate away from another mapping tool which did not do this (pyxb), this would
require a lot of API breakage on the client code, since that depends on the generated types a lot.

Is there an option to prevent that mapping to occur?

Regards

**Comment by tefra** [comment]
currently no, xsdata the name converters can't understand all capital single or multiple letters prefixes/suffixes.

But this is something that I wanted to take another look since the beginning, some of these converters are there even before the first release.

**Comment by tefra** [comment]
Oh i remembered this schema lmao

```xml
  <xsd:simpleType name="GLOBAL-REF">
    <xsd:restriction base="xsd:string"/>
  </xsd:simpleType>
  <xsd:complexType name="ALTERNATIVE-ID">
    <xsd:all/>
    <xsd:attribute name="IDENTIFIER" type="xsd:string" use="required"/>
  </xsd:complexType>
```

I can't I really can't stand to see this 

```python
@dataclass 
class GLOBALREF:
```

I am going to set a max limit 3 to consecutive capital letters, this is more acceptable I think.

```python
@dataclass 
class GlobalREF:
```

**Comment by hcw70** [comment]
But that should be the problem of the XSD designer, IMHO.
If he decided to call that type `GLOBAL-REF`, he should expect something reasonable similair in the
code (which does not violate identifier rules), so it should be either `GLOBAL_REF` or `GLOBALREF`.

Giving him` GlobalRef` might be unexpected. 
In my case i have `TDataType` which is mapped to `TdataType`, which looks weird.

So maybe an option during parsing / code generation, if the minimal mapping should be done
(to gain valid identifier) or if your CamelCaseing naming should be given?

Maybe also it would be an option to provide a dict by the user mapping from XML name to python  name?

**Comment by hcw70** [comment]
Making this an option (minimal mapping, camelcase mapping, dict mapping) might  help if you are not in  control of the XSD naming, since the original author did not had in mind to create data bindings automatically.....

**Comment by tefra** [comment]
I agree with you but most of the time people have to live with the xsd someone else designed why should you have to suffer?

I am playing devil's advocate here, I agree with you and the proposal to have an output without naming transformations.

What about attribute names @hcw70 ?

**Comment by hcw70** [comment]
Attributes should be handled similair IMHO. 
Minimal mapping: only replace stuff what is not python-able,  "GENERATE-HEADER" ->  "GENERATE_HEADER"
CamelCase mapping (if appropiate), would be "GENERATE-HEADER -> "generate_Header" (or "generateHeader" ?)

**Comment by tefra** [comment]
I am going to keep the current behavior as the default but I am going to introduce, configuration files so people can change name processors or even provide custom mappings for class, attributes, namespace prefixes...

**Comment by hcw70** [comment]
Thank you! That sounds good.
Keep up the good work with this component!

**Comment by tefra** [comment]
Hey @hcw70 

Check the #265 and the new [docs](https://xsdata.readthedocs.io/en/issue-260/codegen.html#configuration)

Let' me know what you think.

**Comment by hcw70** [comment]
Looks good! Mixed case is the one i will be using most probably... 8.>

Maybe you should extend the name mapping table a bit to make more clear what happens with names like
* test-elem
* Test-Elem
* testElem
* TestElem
* test_elem

**Comment by hcw70** [comment]
Another hint:
I would not write the full xsdata version into the config file. 
`<Config xmlns="http://pypi.org/project/xsdata" version="20.9">
`
Only the "no longer compatible if changed" version number....
I would write "1.0" and keep that as long as you only add elements,
if you remove / change field meanings / rework structutre, bump to 2.0....

**Comment by hcw70** [comment]
The mixedCase is not completely good for my scenario. It works ok for classes, since they start with an upcase letter in my xsd.
It does not work for fields (attributes), since they are defined starting lowercase in my xsd.
I am using camelCase for my fields, that seems to work ok.
But  that i.e. replaces "_" with a camel, which may be suboptimal in my case (where you want / can prescribe most names in xsd).

So for me the best option still would be a "keepCase" option, which only replaces "-" -> "_" and maybe checks for reserved words....

**Comment by tefra** [comment]
I have no idea why I decided to uppercase the first letter in mixed cases lol, I am gonna revert that.

Makes more sense if mixed case just removes non alphanumerical characters without any other transformations, and also to have the `mixed underscore` case that replaces non-alphanumerical characters with underscores.


The version was added for the purpose to know when the config was last initialized/updated from the cli

**Comment by tefra** [comment]
I will go with `mixedSnakeCase` instead of `mixedUnderscoreCase`
