### ISSUE TITLE
Iterate over content / child elements

### ISSUE THREAD

**Issue by hcw70** [tefra/xsdata#261]
In an xsdata representation created from a XSD schema from an XML document like the following

```
<?xml version="1.0" encoding="UTF-8"?>
<MessageDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://deuta.de/config/DeutaMsgDatabase MessageDB.xsd"
                    xmlns="http://deuta.de/config/DeutaMsgDatabase">
                    <module name="root">
                        <datatypes>
                            <packettype name="pckType1">
                                <var name="Var0" type="UNSIGNED32" bitsize="1"/>
                            </packettype>
                        </datatypes>
                    </module>
</MessageDB>

```

is there a uniform way to iterate over the nested elements, maybe something like
```
for child in obj.child_elems():
    print (child)

```
?

In my  current TMessageDb class created by xsdata, there is an attribute "modules" of kind list, but
the child elements are stored in different attributes depending on the class, so here TDataTypes would have an list element "packettype".

Regards

**Comment by tefra** [comment]
No there is no such helper method for such thing, but it's not very difficult to write one, here something similar that I wrote in order to fetch all the obj children that matched a base class.

https://github.com/tefra/xsdata/blob/026ef556499e2ceeb9d83ee7469b76aff22e7563/xsdata/models/mixins.py#L190-L204

**Comment by hcw70** [comment]
Agreed, after digging into dataclass deeper, i came to a similair solution, thanks for providing the info!

However, after further investigation, it looks like the order of the elements yielded by that is not in document order
(if the xsd has a sequence of choices of elements) but packet together based on the element type.

Since the order in our XML docs are very relevant in most cases, this is a no-go for us. Should i raise a new issue for this?

**Comment by tefra** [comment]
Oh I see what you need.

Cool that's part of the serializer logic I could move it to a public helper, in pr #247 


https://github.com/tefra/xsdata/blob/623ee6dbdcea0924959821a04c330b72a5c021b4/xsdata/formats/dataclass/serializers/xml.py#L214-L248

**Comment by tefra** [comment]
Hey man take a look at `XmlSerializer.next_value`


```python

In [1]: from xsdata.formats.dataclass.serializers import XmlSerializer

In [2]: from xsdata.formats.dataclass.context import XmlContext

In [3]: from tests.fixtures.books.fixtures import books

In [4]: books.book[0]
Out[4]: BookForm(author='Hightower, Kim', title='The First Book', genre='Fiction', price=44.95, pub_date='2000-10-01', review='An amazing story of nothing.', id='bk001', lang='en')

In [7]: context = XmlContext()

In [8]: meta = context.fetch(books.__class__)

In [9]: for var, value in XmlSerializer.next_value(books, meta):
   ...:     print(value)
   ...: 
[BookForm(author='Hightower, Kim', title='The First Book', genre='Fiction', price=44.95, pub_date='2000-10-01', review='An amazing story of nothing.', id='bk001', lang='en'), BookForm(author='Nagata, Suanne', title='Becoming Somebody', genre='Biography', price=33.95, pub_date='2001-01-10', review='A masterpiece of the fine art of gossiping.', id='bk002', lang='en')]

```

In the generator you can do a check for list instance and create a recursive method, the var holds teh attribute metadata used for binding purposes you can ignore it. The values will be in the order the fields are defined with support for sequential elements as well.

**Comment by hcw70** [comment]
Thank you. i will have a look!
