### ISSUE TITLE
Generated model fails with "TypeError: 'Field' object is not callable"

### ISSUE THREAD

**Issue by strongly-typed** [tefra/xsdata#275]
I am new to xsdata and using this XSD [x3d-3.3.xsd](https://www.web3d.org/specifications/x3d-3.3.xsd). Generation works fine but the import of the model fails with

```python
TypeError: 'Field' object is not callable
```

and `Fields` is from Python `dataclasses`.

I quickly setup a GitHub Action to demonstrate the behaviour [here](https://github.com/strongly-typed/xsdata-test/runs/1192451995?check_suite_focus=true#step:5:13).

Do I use this in a wrong way or is this a bug? In xsdata or in the XSD?

Ultimately, I would like to generate models from this [XSD](https://www.design2machine.com/btlx/btlx_11.xsd) which includes `x3d-3.3.xsd`.

Any help appreciated.

**Comment by tefra** [comment]
Hey @strongly-typed The word `field` was added in the reserved keywords list very recently, you can switch to the latest master until  the next release.

![Screenshot from 2020-10-01 12-34-07](https://user-images.githubusercontent.com/2098915/94793088-9c050900-03e2-11eb-8488-23c1a5771770.png)

Here a test run for your xsd with latest master and a mypy run to verify there are no errors

``console
❯ xsdata https://www.design2machine.com/btlx/btlx_11.xsd
Parsing schema btlx_11.xsd
Parsing schema x3d-3.3.xsd
Parsing schema x3d-3.3-Web3dExtensionsPublic.xsd
Compiling schema x3d-3.3-Web3dExtensionsPublic.xsd
Builder: 2 main and 0 inner classes
Parsing schema x3d-3.3-Web3dExtensionsPrivate.xsd
Compiling schema x3d-3.3-Web3dExtensionsPrivate.xsd
Compiling schema x3d-3.3.xsd
Builder: 481 main and 1 inner classes
Compiling schema btlx_11.xsd
Builder: 125 main and 35 inner classes
Analyzer input: 608 main and 36 inner classes
Analyzer output: 502 main and 35 inner classes
Generating package: init
Generating package: generated.x3d_3_3_web3d_extensions_public
Generating package: generated.x3d_3_3
Generating package: generated.btlx_11
❯ mypy generated
Success: no issues found in 4 source files

```

**Comment by strongly-typed** [comment]
Hey @tefra! Awesome! 🎉
[✔️](https://github.com/strongly-typed/xsdata-test/runs/1192711119?check_suite_focus=true#step:5:160) [✔️](https://github.com/strongly-typed/xsdata-test/runs/1192711119?check_suite_focus=true#step:6:2)

When is the next release expected?

**Comment by tefra** [comment]
Early next week!
