### ISSUE TITLE
xsi:type not working on xsd:anyType elements

### ISSUE THREAD

**Issue by mihxil** [tefra/xsdata#306]
I have a use case were we wrap lists of 'items' in an xml where the elements are in the xsd marked as 'xs:anyType'.

The xml though specifies the type with something like:
` xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="api:searchResultItem" `
so, the actual type is specified with an xsi:type attribute.

If I unmarshal this xml with xsdata these object just become `AnyElement`s and are not unmarshaled to the correct type (as e.g. pyxb and jaxb would do).

I don't rule out that I do something wrong, but as far as I looked into the code it is not supported at all. But please  correct me if I'm wrong.

**Comment by tefra** [comment]
Hi @mihxil 

yes currently on `xs:anyType` derived fields there are no lookups in place to match the actual model even when an `xsi:type` is provided. 

Its a bit tricky because the parser needs to scan the whole context to match any defined models that match the active qualified name, but it's definitely one of the next things I want to work on.

**Comment by tefra** [comment]
I am sure I can find examples from the w3c suite but it would be great if you could share your schema and a sample xml.

**Comment by mihxil** [comment]
I was just trying it out in a project that currently uses pyxb. Approximately at this line:
https://github.com/npo-poms/pyapi/blob/feature/xsdata/tests/unit/xml_test.py#L191
I became aware of the problem.

I'm sure that I can make up a simpler example though.

**Comment by tefra** [comment]
thank you @mihxil it's perfect.

**Comment by tefra** [comment]
@mihxil give it a try #310 I still want to tweak a few things but the xsi:type lookup should work for your case.

**Comment by tefra** [comment]
@mihxil I 've merged the updates to master, I have included your test case in [samples](https://github.com/tefra/xsdata-samples/tree/master/npo) repo as well.

Surprisingly the w3c test suite only a few similar test cases but none of them are so thorough with different namespaces / modules.

**Comment by mihxil** [comment]
Thansk a lot. I'll take a further look as soon as I've some time!
