### ISSUE TITLE
auto generated document format

### ISSUE THREAD

**Issue by egemenimre** [tefra/xsdata#318]
Hallo,

I see that the auto-generated document stubs for the generated classes is ReST. Are there any plans to offer this in Numpy standard or something like that? Admittedly, this is a "nice-to-have" but it would make comments easier for many people.

Btw, thanks for the excellent library, I have generated the entire set of CCSDS Navigation Data Messages (bunch of xsd files) through xsdata and it produced very clean code with clear classes.
(https://github.com/egemenimre/ccsds-ndm/tree/main/src/examples/xsdata_example/ndmxml directory)

**Comment by egemenimre** [comment]
I am no fan of adding more dependencies than is absolutely needed but maybe [pyment](https://github.com/dadadel/pyment/) can be interesting as a post-processor to convert the docstrings.

**Comment by tefra** [comment]
It doesn't make sense to add post-processors to reformat stuff, you can do this already.

But I am interested of adding docstrings formats as a generator config option and use the jinja templates to render them accordingly.

**Comment by tefra** [comment]
Introduced docstring-style config #325
