### ISSUE TITLE
conda or conda-forge

### ISSUE THREAD

**Issue by egemenimre** [tefra/xsdata#319]
I am wondering whether there are any plans to submit the code to conda or conda-forge. 

Conda-forge requires all dependencies to be present in conda-forge as well and, as I will rely on xsData to read and write xml files from the auto-generated classes, this is a limitation for all the downstream packages. It would be great if you could consider it.

Cheers!

**Comment by tefra** [comment]
Thank you for the suggestion @egemenimre 

https://anaconda.org/conda-forge/xsdata

**Comment by egemenimre** [comment]
Thanks!

The first issue to conda-forge is a bit painful, but you can then automate
the process (bot automerge or something), so that when you send an updated
package to pypi, conda-forge senses that and updates your conda-forge
package accordingly. As long as you pass the conda-forge tests, you don't
have to do much, really.
