### ISSUE TITLE
noNamespaceSchemaLocation?

### ISSUE THREAD

**Issue by egemenimre** [tefra/xsdata#320]
I have been trying some "round-trip testing", reading an XML file and trying to write it to a file through xsData.  The output file seems to be missing the `xsi:noNamespaceSchemaLocation` info.

The source file starts with:
```
<?xml version="1.0" encoding="UTF-8"?>
<cdm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="https://sanaregistry.org/r/ndmxml/ndmxml-1.0-master.xsd"
     id="CCSDS_CDM_VERS" version="1.0">

    <header>
        <COMMENT>Sample CDM - XML version</COMMENT>
```
I read it and then write it to a file:
```
    # *** read XML file ***
    config = ParserConfig(fail_on_unknown_properties=True)
    parser = XmlParser(config=config)
    cdm = parser.from_path(xml_read_file_path, Cdm)

    # *** write XML file ***
    xml_write_file_path = Path(os.getcwd(), "..", "..", "sample_xml", "write_cdm.xml")
    serializer = XmlSerializer(pretty_print=True)
    xml = serializer.render(cdm, ns_map=parser.ns_map)
    xml_write_file_path.write_text(xml)
```

The written file is missing the `xsi:noNamespaceSchemaLocation` part:
```
<?xml version='1.0' encoding='UTF-8'?>
<cdm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="CCSDS_CDM_VERS" version="1.0">
  <header>
    <COMMENT>Sample CDM - XML version</COMMENT>
```
This part is clearly read but it seems to be discarded through the read process as I can no longer find it on the generated class or in the parser. Any ideas?

Cheers!

**Comment by tefra** [comment]
That attribute and in general all XMLSchema-instance attributes are more like instructions to processors (parsers, validators) and their values are not meant to be preserved between bindings but instead regenerated if **needed** like xsi:type and xsi:nil
The output will still validate against that schema just fine.

But it's not a bad idea to add a config option for the serializer to provide that manually, similar to other binding libraries like jaxb

**Comment by egemenimre** [comment]
This is not a bug as such, but more like a feature request, as I would like to keep or generate that information.

From what I understand, currently there is no way to write an attribute to the xml file through xsData, no?

**Comment by tefra** [comment]
yes currently there is no way, but I will add an option to the sterilizer in the next release
