### ISSUE TITLE
Something like CreateFromDocument or JAXBContext.newInstance?

### ISSUE THREAD

**Issue by mihxil** [tefra/xsdata#332]
If I want to parse XML it seems that I always have to specify the type:
```
XmlParser().from_string(data, <TYPE>)
```
In certain cases that would be overly restrictive.  IIRC pyxb generates a method like CreateFromDocument, and e.g. in JAXB you can use a JAXBContext which you can configure with the namespaces to recognise.

Als to xsdata generated classes seem to contains sufficient information. Element-name and namespace of the root element generally is enough to know the type to create. 

I may be missing something, but I don't see an easy way to accomplish this.

**Comment by tefra** [comment]
In pyxb you still need to know the module with the generated models right and in jaxb you have to register the types manually beforehand.

The jaxb api seems interesting and easy to implement.

**Comment by tefra** [comment]
Ideas

Use the parser directly 

```python
parser = XmlParser()
parser.register_type(ClassA)
parser.register_type(ClassB)
parser.register_type(ClassC)

parser.from_string(data)
```

or maybe utilize the existing XmlContext registry

```python
context = XmlContext()
context.build(ClassA)
context.build(ClassB)
context.build(ClassC)

parser = XmlParser(context=context)
parser.from_string(data)  # Add the logic in the interface to locate the correct type
```

or even go full jaxb and hide the parser internally and also avoid changing the existing api of the parser

```python
context = XmlContext()
context.build(ClassA)
context.build(ClassB)
context.build(ClassC)

unmarshaller = XmlUnmarshaller(context=context)  # Complete separation of logic
unmarshaller.from_string(data)
```

**Comment by tefra** [comment]
@mihxil give it a try #335, the type in now optional, as long as the models module has been imported the parser should be able to locate the target type.


```python
XmlParser().from_string(data)
```

**Comment by mihxil** [comment]
Thanks, I'll try.
