### ISSUE TITLE
UnitTests errors: jinja2.exceptions.TemplateSyntaxError: tag name expected

### ISSUE THREAD

**Issue by eLvErDe** [tefra/xsdata#336]
Hello,

I'm working in getting your package into Debian archive but on ma machine 16 unittests are failing, all related to jinja2 with the same error, e.g:

```
self = <jinja2.parser.Parser object at 0x7ff080b08b38>, msg = 'tag name expected', lineno = 2, exc = <class 'jinja2.exceptions.TemplateSyntaxError'>

    def fail(self, msg, lineno=None, exc=TemplateSyntaxError):
        """Convenience method that raises `exc` with the message, passed
        line number or last line number as well as the current name and
        filename.
        """
        if lineno is None:
            lineno = self.stream.current.lineno
>       raise exc(msg, lineno, self.name, self.filename)
E       jinja2.exceptions.TemplateSyntaxError: tag name expected

/usr/lib/python3/dist-packages/jinja2/parser.py:59: TemplateSyntaxError
```

Any idea ?

Thanks

**Comment by tefra** [comment]
Thanks for reporting @eLvErDe 

I rechecked all the templates and I actually found a typo, which is there since August :scream:  

I have pushed the fix on master, let me know if that fixes your error.

Can you please help me understand why this got undetected till now, because the ci in this repo, the samples repo and the w3c-test-suite repo should have failed but they didn't.

What procedure do you follow to create the deb package, also can you list all the python package versions in your environment?

**Comment by eLvErDe** [comment]
Hello,

Debian package is available here:
https://salsa.debian.org/python-team/packages/python-xsdata

But it is not ready for inclusing yet as it depends on click-default-group and docformatter (which is also depending on untokenizer). I also have prepared all theses dependencies.

My main system is running Debian Buster and with stable jinja2 package 2.10, tests failed, with Debian Unstable version which is 2.11.2, it works.

I'm checking the patch now and will report back

**Comment by tefra** [comment]
I just testeds with jinja2==2.10 and I got the failures

```console
===================================================== short test summary info =====================================================
FAILED tests/formats/dataclass/test_generator.py::DataclassGeneratorTests::test_render_module - jinja2.exceptions.TemplateSyntax...
FAILED tests/integration/test_books.py::test_books_schema - jinja2.exceptions.TemplateSyntaxError: tag name expected
FAILED tests/integration/test_calculator.py::CalculatorServiceTests::test_wsdl_codegen - jinja2.exceptions.TemplateSyntaxError: ...
FAILED tests/integration/test_defxmlschema.py::test_definitive_xml_schema_chapter_01 - jinja2.exceptions.TemplateSyntaxError: ta...
FAILED tests/integration/test_defxmlschema.py::test_definitive_xml_schema_chapter_03 - jinja2.exceptions.TemplateSyntaxError: ta...
FAILED tests/integration/test_defxmlschema.py::test_definitive_xml_schema_chapter_04 - jinja2.exceptions.TemplateSyntaxError: ta...
FAILED tests/integration/test_defxmlschema.py::test_definitive_xml_schema_chapter_05 - jinja2.exceptions.TemplateSyntaxError: ta...
FAILED tests/integration/test_defxmlschema.py::test_definitive_xml_schema_chapter_08 - jinja2.exceptions.TemplateSyntaxError: ta...
FAILED tests/integration/test_defxmlschema.py::test_definitive_xml_schema_chapter_10 - jinja2.exceptions.TemplateSyntaxError: ta...
FAILED tests/integration/test_defxmlschema.py::test_definitive_xml_schema_chapter_12 - jinja2.exceptions.TemplateSyntaxError: ta...
FAILED tests/integration/test_defxmlschema.py::test_definitive_xml_schema_chapter_13 - jinja2.exceptions.TemplateSyntaxError: ta...
FAILED tests/integration/test_defxmlschema.py::test_definitive_xml_schema_chapter_15 - jinja2.exceptions.TemplateSyntaxError: ta...
FAILED tests/integration/test_defxmlschema.py::test_definitive_xml_schema_chapter_16 - jinja2.exceptions.TemplateSyntaxError: ta...
FAILED tests/integration/test_defxmlschema.py::test_definitive_xml_schema_chapter_17 - jinja2.exceptions.TemplateSyntaxError: ta...
FAILED tests/integration/test_hello_rpc.py::HelloRpcServiceTests::test_wsdl_codegen - jinja2.exceptions.TemplateSyntaxError: tag...
FAILED tests/integration/test_primer.py::test_primer_schema - jinja2.exceptions.TemplateSyntaxError: tag name expected
===================================== 16 failed, 649 passed, 19 skipped, 2 warnings in 6.24s ======================================

```

Seems like recent versions of jinja2 are more forgiving and actually recover from small errors/typos

**Comment by eLvErDe** [comment]
Confirmed, cc9b746b5fc1de4090c46316b734adc0acd94678 restored jinja2 2.10 compat, thanks for the quick fix.

Also thanks for this library, I don't know yet how I'll use it but I have some work to do with very complex XSD and it generated typed dataclasses for it perfectly fine so it'll probably make my job a lot easier :D

**Comment by eLvErDe** [comment]
You might want to setup a couple of CI profiles using versions from common distributions, e.g: Ubuntu 18.04/20.04, Debian 10, CentOS 8, that could help spotting regression like this
