### ISSUE TITLE
Macro field disambiguation

### ISSUE THREAD

**Issue by untereiner** [tefra/xsdata#351]
Hello,

I am trying to convert a set of xml files using xsdata.
In one of these files I have an enum of units of measure.
Two of them end of with the same enum field in python:
- The field D[API] give D_API
- The field dAPI gives D_API too

What can I do to avoid that ?
I am thinking xsdata should generate different enum fields for different xml fields

PS: I was looking to gsoap. It generates the unicode of a symbol, for instance __D_x005bAPI_x005d and dAPI

**Comment by tefra** [comment]
The sanitizer misfires on this case, it is supposed to add an auto-increment suffix for duplicate enum members.

**Comment by tefra** [comment]
Thanks for reporting @untereiner the fix is on master c0a442bf01cb7fe86a832d528625b277eaaaf5e4

If you don't like the auto-increment suffixes you can always check the custom aliases in the generator config.

**Comment by untereiner** [comment]
Thank you @tefra. I will test it.
