### ISSUE TITLE
error with schema location

### ISSUE THREAD

**Issue by untereiner** [tefra/xsdata#353]
I have an xsd schema that reference an another schema as this:
`   <import namespace="http://www.w3.org/1999/xlink"
           schemaLocation="../../xlink/1.0.0/xlinks.xsd"/>
`
But xsdata uses the xlink.xsd schema embedded with it instead of the linked one
Since my xsd schema uses the xsi:simpleLink attribute that does not exist in xlink.xsd the generation fails

**Comment by tefra** [comment]
Since there is a custom schema location the generator should use that instead of the embedded version, the cli is trying to avoid hitting the official resource.

I am on it.

**Comment by tefra** [comment]
Thank you for reporting @untereiner 

The fix is on master @ 56339ad6ef62dde4511a4f51f71486b5e44dc207
