### ISSUE TITLE
SerializerConfig introduced 2 issues

### ISSUE THREAD

**Issue by jforand** [tefra/xsdata#357]
Hello,

1st issue is that the constructor interface for XmlSerializer changed.

```python
XmlSerializer(encoding=None)
```

no longer works. This is a smaller issue as I can change my code to support the new library (but it's still a change that isn't backwards compatible)

2nd issue is that the XmlWriter no longer supports encoding=None. This is a blocker, as I have a rest API that will not accept a payload with an encoding.

**Comment by tefra** [comment]
Yes, the last version broke the backwards compatibility, I know it's painful but it will be easier from now on to add new options.

The second one was never an intentional feature, more like a side effect for the lxml writer, I will take care of that.

**Comment by tefra** [comment]
Thanks for reporting @jforand the new SerializerConfig option is on mater @ a2eb1d2c70169063878d3cfe195f9f471abb35d8 
now it's possible to omit the xml declaration for all writers.

```python
    config = SerializerConfig(xml_declaration=False)
    serializer = XmlSerializer(config=config)
```

**Comment by jforand** [comment]
Perfect, thanks. That solves the issue nicely.
