### ISSUE TITLE
DateTime and Date Converters

### ISSUE THREAD

**Issue by captaincolonelfox** [tefra/xsdata#366]
I was trying to create such dataclass 

```
@dataclass
class GetByDate:
    class Meta:
        namespace = NAMESPACE

    date: datetime = field(
        default=None,
        metadata={
            "name": "Date",
            "type": "Element"
        }
    )
```

But when I trying to proceed request with date in it I got a warning:
```
/xsdata/formats/converter.py:123: ConverterWarning: No converter registered for `<class 'datetime.datetime'>`
  warnings.warn(f"No converter registered for `{data_type}`", ConverterWarning)
```
And maybe it would be nice to have datetime converter which will try to parse from most common datetimes formats such as

for datetimes:
- %y-%m-%dT%H:%M:%S
- %y-%m-%d %H:%M:%S
- ...and so on

for dates:
- %y-%m-%d
- %d-%m-%y
- ...and so on

And by default it can serialize datetimes to `%y-%m-%dT%H:%M:%S` or a local time format.
So a user can specify in a serializer config which format he wants to have

**Comment by tefra** [comment]
I have avoided mapping the xs:date, xs:dateTime, xs:time to python datetime for some time now because of all the possible [formats](http://books.xmlschemata.org/relaxng/ch19-77049.html), but it's definitely in my **todos**.

For now there is a way to register a custom converter see [here ](https://xsdata.readthedocs.io/en/latest/data-types.html#converters) and the full script [here](https://github.com/tefra/xsdata/blob/master/docs/examples/converter.py)

**Comment by captaincolonelfox** [comment]
Awesome, will look forward for this changes!

>because of all the possible [formats](http://books.xmlschemata.org/relaxng/ch19-77049.html)

Not sure if it will be useful for you, but you can do `try: ... except: continue` on a list of different formats and return the first succeeded

And thank you, I didn't know you can implement your own converter. I guess I will do it for now

**Comment by tefra** [comment]
Hey @captaincolonelfox 

Take a look [here](https://xsdata.readthedocs.io/en/latest/data-types.html#working-with-date-strings), I added support for custom date/time formats and standard iso 8601 xml date/times

It will be included in the next release

**Comment by captaincolonelfox** [comment]
@tefra Awesome, thank you for your work!
