### ISSUE TITLE
Strip namespace on serialization

### ISSUE THREAD

**Issue by eLvErDe** [tefra/xsdata#392]
Hello tefra,

I know we already had a quick exchange regarding this but I wanted to come back with a complete example of what is generated by XSdata and what other public and private providers export with the same XSD.

The following example is inspired by netherland traffic authorities and also features link to Microsoft and TomTom documentation also show examples without namespaces.

```python
"""
Datex2 generate XML has namespace info everywhere while it seems nobody else has them

Please generate datex2 models first by running:

  wget https://docs.datex2.eu/_static/data/v2.3/DATEXIISchema_2_2_3_0.zip -O /tmp/datex2_2_3.zip
  unzip /tmp/datex2_2_3.zip -d /tmp
  xsdata generate /tmp/DATEXIISchema_2_2_3.xsd --output pydata --package datexii.datexii_2_3

The example below has been mimiced from netherland OpenDATA publication available at:
  http://opendata.ndw.nu/incidents.xml.gz

Others examples are available at TomTom and Microsoft Here and also don't have the namespaces
  https://developer.tomtom.com/intermediate-traffic-service/intermediate-traffic-service/tomtom-traffic-incidents-intermediate-service-datex-ii
  https://developer.here.com/documentation/traffic-data-service/dev_guide/topics/traffic-incidents-response.html

So I am pretty sure this is NOT expected ;-)
"""


import datetime
import xml.dom.minidom

from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.models.datatype import XmlDateTime

from datexii.datexii_2_3 import (
    D2LogicalModel,
    Exchange,
    SituationPublication,
    InternationalIdentifier,
    CountryEnum,
    Subscription,
    OperatingModeEnum,
    UpdateMethodEnum,
    Target,
    Situation,
    SeverityEnum,
    VehicleObstruction,
    Mobility,
    MobilityEnum,
)


def build_datex2_2_3_situation_publication() -> SituationPublication:
    """
    Build Datex2 SituationPublication example

    :returns: SituationPublication xsdata object instance
    :rtype: SituationPublication
    """

    xml_dt_now = XmlDateTime.from_datetime(datetime.datetime.now(tz=datetime.timezone.utc))

    payload = D2LogicalModel(
        exchange=Exchange(
            supplier_identification=InternationalIdentifier(country=CountryEnum.NL, national_identifier="NLNWD"),
            subscription=Subscription(
                operating_mode=OperatingModeEnum.OPERATING_MODE3,
                subscription_start_time=xml_dt_now,
                update_method=UpdateMethodEnum.SNAPSHOT,
            ),
            target=Target(address=None, protocol="HTTP"),
        ),
        payload_publication=SituationPublication(
            lang="nl",
            publication_time=xml_dt_now,
            publication_creator=InternationalIdentifier(country=CountryEnum.NL, national_identifier="NLNDW"),
            situation=Situation(
                id="RWS03_968399",
                version="2",
                overall_severity=SeverityEnum.UNKNOWN,
                situation_version_time=xml_dt_now,
                situation_record=[
                    VehicleObstruction(id="RWS03_968399_1", version="2", mobility_of_obstruction=Mobility(mobility_type=MobilityEnum.STATIONARY))
                ],
            ),
        ),
    )
    return payload


if __name__ == "__main__":
    SERIALIZER = XmlSerializer()
    PAYLOAD = build_datex2_2_3_situation_publication()

    print(xml.dom.minidom.parseString(SERIALIZER.render(PAYLOAD)).toprettyxml())
```

Thanks a lot in advance, your library has been a GREAT help so far !

Regards, Adam.

**Comment by tefra** [comment]
The namespace is necessary otherwise the output won't validate against the schema, in the samples of tomtom they omit the definition in the top examples for readability but if you see some of the bottom examples, they have it in the output.

```xml
<?xml version="1.0" ?>
<d2LogicalModel
  xmlns="http://datex2.eu/schema/1_0/1_0"
  modelBaseVersion="1.0">
  [...]
  <payloadPublication
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:type="SituationPublication" lang="en">
```

Also from the https://developer.here.com/

```xml
<?xml version="1.0" encoding="UTF-8"?>
<d2LogicalModel xmlns="http://datex2.eu/schema/2/2_0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" modelBaseVersion="2" xsi:schemaLocation="http://datex2.eu/schema/2/2_3/DATEXIISchema_2_2_3.xsd">
   <exchange>
...
```

The `xmlns="http://datex2.eu/schema/2/2_0"` part is setting the default namespace for all elements. By default xsdata is adding prefixes to namespaces because it's not always possible to detect the default namespace from the models. Depends if they are derived from xs:element or xs:complexType, anyway it's irrelevant the result for all parsers across platforms is the same.

```xml
<ns0:d2LogicalModel xmlns:ns0="http://datex2.eu/schema/2/2_0" modelBaseVersion="2">
  <ns0:exchange>
    <ns0:supplierIdentification>
      <ns0:country>nl</ns0:country>
      <ns0:nationalIdentifier>NLNWD</ns0:nationalIdentifier>
    </ns0:supplierIdentification
```

You can set that namespace as the default manually during serialization to avoid the prefixes by providing a custom namespace prefix-URI mapping. That way you can get the same exact output as the samples above.

```python
config = SerializerConfig(pretty_print=True)
SERIALIZER = XmlSerializer(config=config)
PAYLOAD = build_datex2_2_3_situation_publication()

print(SERIALIZER.render(PAYLOAD, ns_map={None: "http://datex2.eu/schema/2/2_0"}))

```xml
<d2LogicalModel xmlns="http://datex2.eu/schema/2/2_0" modelBaseVersion="2">
  <exchange>
    <supplierIdentification>
      <country>nl</country>
      <nationalIdentifier>NLNWD</nationalIdentifier>
    </supplierIdentification>
```

By the way, I am curious why you use minidom for pretty-print? Have you noticed anything wrong with the indentation of the xsdata writers?

**Comment by tefra** [comment]
Note to self `XmlDateTime` needs `now()` classmethod

**Comment by eLvErDe** [comment]
Hello,

Thanks a lot for the complète explanation, is it possible to add an example if I have multiple namespace ? Newest versions of the datex2 schema has been split in different namespaces so I get ns0/ns1/ns2.
I can provide an example if you want :-)

For prettyprint, I initially made my test using and older version of xsdata not having the serializer config, just need to check how it works and ditch minidom.

For XML datetime, yeah that could be an option, but others features are also needed like datetime replace to zero microseconds and tz kwargs to display time in local timezone. I haven't looked at the complete definition of this class so it might be available already, if not you might consider my suggestion if you're modifying the class.

**Comment by tefra** [comment]
If I understood correctly you want something like this?

```xml
<root xlmns="foo">
    <sub xlmns="bar">
    </sub>
</root>
```

Unfortunately that's not possible at the moment, xsdata can only create one default namespace per document.

Printing [XmlDateTime](https://xsdata.readthedocs.io/en/latest/api/reference/xsdata.models.datatype.XmlDateTime.html#xsdata.models.datatype.XmlDateTime) will trim zero microseconds

```python
In [10]: from datetime import datetime, timezone, timedelta
In [11]: from xsdata.models.datatype import XmlDateTime

In [12]: str(XmlDateTime.from_datetime(datetime.now(tz=timezone.utc)))
Out[12]: '2021-01-22T17:59:22.471679Z'

In [13]: str(XmlDateTime.from_datetime(datetime.now(tz=timezone.utc).replace(microsecond=123000)))
Out[13]: '2021-01-22T17:59:43.123Z'

In [14]: str(XmlDateTime.from_datetime(datetime.now(tz=timezone.utc).replace(microsecond=0)))
Out[14]: '2021-01-22T17:59:51Z'
```

Note to self the built in datatypes are immutable and could benefit from a replace method.

**Comment by eLvErDe** [comment]
For the nested namespace yes, that's exactly how it looks elsewhere. Let me know if you decide to implement this at some point :)

For the datetime, it's indeed like that, mimicing datetime behavior that looks sane to me

**Comment by tefra** [comment]
Most of xml writers are based on SAX events, which is great for performance but tricky to change the namespaces prefixes for nested elements. 

Each element has it's own namespace context that starts and ends with the element. By initializing the ns prefix-URI mapping you initialize the context for all elements in the document and because its key-value mapping you can't really set the sub element namespace prefix to None. I 'll keep it in mind.

I am going to close this one and open another one for the XmlDateTime helpers
