### ISSUE TITLE
Unknown property error during parsing 

### ISSUE THREAD

**Issue by Przemek625** [tefra/xsdata#403]
During parsing document occured an error: 

`xsdata.exceptions.ParserError: Unknown property {http://www.w3.org/2001/XMLSchema}schema:head
` 

To reproduce the error run
`xsdata generate https://github.com/erasmus-without-paper/ewp-specs-api-omobility-las/blob/v0.3.0/endpoints/index-response.xsd
`

**Comment by tefra** [comment]
What version are you using @Przemek625?

```console
❯ xsdata generate https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-discovery/stable-v5/manifest.xsd
Parsing schema manifest.xsd
Parsing schema xml.xsd
Compiling schema xml.xsd
Builder: 5 main and 2 inner classes
Parsing schema common-types.xsd
Compiling schema common-types.xsd
Builder: 20 main and 0 inner classes
Parsing schema catalogue.xsd
Compiling schema catalogue.xsd
Builder: 4 main and 11 inner classes
Compiling schema manifest.xsd
Builder: 2 main and 3 inner classes
Analyzer input: 31 main and 16 inner classes
Analyzer output: 19 main and 13 inner classes
Generating package: init
Generating package: init
Generating package: init
Generating package: init
Generating package: init
Generating package: init
Generating package: init
Generating package: init
Generating package: generated.ewp_specs_architecture.stable_v1.common_types
Generating package: generated.ewp_specs_api_registry.stable_v1.catalogue
Generating package: generated.ewp_specs_api_discovery.stable_v5.manifest
Generating package: generated.xml
❯ xsdata --version
xsdata, version 21.2
```

**Comment by tefra** [comment]
Oh there is a mess on the generated.ewp_specs_architecture.stable_v1.common_types some docstrings are breaking syntax, are you talking about that?

**Comment by Przemek625** [comment]
I use 

```
xsdata --version
xsdata, version 21.1
```

I am not talking about the docstrings that break syntax. Simply ` xsdata generate` the command failed and in the output was this

`xsdata.exceptions.ParserError: Unknown property {http://www.w3.org/2001/XMLSchema}schema:head
`
Hmmm... I noticed that you have newer verision I will update library version and I will let you know if it helped. 

As always thanks for help and I will get back to you with more details soon.

**Comment by tefra** [comment]
Yeah the latest version seems to be working during parsing but the docstring filters are breaking the syntax, I am working on it.

**Comment by Przemek625** [comment]
@tefra Sorry. I made a mistake. I used wrong url(that forunately works). To reporduce the issue use run this:

`xsdata generate https://github.com/erasmus-without-paper/ewp-specs-api-omobility-las/blob/v0.3.0/endpoints/index-response.xsd`

**Comment by tefra** [comment]
You are using the the github page and not the xsd file, the parser is doing its best because sometimes it's valid for the root qualified name not to match the model but it's failing on the next one which is the html > head tag

switch your url to  https://raw.githubusercontent.com/erasmus-without-paper/ewp-specs-api-omobility-las/v0.3.0/endpoints/index-response.xsd

xsdata comes with a download command, which works for most of the cases in order to avoid fetching the remote sources every time. ```xsdata download $uri```

**Comment by tefra** [comment]
self note: I still don't like the error message

**Comment by Przemek625** [comment]
@tefra You are right. Sorry, It was clearly my fault. I did noticed that url lead to gighub instead of the raw xml.

**Comment by tefra** [comment]
Thank you @Przemek625 at least you found that issue with the triple quotes, the fix is on master
