### ISSUE TITLE
Additional Decorators

### ISSUE THREAD

**Issue by gokgozf** [tefra/xsdata#413]
Hi @tefra 

Would it be difficult to provide a mechanism to add aditional decorators for the generated classes? 

e.g. 
https://pypi.org/project/pure-protobuf/
https://pypi.org/project/dataclasses-json/

**Comment by tefra** [comment]
The mechanism to add more output formats exists, the goal is to make it pluggable at some point so people can create custom generators, but I am afraid it's not actually high in priorities.

FIY xsdata can do json

**Comment by gokgozf** [comment]
Sure json serialization is possible with xsdata, those were just examplary cases. If you planed any particular place to make this option pluggable I might be able to send pull request based on your requirements.

**Comment by tefra** [comment]
@gokgozf 

The code generators are now pluggable, I extracted the plantuml output format to a standalone plugin here https://github.com/tefra/xsdata-plantuml

The api is not yet documented but it's a start, I suggested starting by extending the dataclasses generator with its templates and filters and taking it from there https://github.com/tefra/xsdata/blob/8b325a28f319248e383ff38e774bfbe110fd6722/xsdata/formats/dataclass/generator.py#L19
