### ISSUE TITLE
Package names are normalized

### ISSUE THREAD

**Issue by gganssauge** [tefra/xsdata#416]
I'm developing in an environment where package names don't conform to PEP-8, i.e. they are CamelCase, e.g. Products.RESTService.
Unfortunately, when generating with _--package_ the package name is obviously normalized to complete lowercase.

As a consequence I can't generate using _--package_ because the generated modules are written to the wrong folders.

For a workaround I tried to generate with _--print_ and redirect the output to the correct file - but that failed due to the \_\_init\_\_ modules not being generated.

For another workaround I tried to generate with _--package=._, but that failed as well because the resulting files were written to directory _pkg/pkg_.

Furthermore the generated \_\_init\_\_ modules contained absolute imports from _pkg.pkg_ instead of using a relative import, so I couldn't move the generated files.

Is there any chance for a workaround here?

**Comment by tefra** [comment]
You can change the naming scheme applied to package/module names through a project configuration 

```xml
 <Conventions>
    <ClassName case="pascalCase" safePrefix="type"/>
    <FieldName case="snakeCase" safePrefix="value"/>
    <ConstantName case="screamingSnakeCase" safePrefix="value"/>
    <ModuleName case="snakeCase" safePrefix="mod"/>
    <PackageName case="snakeCase" safePrefix="pkg"/>
  </Conventions>
```

How to create and use a project config
https://xsdata.readthedocs.io/en/latest/codegen.html#initialize-config

Generator Configuration reference
https://xsdata.readthedocs.io/en/latest/api/codegen.html

Check the available naming schemes and let me know if one of them fits your needs
https://xsdata.readthedocs.io/en/latest/api/reference/xsdata.models.config.NameCase.html#xsdata.models.config.NameCase

**Comment by tefra** [comment]
Note to self: relative imports sounds interesting 💯

**Comment by gganssauge** [comment]
Thanks for the info.
The use of configuration files is a tad complex because you can't override their settings with command line arguments.

Suppose I want to recursively generate Python modules for all XSD  schemata in a package hierarchy, and I want to create each module in the schema's folder.
For that task I'd need to create a configuration file for every schema I find in order to generate a module in the right folder/package.

All doable - but unneccessary clumsy.

I did check the naming schemes - I'm missing ORIGINAL - assuming the caller knows about the naming conventions in his/her hierarchy and can't copy with any of the others. For ym case, probably MIXED would be ok, but that's only because I'm not aware of a package having '_' in its name. In that case I'd need to use MIXED_SNAKE which would destroy names without '_', adding '_' to them if they contain capitals within a name.

I suppose letting command line arguments override configuration properties would be quite easy (I could prepare a pull request if you like).
Also a naming convention ORIGINAL would be no witchwork, I guess.

Both probably would improve the useability considerably, though.

**Comment by tefra** [comment]
Ty @gganssauge 

I will add the original naming scheme and allow the cli package argument to override the config's setting.

**Comment by tefra** [comment]
The new naming scheme `originalCase` and the ability to override the package config with the cli argument are both on master and will be included in the next release.
