### ISSUE TITLE
Light library CLI as extras

### ISSUE THREAD

**Issue by jules-ch** [tefra/xsdata#419]
Thank you for developping this neat lib to bind XML to Data object. :)
When running this lib, I need CLI dependencies only for dev but not when running my webservice :

Code generation / CLI :
- click
- jinja2
- docformatter
- toposort

WSDL/SOAP:
- requests

Maybe we can consider adding this as extras to have a light library for parsing & serializing. (only lxml as dependency)

**Comment by tefra** [comment]
Sounds great!

**Comment by tefra** [comment]
Thank you for the suggestion @jules-ch 

Three extra requirements were added to make the cli, wsdl client and lxml for binding optional.

```console
pip install git+https://github.com/tefra/xsdata@master#egg=xsdata[cli,lxml,soap]
```

**Comment by jules-ch** [comment]
Awesome !
