### ISSUE TITLE
"ParserError: Unknown property" when running generate

### ISSUE THREAD

**Issue by highviolet** [tefra/xsdata#420]
Hi!

I'm trying to generate dataclasses from a XSD file.
The following is raised:
"ParserError: Unknown property {http://www.w3.org/2001/XMLSchema}Annotation:{http://www.w3.org/2001/XMLSchema}appinfo"

Perhaps it would be valuable to add an option to set ParserConfig.fail_on_unknown_properties = False from the main entry point.

Thanks!

**Comment by tefra** [comment]
Can you share your schema?

**Comment by highviolet** [comment]
This should be a minimal reproducible example:



```
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:rmg="http://www.somecompany.com/xml/schema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.somecompany.com/xml/schema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:complexType name="someComplex_type">
		<xsd:annotation>
			<xsd:appinfo>
				<rmg:aDimensions>
					<rmg:aDimension>
						<rmg:dimension>aValue</rmg:dimension>
					</rmg:aDimension>
				</rmg:aDimensions>
			</xsd:appinfo>
			<xsd:appinfo>
				<rmg:bDimensions>
					<rmg:bDimension>
						<rmg:dimension>bValue</rmg:dimension>
					</rmg:bDimension>
				</rmg:bDimensions>
			</xsd:appinfo>
		</xsd:annotation>
	</xsd:complexType>
</xsd:schema>
```

**Comment by tefra** [comment]
Thank you @highviolet, the internal schema model for xsd:annotation is set to accept only one appinfo element, which you are right is [wrong](https://www.w3schools.com/xml/el_annotation.asp)

**Comment by tefra** [comment]
The fix is on master and will be included in the next release

**Comment by highviolet** [comment]
Thanks a lot!!
