### ISSUE TITLE
XML list[str] Wrapper?

### ISSUE THREAD

**Issue by ctzen** [tefra/xsdata#428]
First, thanks for this wonderful module.

Given:

```
@dataclass
class Foo:
    bars: list[str] = field(metadata={'name': 'bar'})
```

It currently serialize to XML as: 

```
<Foo>
    <bar>BAR 1</bar>
    <bar>BAR n</bar>
</Foo>
```

Is it possible to add wrapper `<bars>`, as in:

```
<Foo>
    <bars>
        <bar>BAR 1</bar>
        <bar>BAR n</bar>
    </bars>
</Foo>
```

Sadly, the dataclass structure cannot be changed. 
`bars` needs to serialize to JSON as list of strings `"bars": ["BAR 1", "BAR n"]`
and wrapped in XML `<bars><bar>BAR 1</bar><bar>BAR n</bar></bars>`

**Comment by tefra** [comment]
That's not really possible, even if there was such a field property to wrap list values it would still do exactly the same for both xml, json formats.

I would try to get the xml structure right with models first and they try to create a custom serializer for json which is a bit easier to extend

https://github.com/tefra/xsdata/blob/3c193bed2e94f510d4d87157083ec04193edf9cb/xsdata/formats/dataclass/serializers/json.py#L33


Have you seen such feature for other languages / libraries

**Comment by ctzen** [comment]
Understand.  Sadly the data structure is fixed.

It is only a problem for me because I am making a API client to test both JSON and XML and trying to use the same dataclass. For real clients, they only have to adhere to JSON or XML.

As for such feature for other language, the source of this structure is in Java with JaxB annotations:

```
    @XmlElementWrapper(name = "bars")
    @XmlElement(name = "bar")
    List<String> bars; 
```

It serializes to both JSON list and XML as I described.

BTW, is it possible to ask your JsonSerializer to omit nulls/None?

**Comment by ctzen** [comment]
Managed with this work-around.

```
@dataclass
class Bars:
    bar: list[str] = field(metadata=dict(type='Element'))

@dataclass
class Foo:
    bars: Bars or list[str]
```

When need JSON, populate Foo.bars with list[str]:
```
"bars": [ "x", "y" ]
```

When need XML, populate Foo.bars with Bars:
```
<bars>
    <bar>x</bar>
    <bar>y</bar>
</bars>
```

Seems to work ;-)

**Comment by tefra** [comment]
That's one way to achieve it, yeah type unions are supported... 


Regarding filtering null values, you can provide a custom `dict` factory to the JsonSerializer to filter them, there is one builtin but you could pass any custom callable.

```
from xsdata.formats.dataclass.serializers.json import DictFactory
from xsdata.formats.dataclass.serializers.json import JsonSerializer

JsonSerializer(dict_factory=DictFactory.FILTER_NONE)
```

**Comment by ctzen** [comment]
> That's one way to achieve it, yeah type unions are supported...
> 
> Regarding filtering null values, you can provide a custom `dict` factory to the JsonSerializer to filter them, there is one builtin but you could pass any custom callable.
> 
> ```python
> from xsdata.formats.dataclass.serializers.json import DictFactory
> from xsdata.formats.dataclass.serializers.json import JsonSerializer
> 
> JsonSerializer(dict_factory=DictFactory.FILTER_NONE)
> ```

works! Thank you.
