### ISSUE TITLE
Parsing / generating custom namespaced elements inside an SVG document

### ISSUE THREAD

**Issue by SeanDS** [tefra/xsdata#444]
I've defined some custom namespaced elements inside an SVG document, as shown below. I'd like to be able to parse the inner `<svg>` element and sub-elements into Python dataclass objects using xsdata.

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:myapp="http://example.com" width="10.671" height="29.096" overflow="visible">
  	<defs>
		<linearGradient id="a" x1="0" x2="0" y1="43.03" y2="14.683" gradientTransform="matrix(.35 0 0 1 -117.195 -14.309)" gradientUnits="userSpaceOnUse">
			<stop offset="0" stop-color="#89a4b6"/>
			<stop offset="0.5" stop-color="#fff"/>
			<stop offset="1" stop-color="#89a4b6"/>
		</linearGradient>

                <!-- This is the start of my stuff -->
		<svg id="myitem" myapp:name="myitem" myapp:origin-x="0" myapp:origin-y="50%">
			<myapp:port myapp:name="p1" myapp:offset-x="0" myapp:offset-y="0">
				<myapp:node myapp:name="i" myapp:normal="0°"/>
				<myapp:node myapp:name="o" myapp:normal="180°"/>
			</myapp:port>
			<myapp:port myapp:name="p2" myapp:offset-x="100%" myapp:offset-y="0">
				<myapp:node myapp:name="i" myapp:couples-with="p1.o"/>
				<myapp:node myapp:name="o" myapp:couples-with="p1.i"/>
			</myapp:port>
			<path fill="url(#a)" stroke="#000" stroke-width=".75" d="M.375.375h9.921v28.346H.375z"/>
			<path stroke="#000" stroke-width=".75" d="M7.46.375h2.836v28.346H7.46z"/>
		</svg>
                <!-- This is the end of my stuff -->
  	</defs>

	<use x="0" y="0" href="#myitem"/>
</svg>
```

When I run `xsdata generate /path/to/file.svg` it generates a bunch of dataclasses for the SVG namespace (`Svg`, `Defs`, `LinearGradient`, `Use`, etc.) as well as the "myapp" namespace I defined myself. I'd rather not generate code for the whole SVG spec, just for the stuff I care about - I don't need the rest of the document to be parsed into Python objects. Can I limit xsdata to only generate dataclasses for the stuff in my namespace, and later, when parsing, ignore anything in the document that isn't part of my namespace?

Would it be simpler to write an XSD file for my custom namespace instead?

**Comment by tefra** [comment]
The generator treats this case as raw xml document, that means it will try to create the necessary data binding models for that document **specifically**. Currently there is no config option to ignore some of the classes, but since you have access to the document you could always modify it to cut down what you don't need.


```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:myapp="http://example.com" id="myitem" myapp:name="myitem" myapp:origin-x="0" myapp:origin-y="50%">
  <myapp:port myapp:name="p1" myapp:offset-x="0" myapp:offset-y="0">
    <myapp:node myapp:name="i" myapp:normal="0°" />
    <myapp:node myapp:name="o" myapp:normal="180°" />
  </myapp:port>
  <myapp:port myapp:name="p2" myapp:offset-x="100%" myapp:offset-y="0">
    <myapp:node myapp:name="i" myapp:couples-with="p1.o" />
    <myapp:node myapp:name="o" myapp:couples-with="p1.i" />
  </myapp:port>
  <path fill="url(#a)" stroke="#000" stroke-width=".75" d="M.375.375h9.921v28.346H.375z" />
  <path stroke="#000" stroke-width=".75" d="M7.46.375h2.836v28.346H7.46z" />
</svg>
```

A schema is always better, less guessing with types but the xml transformer does a pretty decent job, it's up to you, which one you prefer.

**Comment by SeanDS** [comment]
Great, thanks for the info!
