### ISSUE TITLE
cycles

### ISSUE THREAD

**Issue by untereiner** [tefra/xsdata#450]
Hello,

I am working on the complete set of xsd I sent to you a while ago.
I can generate the classes. But, I tested to import one and I have a lot of circular imports. 

It think this is due to a mismatch between the conceptual split into xsd files and the xml namespaces what are common accross this conceptual split.

I think it would be possible to avoid these circular imports if I could generate the package into sub-packages for each xml leaf from the namespace tree.

I would give it a try. Could you give me some hints to do it ?

Thansk

**Comment by tefra** [comment]
Have you tried using the `--ns-struct` flag? 
This will group the classes per namespace.

https://xsdata.readthedocs.io/en/latest/codegen.html

**Comment by untereiner** [comment]
I tried but it has no effect

**Comment by tefra** [comment]
Hrm which class is giving you issues?

Run with `--ns-struct`

```console
Analyzer output: 1038 main and 0 inner classes
Generating package: init
Generating package: issue2.models.opengis_net_gml_3_2
Generating package: issue2.models.energistics_org_energyml_data_commonv2
Generating package: issue2.models.energistics_org_energyml_data_resqmlv2
```

```
In [1]: from issue2.models import *

In [2]: print("all good")
all good

In [3]: from issue2.models import AbstractCoordinateOperation

In [4]: 

```


Make sure you remove all the previously generated packages

**Comment by untereiner** [comment]
ok I was using this command line
`python xsdata/cli.py generate --ns-struct my_folder/`

but I had this .xsdata config file

 ```xml
<?xml version="1.0" encoding="UTF-8"?>
<Config xmlns="http://pypi.org/project/xsdata" version="21.2">
  <Output maxLineLength="79">
    <Package>generated</Package>
    <Format>dataclasses</Format>
    <Structure>filenames</Structure>
    <DocstringStyle>reStructuredText</DocstringStyle>
    <CompoundFields>false</CompoundFields>
  </Output>
  <Conventions>
    <ClassName case="pascalCase" safePrefix="type"/>
    <FieldName case="snakeCase" safePrefix="value"/>
    <ConstantName case="screamingSnakeCase" safePrefix="value"/>
    <ModuleName case="snakeCase" safePrefix="mod"/>
    <PackageName case="snakeCase" safePrefix="pkg"/>
  </Conventions>
  <Aliases>
    <ClassName source="fooType" target="Foo"/>
    <ClassName source="ABCSomething" target="ABCSomething"/>
    <FieldName source="ChangeofGauge" target="change_of_gauge"/>
    <PackageName source="http://www.w3.org/1999/xhtml" target="xtml"/>
    <ModuleName source="2010.1" target="2020a"/>
  </Aliases>
</Config>
 ```

It supersedes the command line option I gave.
It worked when I moved this file.

**Comment by tefra** [comment]
Cool, I will make a note to make the cli argument to override the config

**Comment by tefra** [comment]
cli --ns-struct should now override the config #463
