### ISSUE TITLE
Support frozen dataclasses

### ISSUE THREAD

**Issue by neriusmika** [tefra/xsdata#456]
It would be nice to have immutable schemas with (frozen=True). In such cases, when generating schemas automatically, types should be immutable by default. E.g. Tuple, instead of List. And deserialization code must handle these types accordingly.

**Comment by tefra** [comment]
Hey @neriusmika give it a [try](https://xsdata.readthedocs.io/en/latest/examples/dataclasses-features.html#dataclasses-features),

Samples [repo / ubl](https://github.com/tefra/xsdata-samples/tree/master/ubl)
