### ISSUE TITLE
Typing issues

### ISSUE THREAD

**Issue by neriusmika** [tefra/xsdata#466]
With UBL schemas, I found 2 problems in file common\ubl_xad_esv132_2_1.py:

1) Mypy complains about the generic `Dict` type in a strict mode:
```python
@dataclass
class AnyType:
    any_element: List[object] = field(
        default_factory=list,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
            "mixed": True,
        },
    )
    any_attributes: Dict = field(
        default_factory=dict,
        metadata={
            "type": "Attributes",
            "namespace": "##any",
        },
    )
```
XML attributes are always strings, can we change that type hint to `Dict[str, str]`?

2) The type of inherited field `OtherTimeStampType.encapsulated_time_stamp` is different from the base class.

**Comment by tefra** [comment]
Thanks for reporing @neriusmika 

Yeah the first one is pretty straightforward and you are correct the keys and values are always str.
The second one not so much, I have encountered it before but I am not really sure how to handle it.

In the base class the element is effectively a list where in the subclass the element has effectively `maxOccurs=1`

```xsd
<xsd:complexType name="GenericTimeStampType" abstract="true">
    <xsd:sequence>
                   ...
        <xsd:choice maxOccurs="unbounded"><!-- maxOccurs > 1 aka list -->
            <xsd:element name="EncapsulatedTimeStamp" type="EncapsulatedPKIDataType"/>
            <xsd:element name="XMLTimeStamp" type="AnyType"/>
        </xsd:choice>
    </xsd:sequence>
   ...
   ...

<xsd:complexType name="OtherTimeStampType">
    <xsd:complexContent>
        <xsd:restriction base="GenericTimeStampType">
            <xsd:sequence>
                ...
                ...
                <xsd:choice>  <!-- maxOccurs=1 -->
                    <xsd:element name="EncapsulatedTimeStamp" type="EncapsulatedPKIDataType"/>
                    <xsd:element name="XMLTimeStamp" type="AnyType"/>
                </xsd:choice>
            </xsd:sequence>
```

One way would be to simply keep the element as a list in the subclass, xjc (java) completely ignores the subclass fields by simple generating an empty class extending the base class. I ''ll have to think about it and run a few tests.

**Comment by neriusmika** [comment]
Yes, these rare cases with restrictions smell. My intuition says, that making a whole new python class without inheritance will cause fewer problems. Of course, you can't reuse code from the base class, but doing so would be dangerous anyway. Liskov violation etc.

**Comment by tefra** [comment]
Hi @neriusmika 

Thanks for reporting, this issue triggered a series of some very important updates :rocket: 

I have added the UBL collection in the samples [repo](https://github.com/tefra/xsdata-samples/runs/2502876120?check_suite_focus=true) it now passes all mypy checks.

**Comment by neriusmika** [comment]
Good news, thank you :clap:
