### ISSUE TITLE
AttributeError: 'XXXXXXXXXXXXX' object has no attribute 'items'

### ISSUE THREAD

**Issue by reidsneo** [tefra/xsdata#483]
Dear Maintainer,

I currently working with SIRI implementation of netex https://github.com/NeTEx-CEN/NeTEx
Then I generate the WSDL model using this command 

`xsdata xsd/wsdl/NeTEx_wsProducer-Document.wsdl --config .xsdata.xml`

`<?xml version="1.0" encoding="UTF-8"?>
<Config xmlns="http://pypi.org/project/xsdata" version="21.4">
  <Output maxLineLength="79">
    <Package>siri.wsdl.generated</Package>
    <Format>dataclasses</Format>
    <Structure>single-package</Structure>
    <DocstringStyle>Blank</DocstringStyle>
    <CompoundFields>false</CompoundFields>
  </Output>
  <Conventions>
    <ClassName case="pascalCase" safePrefix="type"/>
    <FieldName case="snakeCase" safePrefix="value"/>
    <ConstantName case="screamingSnakeCase" safePrefix="value"/>
    <ModuleName case="snakeCase" safePrefix="mod"/>
    <PackageName case="snakeCase" safePrefix="pkg"/>
  </Conventions>
  <Aliases>
    <ClassName source="fooType" target="Foo"/>
    <ClassName source="ABCSomething" target="ABCSomething"/>
    <FieldName source="ChangeofGauge" target="change_of_gauge"/>
    <PackageName source="http://www.w3.org/1999/xhtml" target="xtml"/>
    <ModuleName source="2010.1" target="2020a"/>
  </Aliases>
</Config>
`

This issue is XSDATA always complaining about missing "items" attribute
![image](https://user-images.githubusercontent.com/12298979/117437998-8735b880-af63-11eb-8083-436564d085c0.png)

while put the items attribute manually it should be working
`items: List[str] = field(
        default=list,
        metadata={
            "name": "lines",
            "type": "Element",
        }
    )`

![image](https://user-images.githubusercontent.com/12298979/117438094-aaf8fe80-af63-11eb-8a5a-acc4c46c125a.png)

Thanks!

**Comment by tefra** [comment]
Hi @reidsneo,

I am looking at the "ServiceDelivery" type from the schema there is no element with name "items" defined, what am I missing here, can you please provide a sample xml of what you are trying to produce?

**Comment by reidsneo** [comment]
Hi @tefra 

Sorry I didn't saw that, even though I already take a look on docs example, I finally can understand bit more about the XSDATA, this library is great!
![image](https://user-images.githubusercontent.com/12298979/117526642-2f499100-aff9-11eb-9312-08bcf1ee2d3b.png)
It is working now, but just one question what the best way to process Dictionary type data in the XML instead of native List data
for example linedict is a dictionary type

while the binding only accept List
![image](https://user-images.githubusercontent.com/12298979/117526724-80598500-aff9-11eb-86ae-a516b10ea382.png)

**Comment by reidsneo** [comment]
Hi @tefra 

Sorry for reopening the issue, can you give me any though about the ns mapping?
First here is without any mapping
![image](https://user-images.githubusercontent.com/12298979/117753591-513a5200-b24b-11eb-9ef2-b352f63476e1.png)
After mapping siri url map
![image](https://user-images.githubusercontent.com/12298979/117753690-8050c380-b24b-11eb-999c-3063d2b04278.png)
But the issue is occured on maping netex map
![image](https://user-images.githubusercontent.com/12298979/117753789-a8d8bd80-b24b-11eb-88bb-148c822e55ce.png)
The siri url map is not working anymore

**Comment by tefra** [comment]
I am closing this one, please open a new one if you have further questions @reidsneo
