### ISSUE TITLE
JsonParser null value throws TypeError

### ISSUE THREAD

**Issue by ctzen** [tefra/xsdata#493]
The dataclass:
```python
@dataclass
class Foo:
    a: str
    b: Optional[str] 
```
The JSON:
```json
{
    "a": "a-value",
    "b": null
}
```

```python
JsonParser().from_string(json_text, Foo)
```

Was expecting Foo.b to be set to None but got TypeError exception.
```
TypeError: __init__() missing 1 required positional argument: 'b'
```

**Comment by tefra** [comment]
The parser needs fields with optional values to be explicit with their default value.

```python
@dataclass
class Foo:
    a: str
    b: Optional[str] = None
```

I will accept this one as a bug though, the current behavior is at least annoying. 

PS: This most likely affects the xml parser as well...

**Comment by tefra** [comment]
Hi @ctzen the Json parser just got a major refactor and updates that includes a fix to not ignore required null values.

Thank you for reporting!
