### ISSUE TITLE
Unable to model data without specifying correct xmlns each time

### ISSUE THREAD

**Issue by SionAbes** [tefra/xsdata#496]
I was wondering if I could get some help with regards to a problem I'm having.. I'm trying to call a set of endpoints that respond with the same standard of information, but, The namespace is always different leading to the following error:

> xsdata.exceptions.ParserError: Unknown property Fleet:{http://www.jcmanet.or.jp/english2017/ISO/15143/-3/20190501}Links

I've been trying to mess around with the namespace settings of my models but to no avail.. I can't seem to make it work without directly specifying the namespace each time in the model classes, which I find a less than ideal solution, given 99% of the model is the same.

Below are two examples of two seperate endpoints. As mentioned, the rest of the modelling bar this Fleet xmlns are identical:

```
<Fleet xmlns="http://standards.iso.org/iso/15143/-3" version="0">
```

```
<Fleet xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="20190501" xmlns="http://www.jcmanet.or.jp/english2017/ISO/15143/-3/20190501">
```

Would you have any suggestions? 

Cheers,
Siôn

**Comment by tefra** [comment]
Hi @SionAbes yes the models need to be defined explicitly in order for the binding process to work out of the box for any schema.

I agree the process can become tedious when someone writes those models manually and the models involve multiple namespaces, FYI the cli code generator can work with raw xml documents as well!

What you ask is actually possible, although I don't recommend it 

```python
@dataclass
class TypeB:
    three: str
    four: str

@dataclass
class Root:
    one: int
    two: TypeB
```

Internally the parsers and serializers use the XmlContext class to build all the binding information, if you initialize an instance and build the binding metadata for your class manually with a custom namespace you can get the desired behavior.

```python
import sys

from issue.models import Root, TypeB
from xsdata.formats.dataclass.context import XmlContext
from xsdata.formats.dataclass.parsers import XmlParser
from xsdata.formats.dataclass.serializers import XmlSerializer

context = XmlContext()  # initialize context
context.build(Root, parent_ns="xsdata")  # Build our root class with a custom parent namespace!

obj = Root(one=1, two=TypeB(three="three", four="four"))

serializer = XmlSerializer(context=context)  # Use our context instance
parser = XmlParser(context=context)  # Use our context instance

serializer.config.pretty_print = True
serializer.write(sys.stdout, obj)

xml = """<ns0:Root xmlns:ns0="xsdata">
  <ns0:one>1</ns0:one>
  <ns0:two>
    <ns0:three>three</ns0:three>
    <ns0:four>four</ns0:four>
  </ns0:two>
</ns0:Root>"""

assert obj == parser.from_string(xml, Root)
```

For simple cases though you only need to define the namespace for the root class anyway

```python
@dataclass
class TypeB:
    three: str
    four: str

@dataclass
class Root:

    class Meta:
        namespace = "xsdata"

    one: int
    two: TypeB


context = XmlContext()
obj = Root(one=1, two=TypeB(three="three", four="four"))

serializer = XmlSerializer()
serializer.config.pretty_print = True
serializer.write(sys.stdout, obj)
```

```
<ns0:Root xmlns:ns0="xsdata">
  <ns0:one>1</ns0:one>
  <ns0:two>
    <ns0:three>three</ns0:three>
    <ns0:four>four</ns0:four>
  </ns0:two>
</ns0:Root>
```
