### ISSUE TITLE
Problem in typing with self-referencing classes

### ISSUE THREAD

**Issue by gramm** [tefra/xsdata#503]
Problem:
When converting AUTOSAR_00049_COMPACT.xsd (https://www.autosar.org/fileadmin/user_upload/standards/foundation/20-11/AUTOSAR_TR_XMLSchemaSupplement.zip), some classes have references to self. In Python <= 3.9, this is seemingly not supported by the 'typing' module (https://stackoverflow.com/questions/33533148/how-do-i-type-hint-a-method-with-the-type-of-the-enclosing-class).

Example to reproduce error:
- use xsdata to convert AUTOSAR_00049_COMPACT.xsd

- try to execute the following program
```
from autosar_00048_compact import Autosar

if __name__ == '__main__':
    ar = Autosar()
    print(ar)
```
- The program fails with "NameError: name 'SlOverviewParagraph' is not defined"

**Comment by tefra** [comment]
Hi @gramm thanks for reporting,

Actually the class analyzer is not the picking the correct type for the field `SlParagraph.ft` because there is an attributeGroup and a complexType named `SL-OVERVIEW-PARAGRAPH` seems like there is condition missing there.

**Comment by tefra** [comment]
Hi @gramm, the fix is on master and will be included in the next release, this schema is interested I am going to add it in the samples [repo](https://github.com/tefra/xsdata-samples)  as well

**Comment by gramm** [comment]
Thanks for the quick fix. The AR schema is definitively a solid test XSD.

One side question, what do you think of adding a feature that would generate one file per class instead of one huge file? For development purpose it is much easier to deal with smaller files e.g. jumping into a class, reading its documentation, looking at the type of its fields... For example in PyCharm a 13mb python file will not be indexed in the default configuration, so auto import etc. is not available.

**Comment by tefra** [comment]
It's impossible for python due to circular imports, but I 've been thinking for awhile for a clustered mode that will try to group classes per multiple files just enough to avoid circular imports but it's not an easy task.

**Comment by tefra** [comment]
@gramm check pr #509  -> demo tefra/xsdata-samples#48
