### ISSUE TITLE
Exclude private attributes when serialize to xml

### ISSUE THREAD

**Issue by finswimmer** [tefra/xsdata#504]
Hello,

I'm in need to have some "private" attributes in my dataclass which I want to serialize to xml. But those private attributes should not be included in the serialized xml. Is there a way to achieve this or is this a feature request.

Here's a minimal example how it looks like now:

```python
from dataclasses import dataclass
from typing import Optional

from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig


@dataclass
class User:
    name: str
    age: int

    _privatekey: Optional[str] = None

    @property
    def privatekey(self) -> Optional[str]:
        return self._privatekey

    @privatekey.setter
    def privatekey(self, value: str) -> None:
        self._privatekey = value


user = User(name="john doe", age=42)
user.privatekey = "testdata"

serializer_config = SerializerConfig(pretty_print=True, xml_declaration=False)
serializer = XmlSerializer(config=serializer_config)
xml = serializer.render(user)

print(xml)
```

**Output:**
```
<User>
  <name>john doe</name>
  <age>42</age>
  <_privatekey>testdata</_privatekey>
</User>
```

**Output in Request:**
```
<User>
  <name>john doe</name>
  <age>42</age>
</User>
```

fin swimmer

**Comment by tefra** [comment]
Thanks for reporting @finswimmer it's been on my todo for a while now, will add in time for the next release, it's shouldn't be too hard.

**Comment by finswimmer** [comment]
Cool, thanks for your quick anser @tefra.

I had some time today to have a look into the code and indeed it doesn't look to hard to implement. Maybe I can provide a PR for it tomorrow (I guess writing a test would be the hardest part for me ...)

fin swimmer

**Comment by tefra** [comment]
Don't worry about it @finswimmer, next time. Give it a try #506, you need to mark the field with `type=Ignore` and make sure there is a default value otherwise data binding will fail.

```python
@dataclass
class User:
    name: str
    age: int

    _privatekey: Optional[str] = field(default=None, metadata={"type": "Ignore"})
```

**Comment by finswimmer** [comment]
Great! Seems to work like a charm :+1: 

Thanks a lot.
