### ISSUE TITLE
alternatives to dataclasses: pydantic 

### ISSUE THREAD

**Issue by untereiner** [tefra/xsdata#522]
Did you plan to add alternatives to dataclasses, like pydantic for instance ?
I am interested in it and I can start a draft.

**Comment by tefra** [comment]
I am working on a compatibility layer for dataclasses see #521, in order to avoid hacking/rewriting all the binding modules.

The target of the experiment is attrs for now...

**Comment by tefra** [comment]
Out of curiosity why pydantic what are they features that you are interested in?

**Comment by untereiner** [comment]
I am using fastapi which uses pydantic
Pydantic has builtin json export. No need of cattrs in addition to attrs for example.

**Comment by tefra** [comment]
Oh I see, different use case, I am interested in attrs because it offers some features not available in python dataclasses. It will include both code generation and data binding modules.

You just want a code generation plugin right?

**Comment by untereiner** [comment]
> You just want a code generation plugin right?

I think yes. The inheritance (for pydantic) or the class decorator (for attrs) will give free access to more features (e.g. serialization for pydantic)

**Comment by tefra** [comment]
Please check the following two repos for examples on how to create a plugin

https://github.com/tefra/xsdata-plantuml
https://github.com/tefra/xsdata-attrs  (still in progress)

**Comment by untereiner** [comment]
Thanks I will check the progress of the second one
