### ISSUE TITLE
[RFC] BadgerFish json bindings

### ISSUE THREAD

**Issue by tefra** [tefra/xsdata#528]
> BadgerFish is a convention for translating an XML document into a JSON object. Once you've got your XML document represented as a JSON object, it's easy to manipulate from within Javascript. If you're familiar with PHP's SimpleXML extension, think of BadgerFish as aiming for a similar goal: making it simpler to do common manipulations of XML documents with a predictable structure.

**Comment by untereiner** [comment]
[http://www.sklar.com/badgerfish/](Link to description)
by the wayn they are even more conventions see [https://github.com/sanand0/xmljson](xmljson)

**Comment by untereiner** [comment]
The [xmlschema](https://xmlschema.readthedocs.io/en/latest/converters.html) library uses converters to do so

**Comment by tefra** [comment]
I will be happy to accept and JSON Renderer style contributions...

Closing for now
