### ISSUE TITLE
Deserialising a subtree from lxml to improve performance of huge documents

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#530]
In #476 we have established that the performance of huge XSDs in combination with larger XML are limited by single threaded processing. I wonder if the example below could be executed more elegantly, by directly using the LXML Element without the need for serialisation to string again. Hence could LxmlSaxHandler or LxmlEventHandler be convinced to start with an Element?

```python
import lxml
import sys
from xsdata.formats.dataclass.context import XmlContext
from xsdata.formats.dataclass.parsers import XmlParser
from xsdata.formats.dataclass.parsers.config import ParserConfig
from xsdata.formats.dataclass.parsers.handlers import LxmlEventHandler
from netex import VersionsRelStructure

context = XmlContext()
config = ParserConfig(fail_on_unknown_properties=False)
parser = XmlParser(context=context, config=config, handler=LxmlEventHandler)
tree = lxml.etree.parse('NeTEx_HTM_Rail_2021-06-02_new.xml')
versions = parser.from_bytes(lxml.etree.tostring(t.find('.//{http://www.netex.org.uk/netex}versions')), VersionsRelStructure)
```

What I would like to explore is below, it seems to me that this is already so close to the lxml stuff...
```
versions = parser.from_element(t.find('.//{http://www.netex.org.uk/netex}versions'), VersionsRelStructure)
```

**Comment by tefra** [comment]
So if you know exactly what piece of the xml you actually need, parse it directly :love_you_gesture: 

lxml has an api to turn an element or tree to an [event stream](https://lxml.de/apidoc/lxml.etree.html?highlight=iterwalk#lxml.etree.iterwalk).

```python
from typing import Any
from typing import Union

from lxml import etree

from xsdata.formats.dataclass.parsers.handlers import LxmlEventHandler
from xsdata.models.enums import EventType

EVENTS = (EventType.START, EventType.END, EventType.START_NS)


class LxmlTreeWalkerHandler(LxmlEventHandler):
    __slots__ = ()

    def parse(self, source: Union[etree.Element, etree.ElementTree]) -> Any:
        """Parse directly an lxml element or tree."""
        ctx = etree.iterwalk(source, EVENTS)
        return self.process_context(ctx)
```

```python
import lxml

tree = lxml.etree.parse(sample)
parser = XmlParser(context=context, config=config, handler=LxmlTreeWalkerHandler)
versions = parser.parse(tree.find('.//{http://www.netex.org.uk/netex}versions'), VersionsRelStructure)
print(versions)
```

**Comment by tefra** [comment]
what's bugs me a lot is that the lxml iterwalk seems faster than iterparse

**Comment by tefra** [comment]
check #531 I think it's better to integrate this as a feature in the existing LxmlEventHandler

**Comment by tefra** [comment]
Thanks for the suggestions @skinkie keep them coming 

https://xsdata.readthedocs.io/en/latest/xml.html#parse-from-lxml-element-or-tree
