### ISSUE TITLE
NeTEx scherma with compound fields causes errors

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#532]
```
/mnt/storage/home/skinkie/Sources/xsdata/xsdata/formats/converter.py:82: ConverterWarning: Failed to convert value `all` to one of []
  warnings.warn(
/mnt/storage/home/skinkie/Sources/xsdata/xsdata/formats/converter.py:82: ConverterWarning: Failed to convert value `noneRequired` to one of []
  warnings.warn(
/mnt/storage/home/skinkie/Sources/xsdata/xsdata/formats/converter.py:82: ConverterWarning: Failed to convert value `always` to one of []
  warnings.warn(
/mnt/storage/home/skinkie/Sources/xsdata/xsdata/formats/converter.py:82: ConverterWarning: Failed to convert value `both` to one of []
  warnings.warn(
/mnt/storage/home/skinkie/Sources/xsdata/xsdata/formats/converter.py:82: ConverterWarning: Failed to convert value `anyone` to one of []
  warnings.warn(
/mnt/storage/home/skinkie/Sources/xsdata/xsdata/formats/converter.py:82: ConverterWarning: Failed to convert value `passenger` to one of []
  warnings.warn(
/mnt/storage/home/skinkie/Sources/xsdata/xsdata/formats/converter.py:82: ConverterWarning: Failed to convert value `AND` to one of []
  warnings.warn(
/mnt/storage/home/skinkie/Sources/xsdata/xsdata/formats/converter.py:82: ConverterWarning: Failed to convert value `EQ` to one of []
  warnings.warn(
/mnt/storage/home/skinkie/Sources/xsdata/xsdata/formats/converter.py:82: ConverterWarning: Failed to convert value `route` to one of []
  warnings.warn(
```

**Comment by tefra** [comment]
Thanks for reporting @skinkie, there are multiple issues with compound fields and multi-inheritance models

**Comment by tefra** [comment]
Hey @skinkie, this issue brought up one of my white whales, a scenario that I was pretty sure I would never come across, class/subclass with multiple repeatable choices. It required to rethink the analyzer steps a bit and to refactor some old restrictions handling.

It should work [now](https://github.com/tefra/xsdata-samples/tree/master/netex)

**Comment by skinkie** [comment]
And now you expect end-user to test it ;-) With pleasure. But to be clear, the architecture guys may have modeled everything in impossible ways, I still have to come across a real life example of its usage ;-)

**Comment by tefra** [comment]
I am using the example from the [NeTEx](https://github.com/NeTEx-CEN/NeTEx/tree/00f976f0c7732f865cd6129624174e9285add1ca/examples/functions) to test rountrip conversions and validate against the schema, I did some manual sampling and qa but yeah as always your feedback is the most important.
