### ISSUE TITLE
Implementing "hashCode" for elements

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#536]
Sometimes it is handy to be able to compare objects to sort them or to know if they are unique. Within java it is possible to add some decorators, is it possible to create a generic solution which would make any object hashable types?

**Comment by tefra** [comment]
I am working on frozen dataclasses but the goal is in then to be able to toggle any of the [dataclasses](https://docs.python.org/3/library/dataclasses.html) features

```
@dataclass(init=True, repr=True, eq=True, order=False, unsafe_hash=False, frozen=False)
```

**Comment by skinkie** [comment]
I hope unfreezing is possible :-)

**Comment by tefra** [comment]
Hey @skinkie  give it a [try](https://xsdata.readthedocs.io/en/latest/examples/dataclasses-features.html#dataclasses-features)
