### ISSUE TITLE
Add instance factory function

### ISSUE THREAD

**Issue by hcw70** [tefra/xsdata#548]
I am using XSData to read dataclass instances which need additional checks.

The additional checks should be implemented on user supplied classes which derive from the XSData generated class:

XSData (raw) class:

```
@dataclass
class TModule(TTypeDefinition):
    import_: List[TImport] = field(
        default_factory=list,
        metadata={
            "name": "import",
            "type": "Element",
            "namespace": "http://xxx",
        }
    )
```

My class with additional checks:
```
class TModule(raw.TModule):
    def check(self):
         if condition ...

```

However, the problem is that my TModule is not instanciated during parsing.
Currently, i use a "type hacking approach"
```
@functions_to_super
class TModule(raw.TModule):
    def check(self):
         if condition ...
```
where i copy the defined functions to the base class.
This however is not ideal, since i want to present only my TModule to the user, not the raw classes.

Is there the option (or could this be added) to give a factory function to the parser
```
def createInstance(clazz);
     if clazz.__name__ = "TModule":
        return myTModule()
```
by which i can define for which dataclass which user supplied class is instanciated, so
that the parsed objects dont contain any "raw" classes?

Kind regards

Hauke

**Comment by tefra** [comment]
If it's just some form of checks why not modify the models to add `__post__init__` methods?

Ah you want to change completely the actual return type, why would you want to do that?

If you want to not include certain properties, you can remove them from the generated models and silence the parsers to not fail on unknown properties.

I am trying to figure out the actual need because this kind of customization seems very specific to models and I would rather avoid adding additional logic to the binding modules. Would it be ok if the parsers checked for a custom constructor inside the models and used that instead?

**Comment by hcw70** [comment]
> If it's just some form of checks why not modify the models to add `__post__init__` methods?

How can i modify the __post_init__ methods when the parser only creates the "raw"-classes? 
We dont want to modify the generated code.

> 
> Ah you want to change completely the actual return type, why would you want to do that?
I dont want to return something completely different, but normally a derived class of the given class.

I also dont want to have only a check after creation of the class, but also have
some derived properties like "bitsize()" or "referenced_type()"

> 
> If you want to not include certain properties, you can remove them from the generated models and silence the parsers to not fail on unknown properties.
> 
> I am trying to figure out the actual need because this kind of customization seems very specific to models and I would rather avoid adding additional logic to the binding modules. Would it be ok if the parsers checked for a custom constructor inside the models and used that instead?

The problem is how do i include a custom constructor in the generated classes?
How do i add custom functions ("bitsize()") in the generated classes?

Regards

Hauke

**Comment by hcw70** [comment]
Another approach could be to have a class factory instead of an instance factory:

```
def classToUse(clazz);
     if clazz.__name__ = "TModule":
        return myTModule

```
which would preventing with init arguments.

Your default implemenetation could then be

```
def classToUse(clazz);
        return clazz

```
and be replacable by the user (maybe by setting an attribute in the ParserConfig / Conext).

```
def myClassReplacer(clazz):
    ....

def parse():
    from xsdata.formats.dataclass.parsers import XmlParser
    from xsdata.formats.dataclass.parsers.config import ParserConfig
    from xsdata.formats.dataclass.context import XmlContext

    context = XmlContext()
    config = ParserConfig(process_xinclude=False, class_factory=myClassReplacer)
    parser = XmlParser(config=config, context=context)
    doc = parser.from_string(xml_text, TMessageDB)


```

**Comment by tefra** [comment]
Thank you for the suggestion @hcw70

**Comment by hcw70** [comment]
@tefra  Thank you for your quick implementation!

**Comment by tefra** [comment]
I really liked the config option because in the future we could hookup validations from there as well!

**Comment by hcw70** [comment]
@tefra BTW, are the validations XSData parsing is doing the same / equivalent to an XSD validation step?

**Comment by tefra** [comment]
No currently there are no validations, even though the generator adds restrictions as fields metadata, they are just hints for the developer. At some point I wish to work on something like this but it's not really high on my priorities. 

The binding process can only fail on unknown properties and errors during type conversions, both of them are configurable.
