### ISSUE TITLE
structure-style namespaces path generation

### ISSUE THREAD

**Issue by untereiner** [tefra/xsdata#554]
Could it be possible to add an option to generate the file not with the namespace as filename but as path ?
For example the namespace: `http://www.energistics.org/energyml/data/commonv2`
For now the cli generate the file: `energistics_org_energyml_data_commonv2.py` in a target package
Could it be possible to generate the path `energistics/energyml/data/commonv2.py` in a target package ?

Edit: even better use the version tag
My schema's header is as follows:
```xml 
<xs:schema targetNamespace="http://www.energistics.org/energyml/data/resqmlv2" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:resqml="http://www.energistics.org/energyml/data/resqmlv2" xmlns:eml="http://www.energistics.org/energyml/data/commonv2" elementFormDefault="qualified" version="2.2">
```
I would like to generate a path with the version (e.g. "2.2"): `energistics/energyml/data/v2.2/commonv2.py`

**Comment by tefra** [comment]
@untereiner you could play around with the module aliases, check the [travelport](https://github.com/tefra/xsdata-samples/tree/master/travelport) sample
```
  <Aliases>
    <ModuleName source="http://www.energistics.org/energyml/data/resqmlv2" target="energistics.energyml.data.commonv2"/>
```

**Comment by untereiner** [comment]
ok, besides I can add manually the version string because there is no way to get it from the xsd schema, right ?

**Comment by tefra** [comment]
> ok thanks, besides I can add manually the version string because there is no way to get it from the xsd schema, right ?

yes, you can do whatever you want with the aliases, currently there is no other way
