### ISSUE TITLE
Extended type optional attributes

### ISSUE THREAD

**Issue by neriusmika** [tefra/xsdata#567]
Suppose we have extended string type:
```xml
   <xsd:complexType name="IdentifierType">
      <xsd:simpleContent>
         <xsd:extension base="xsd:normalizedString">
            <xsd:attribute name="schemeID" type="xsd:normalizedString" use="optional">
            </xsd:attribute>
         </xsd:extension>
      </xsd:simpleContent>
   </xsd:complexType>
```
Generated python class is:
```python
class IdentifierType:
    value: Optional[str] = field(default=None)
    scheme_id: Optional[str] = field(
        default=None,
        metadata={
            "name": "schemeID",
            "type": "Attribute",
        },
    )
```
Is there any reason why `value` attribute is optional?
If we use that `IdentifierType` in other types, then of course those attributes can be optional, but I don't understand why `value` itself is optional.
For example, if we have class:
```python
class MyClass:
    id: IdentifierType
    ...
```
It doesn't make sense to have myclass.id.value optional if id itself is required. Maybe I am missing something.

**Comment by tefra** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="IdentifierType">
      <xsd:simpleContent>
         <xsd:extension base="xsd:normalizedString">
            <xsd:attribute name="schemeID" type="xsd:normalizedString" use="optional">
            </xsd:attribute>
         </xsd:extension>
      </xsd:simpleContent>
   </xsd:complexType>
<xsd:element name="IdentifierType" type="IdentifierType" />
</xsd:schema>
```

validates against

```xml
<IdentifierType />
```

```xml
<IdentifierType>foo</IdentifierType>
```

```xml
<IdentifierType schemeID="foo">foo</IdentifierType>
```

```xml
<IdentifierType schemeID="foo" />
```

So both value (simple content) and the attribute are optional

**Comment by neriusmika** [comment]
I think in the last case it must return empty string instead of None.

**Comment by neriusmika** [comment]
The problem is not a validation. It's on the python side. Those values should not be None, when serializing/deserializing. Basically, it's just a string type. And if it doesn't have minoccurs=0 or nillable="true", how it can be None?

**Comment by tefra** [comment]
Early on I made the decision to treat nil or empty string values as None, I am not sure if it was the right decision or not but It made sense not to have to set the default value for these fields as empty strings or to force the users to initialize instances with empty strings.

I also made my mind when I noticed that both lxml and native python return `None` for both cases

```xml
<author></author>
<author />
```

Is there a use case that's giving you troubles with this @neriusmika ?

**Comment by neriusmika** [comment]
I think it's not correct. lxml and others made such decision, because they know nothing about schemas and types. For me, the biggest problem is with type checking when I constantly need to check for None even if the actual field is required. With large schemas, the code becomes quite messy.

**Comment by tefra** [comment]
Thanks for bringing it up again @neriusmika, it was a convenient choice in the beginning but I agree it wasn't the proper handling. This also forced some improvements on nillable content handling as well!

The update is on master and will be included in the next release

**Comment by neriusmika** [comment]
Thanks for the great support!

**Comment by neriusmika** [comment]
Just checked the new version and now required fields match with xsd perfectly. Beautiful work.
