### ISSUE TITLE
Default value set incorrectly for nested complexTypes with simpleContent

### ISSUE THREAD

**Issue by FirefoxMetzger** [tefra/xsdata#579]
I am having issues when generating bindings for elements that specify a default value for a complexType that uses simpleContent. The resulting bindings are not generated consistently.

If the element is at the root level the bindings produce what I would expect:

<details>
<summary>XSD + bindings</summary>

```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.1">
  <xs:element name="pose" default="0 0 0 0 0 0">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string"/>
      </xs:simpleContent>
      <xs:attribute name="relative_to" type="xs:string" use="optional">
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

```python
@dataclass
class Pose:
    class Meta:
        name = "pose"

    value: str = field(
        default="0 0 0 0 0 0",
        metadata={
            "required": True,
        }
    )
    relative_to: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        }
    )
```

</details>

However, when I nest the element in another complex type then `Pose` is generated slightly differently and no longer assigning the default to `Pose.value`, but to `Frame.Pose` instead.

<details>
<summary>XSD + bindings</summary>

```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.1">
  <xs:element name="frame" minOccurs="0" maxOccurs="unbounded">
    <xs:complexType>
      <xs:all>
        <xs:element name="pose" default="0 0 0 0 0 0">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string"/>
            </xs:simpleContent>
            <xs:attribute name="relative_to" type="xs:string" use="optional">
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:all>
      <xs:attribute name="name" type="xs:string" use="required">
      </xs:attribute>
      <xs:attribute name="attached_to" type="xs:string" use="optional">
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

```python
@dataclass
class Frame:
    class Meta:
        name = "frame"

    pose: "Frame.Pose" = field(
        default="0 0 0 0 0 0",
        metadata={
            "type": "Element",
            "namespace": "",
            "required": True,
        }
    )
    name: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        }
    )
    attached_to: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        }
    )

    @dataclass
    class Pose:
        value: str = field(
            default="",
            metadata={
                "required": True,
            }
        )
        relative_to: Optional[str] = field(
            default=None,
            metadata={
                "type": "Attribute",
            }
        )
```

</details>

This is a little unexpected. Assuming I understand XSD correctly, then an element's `@default` should set it's child content if omitted, which in the nested example above should be `Frame.Pose.Value` and not `Frame.Pose`, correct?

A similar thing happens if I refer to the element instead of nesting it. In this case I would expect the referring element's default to overwrite the default of the referred to element. However, two independent defaults are generated instead. What's going on?

<details>
<summary>XSD + bindings</summary>

```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.1">
  <xs:element name="pose" default="0 0 0 0 0 0">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string"/>
      </xs:simpleContent>
      <xs:attribute name="relative_to" type="xs:string" use="optional">
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="frame" minOccurs="0" maxOccurs="unbounded">
    <xs:complexType>
      <xs:all>
        <xs:element name="pose" default="0 0 0 0 0 0" ref="pose">
        </xs:element>
      </xs:all>
      <xs:attribute name="name" type="xs:string" use="required">
      </xs:attribute>
      <xs:attribute name="attached_to" type="xs:string" use="optional">
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>
```

```python
@dataclass
class Pose:
    class Meta:
        name = "pose"

    value: str = field(
        default="0 0 0 0 0 0",
        metadata={
            "required": True,
        }
    )
    relative_to: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        }
    )


@dataclass
class Frame:
    class Meta:
        name = "frame"

    pose: Pose = field(
        default="0 0 0 0 0 0",
        metadata={
            "type": "Element",
            "required": True,
        }
    )
    name: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        }
    )
    attached_to: Optional[str] = field(
        default=None,
        metadata={
            "type": "Attribute",
        }
    )
```

</details>

**Comment by FirefoxMetzger** [comment]
I also just realized that parsing becomes a little strange in this case. This behaves as expected:

Case 1:
```xml
<frame name="F0">
  <pose>0 2 0 0 0 0</pose>
</frame>
```
```python
Frame(pose=World.Frame.Pose(value='0 2 0 0 0 0', relative_to=None), name='F0', attached_to=None)
```

However, other cases behave differently:

Case 2:

```xml
<frame name="F2">
  <pose relative_to="double_pendulum::upper_link"/>
</frame>
```
```python
Frame(pose=World.Frame.Pose(value='', relative_to='double_pendulum::upper_link'), name='F2', attached_to=None)
```

Case 3:

```xml
<frame name="F1_attach" attached_to="double_pendulum"/>
```
```python
Frame(pose='0 0 0 0 0 0', name='F1_attach', attached_to='double_pendulum')
```

All of the above is consistent with the generated bindings, but quite unexpected and I think not what is intended by the spec.

**Comment by tefra** [comment]
hi @FirefoxMetzger, that's an interesting pattern, I wish you could share the full suite, I have never seen that before. Default values on elements with complex type :facepalm: 

Initially I thought it can't be correct but you are right, although your examples are not 100% valid, the default part on complex content is acceptable.

**Comment by FirefoxMetzger** [comment]
>  I wish you could share the full suite, I have never seen that before.

Absolutely. The [full XSD suite lives here](https://github.com/FirefoxMetzger/ropy/tree/main/skbot/ignition/sdformat/schema/1.8) and the parent folder has similar, schemata. The particular file containing the /frame/pose combo [is this one](https://github.com/FirefoxMetzger/ropy/blob/895f07b1438075419e71bac603d38c436a517a99/skbot/ignition/sdformat/schema/1.8/world.xsd#L262-L298) though the same pattern exists in other places.

> Default values on elements with complex type 🤦

I know, right?

> your examples are not 100% valid

Oh? Where did I err?

**Comment by tefra** [comment]
According to xmlschema min/max occurs on global element, complexType with both simpleContent and attribute, element ref with default value and name

**Comment by FirefoxMetzger** [comment]
You are right. I miscounted the brackets on the complex type and thought it can have attributes and simpleContent. I was wondering why attributes are allowed in both extensions and complex types at the same time ... this explains it. I will fix this in the schema and see how it affects the bindings :)

**Comment by FirefoxMetzger** [comment]
Nope, It doesn't affect in the generated bindings.

**Comment by tefra** [comment]
> Nope, It doesn't affect in the generated bindings.

Yeah that's the naive part of the xsdata, it simply walks the tree and collects what it thinks are classes, fields, extensions and restrictions. So it can even create models from invalid schemas :)

I 've pushed to master a fix for this one give it a try, it should cascade the default value to the inner class now.

**Comment by FirefoxMetzger** [comment]
Yep, master cascades the default value down to the nested classes on my bindings. 🚀 

The outer classes are now `Optional` and have `default=None` and `metadata["required"]=True`, which is a bit unexpected since the element is required. I need to investigate a bit more though first, and if it turns out to be an actual issue, I'll open a new one here :) Thanks for providing such an awesome library!
