### ISSUE TITLE
"Working with custom types" doc improvement

### ISSUE THREAD

**Issue by LECbg** [tefra/xsdata#584]
I don't know if the behavior of this `Converter` could be considered an error:
https://github.com/tefra/xsdata/blob/81a8cb9d0333d6501c33e758c509f712db262896/docs/data-types.rst#L48-L55

Deserializing some XML into an `Example` instance and serializing it back wouldn't make use of `TheGoodFloatConverter.serialize`, as the `deserialize` method returns a Python built-in `float` (there's a little bug in that `-> str` in fact).

I just created a custom type and a `Converter` and was wrongly expecting its `serialize` method to get called, as my `deserialize` method doesn't return an instance of my custom type, but a Python built-in type, so the serializer calls the converter of that type. I probably just misunderstood the doc, but that is precisely why I think this example can be improved.

If you agree, @tefra, I can submit a pull request.

**Comment by tefra** [comment]
Yes the deserialize return type is wrong there 🤦‍♂️ 

Thanks @LECbg go ahead!

**Comment by tefra** [comment]
Hey @LECbg I took care of it in the recent docs update, next time, documentation is an area I definitely need all the help I can get, so if you see something wrong dont ask for permission go ahead and submit a pr :+1:
