### ISSUE TITLE
register custom converter for dataclasses

### ISSUE THREAD

**Issue by cedwic** [tefra/xsdata#586]
After reading the documentation here:
https://xsdata.readthedocs.io/en/latest/data-types.html#working-with-custom-types

I've tried to modify the TheGoodFloat class to be a dataclass.

```python
@dataclass
class TheGoodFloat:
    akey :float
    
```
Registering a converter for this version of TheGoodFloat will not trigger any errors, but  the serialize and deserialize method are not being called.

Is there another way I've overlooked to register a non-default converter for a specific dataclass ? 

Or would it be possible to change the code in a way that the converter.registry is checked before the default behaviour for dataclasses apply ?

**Comment by tefra** [comment]
hi @cedwic, dataclasses are the binding models, they are the building blocks that represent the xml tree and nodes, so they area reserved for that purpose, I am afraid

I suggest [namedtuples ](https://docs.python.org/3/library/typing.html?highlight=namedtuple#typing.NamedTuple )or [UserString](https://docs.python.org/3/library/collections.html?highlight=userstring#collections.UserString) for custom atomic/primitive value types if you don't want to deal with the boilerplate of a custom object.

That's what I am using for the [xml datatypes](https://xsdata.readthedocs.io/en/latest/api/xml-datatypes.html) that can't be mapped directly to python

**Comment by cedric-roussel** [comment]
Hi,
I've just looked at this again, and figured out all I needed was already there :)
This is what I ended up doing.

- Use  [custom class_factory](https://xsdata.readthedocs.io/en/latest/examples/custom-class-factory.html)  for parsing

``` python
    if clazz is Comment:
        return NiceComment(text=[i.value for i in params["text"]])
```

- Extend [XmlSerializer](https://xsdata.readthedocs.io/en/latest/_modules/xsdata/formats/dataclass/serializers/xml.html#XmlSerializer.write_dataclass) for writing

```python
if isinstance(obj, NiceComment):
    obj = Comment(text=[Text(index=i + 1, value=v) for i, v in enumerate(obj.text)])
    return super().write_dataclass(obj)
```

This seems to work flawlessly both ways, hiding that generated model which is correct but ugly to work with:
```xml
<root><comment><text index="1">line 1</text><text index="2">line 2</text></comment></root>
```

```python
Root(comment=NiceComment(text=['line 1', 'line 2']))
```

Thank you very much for your support and great library

**Comment by tefra** [comment]
cool I am closing this one for now, but I will revisit the idea about the adaptable types in the future.
