### ISSUE TITLE
depreciation of sax handlers is non-backwards compatible

### ISSUE THREAD

**Issue by FirefoxMetzger** [tefra/xsdata#589]
The SAX handlers were depreciated in v21.9 (which is completely fine); however, I would have expected this to cause a major version bump in xsdata, since it is non-backward compatible and breaks downstream code.

Since the SAX handlers no longer exist, the corresponding classes (e.g. `handlers.LxmlSaxHandler`) stopped existing as well, which breaks downstream code mention/using them. For example, in my case, I was exposing a string kwarg which I then changed to the corresponding handler like so

```python
handler_class = {
        None: handlers.default_handler(),
        "XmlEventHandler": handlers.XmlEventHandler,
        "XmlSaxHandler": handlers.XmlSaxHandler,
        "LxmlEventHandler": handlers.LxmlEventHandler,
        "LxmlSaxHandler": handlers.LxmlSaxHandler,
    }[handler]
```

(In my case depreciating the SAX handlers broke the entire function, even when using EventHandlers.)

Again, not a terrible thing, since good downstream test coverage easily picks up on this, but potentially it is worth putting a note somewhere or bumping the version major.

Otherwise, again, solid work on this release, and I really love the library 💯.

**Comment by tefra** [comment]
@FirefoxMetzger, I started this RFC #582 but the lack of any comments made me think that no-one was actually using them.

Still I suggest pinning xsdata version in your requirements, especially if you use the code generator that tends to change pretty much in every release.
