### ISSUE TITLE
Issue parsing wildcard element

### ISSUE THREAD

**Issue by jstys** [tefra/xsdata#594]
Been going through the docs and still unsure of if what I'm looking for is supported.  My schema has a generic "container" with a wildcard element with no specified choices.  This is getting parsed as `AnyElement`, any way to convert this over to a known type?  

```
	<complexType name="tPayload" mixed="true">
		<sequence>
			<any processContents="strict" minOccurs="1" maxOccurs="1"
				namespace="##any" />
		</sequence>
	</complexType>
	<element name="Payload" type="common:tPayload">
	</element>
```

**Comment by tefra** [comment]
Yeah the xsi:type is the trigger to go look for a matching model, I can't remember what limitation there was for not using the element qname as well as last ditch effort as well, I ''ll check again...

Note to self: Wildcards needs a lot of examples in the docs

**Comment by tefra** [comment]
The xsi:type is necessary for these cases, there is no way to try all declared classes and see which one fits
