### ISSUE TITLE
Add "operations" option to structure-style for wsdl code generation

### ISSUE THREAD

**Issue by brunnels** [tefra/xsdata#599]
I'm requesting an enhancement to add an option similar to `-ss clusters` but it would group by the wsdl operation into a single file named with the operation name.

[activate_device.wsdl](https://github.com/tefra/xsdata/files/7455014/activate_device_wsdl.txt)
The attached wsdl generates the following files with `-ss clusters`:
```
activate_device_input_parms
result
nas_fault
request_header
result_set
row
activate_device_request
network_management_api_activate_device_input
activate_device_response
network_management_api_activate_device_output
network_management_api_activate_device
```
Ideally, with `-ss operations` it would result in the contents of the following files being added into one file named `activate_device.py`
```
activate_device_input_parms
activate_device_request
network_management_api_activate_device_input
activate_device_response
network_management_api_activate_device_output
network_management_api_activate_device
```

**Comment by brunnels** [comment]
The wsdl I attached in the issue was just an excerpt from the full wsdl provided for MFNA (was HPNA).  This is a very common enterprise network management tool.  Here are all the wsdl files that they provide in the latest version.  I'm not sure why there need to be different client versions but I've been using the gsoap one.

[api.wsdl.dotnet.txt](https://github.com/tefra/xsdata/files/7460151/api.wsdl.dotnet.txt)
[api.wsdl.gsoap.txt](https://github.com/tefra/xsdata/files/7460152/api.wsdl.gsoap.txt)
[api.wsdl.soappy.txt](https://github.com/tefra/xsdata/files/7460153/api.wsdl.soappy.txt)
[api.wsdl.wsdl2py.txt](https://github.com/tefra/xsdata/files/7460154/api.wsdl.wsdl2py.txt)
[api.wsdl.axis.txt](https://github.com/tefra/xsdata/files/7460155/api.wsdl.axis.txt)
[api.wsdl.axis2.txt](https://github.com/tefra/xsdata/files/7460156/api.wsdl.axis2.txt)

**Comment by brunnels** [comment]
I also edited the xsdata-attrs plugin to not do the attrs changes but to remove the `network_management_api` from the filenames and `NetworkManagementApi` from the class names.  I don't know xsdata well enough yet to know if this is easier accomplished through some other means but it would be nice if it were.  I would open a separate issue but not sure how to explain it without the context of this issue.

**Comment by brunnels** [comment]
As huge as this wsdl is it would be nice to group the operations into folders if putting the contents of all the files into a single file is too cumbersome.  I guess I could create a post generation script that moves the files into folders based on a regex and then updates the __init__.py files

**Comment by tefra** [comment]
I ''l take a look @brunnels, your wsdl definitely seems interesting please point me to the official wsdl with maybe some RQ/RS samples please.

**Comment by brunnels** [comment]
Unfortunately they don't have a lot of documentation on the SOAP API specifically because it's essentially their CLI API wrapped in SOAP.  What I attached were the official wsdl's for 2020.08.

Here's a brief bit I did find. https://docs.microfocus.com/itom/Network_Automation:2018.11/JavaAPI#Install_WSDL%C2%A0files_(SOAP%C2%A0API)

The wsdl works fine in soapui.  I have also used it in the past with code generation though java and dotnet.

I found a few other issues with the dataclass from wsdl generation with this wsdl.  I have been able to fix the dataclasses and get them working.  It would probably be good for me to create a test repo, checkin the generated code, and then apply the fixes I needed to make to get things working on a branch so they can be easily compared.

I'll do this and then add the link to issue #606

**Comment by brunnels** [comment]
I quickly kludged together a post-processor that groups operations like I want them using this [script](https://github.com/brunnels/xsdata-mfna/blob/main/group_operations.py) which gives [this result](https://github.com/brunnels/xsdata-mfna/tree/main/mfna-grouped) 

I started from code generated with command `xsdata -mll 120 --relative-imports -ss clusters -p mfna mfna-partial.wsdl`

I'm also stripping out the portType name as described [here](https://github.com/tefra/xsdata/issues/613)

Hopefully this gives a better idea of what I'm requesting.

I don't know if it would be easier to do what the script does during xsdata generation time or if you want to add/support that type of functionality or not.

**Comment by tefra** [comment]
@brunnels please take a look here
https://github.com/tefra/xsdata/blob/1cd681598d2235626d0e21716fc9fb885d26e351/xsdata/codegen/handlers/class_designate.py#L26

It's the handler that designates the classes to packages/modules, give it a try

**Comment by tefra** [comment]
I will be happy to accept any contributions on this one...
