### ISSUE TITLE
wsdl operation "import" causes issues with import statements 

### ISSUE THREAD

**Issue by brunnels** [tefra/xsdata#604]
`__init__.py`
```python
from .import import Import
__all__ = [
    "Import"
]
```

`import.py`
```python
from .import_input import ImportInput
from .import_output import ImportOutput

__NAMESPACE__ = "http://microfocus.com/nas/2020/08"


class Import:
    style = "rpc"
    location = "https://localhost/soap"
    transport = "http://schemas.xmlsoap.org/soap/http"
    input = ImportInput
    output = ImportOutput
```

**Comment by tefra** [comment]
help me out here how did you get that result, can you share your config/command?

**Comment by brunnels** [comment]
`xsdata -mll 120 --relative-imports -ss clusters -p mfna api.wsdl.gsoap` using this [wsdl](https://github.com/tefra/xsdata/files/7460152/api.wsdl.gsoap.txt).  

It slipped my mind that this probably came up because I customized the generator to remove `network_management_api` from filenames and remove `NetworkManagementApi` from class names.  

Most likely my modifications are happening after the keyword check happened so this is an invalid issue and I'll have to figure out a better way to remove the api name.

Sorry for the confusion.
