### ISSUE TITLE
operation name not being used in soap body when generating from wsdl

### ISSUE THREAD

**Issue by brunnels** [tefra/xsdata#606]
I'm seeing that the wsdl operation is coming from the input body name.  In this case it's `loginRequest` and that's what I'm seeing in the soap message `<ns1:loginRequest xmlns:ns1="http://microfocus.com/nas/2020/08">`

If I change the metadata name to `login` then the soap message changes and it works `<ns1:login xmlns:ns1="http://microfocus.com/nas/2020/08">`

```python
    @dataclass
    class Body:
        login_request: Optional[LoginRequest] = field(
            default=None,
            metadata={
                "name": "loginRequest",
                "type": "Element",
                "namespace": "http://microfocus.com/nas/2020/08",
            }
        )
```
The wsdl operation name is `login` and the service I'm calling will only accept `login`.
```xml
        <wsdl:operation name="login">
            <wsdl:documentation></wsdl:documentation>
            <wsdl:input message="nas:loginRequest" />
            <wsdl:output message="nas:loginResponse" />
            <wsdl:fault name="error" message="nas:nasFaultMessage" />
        </wsdl:operation>
```
full wsdl is attached to https://github.com/tefra/xsdata/issues/599#issuecomment-957345332

**Comment by tefra** [comment]
@brunnels  can you provide a link to the official wsdl and maybe some docs with samples?

**Comment by brunnels** [comment]
I create a test repo to demonstrate the issues I'm seeing and to show how I fixed them.  See PR https://github.com/brunnels/xsdata-mfna/pull/1/files

**Comment by brunnels** [comment]
After looking at the wsdl more and comparing to the logout operation I guess the wsdl doesn't match up with what the API is expecting in this scenario.  I'll open an issue with MF on this and also try the signin and signout operations to see if perhaps login/logout are legacy.

**Comment by brunnels** [comment]
The logout operation also also wants the operation name for the input name.  The output for both wants the message name.

**Comment by tefra** [comment]
In my samples all the input message names match the operation names :facepalm: 

Thanks @brunnels you are the first one I think that opened an issue about the wsdl generator, keep them coming

**Comment by brunnels** [comment]
@tefra Thank you!  I'll regenerate my test repo tomorrow using `master` and let you know.  

I need to open a different issue on the empty response result metadata namespace.  Right now it's generating with an empty string.

**Comment by rvalyi** [comment]
> Thanks @brunnels you are the first one I think that opened an issue about the wsdl generator, keep them coming

Hehe we are testing them too, but so far so good for us.

**Comment by brunnels** [comment]
I can confirm master resolves this issue in my test repo https://github.com/brunnels/xsdata-mfna
