### ISSUE TITLE
wsdl generation not using message part name

### ISSUE THREAD

**Issue by brunnels** [tefra/xsdata#611]
The operation looks like this
```xml
    <wsdl:types>
        <schema targetNamespace="http://microfocus.com/nas/2020/08"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://www.w3.org/2001/XMLSchema"
                elementFormDefault="qualified">
            <element name="nasFault" type="nas:nasFault"/>
            <complexType name="nasFault">
                <sequence>
                    <element name="message" type="xsd:string"/>
                    <element name="stack" type="xsd:string"/>
                </sequence>
            </complexType>
        </schema>
    </wsdl:types>
    <wsdl:message name="nasFaultMessage">
        <part name="error" element="nas:nasFault"/>
    </wsdl:message>
    <wsdl:portType name="NetworkManagementApi">
        <wsdl:operation name="login">
            <wsdl:documentation></wsdl:documentation>
            <wsdl:input message="nas:loginRequest"/>
            <wsdl:output message="nas:loginResponse"/>
            <wsdl:fault name="error" message="nas:nasFaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
```

`NetworkManagementApiLoginOutput.Body.Fault.Detail` nas_fault  field should have name `error` but has `nasFault` instead.

Please see [PR](https://github.com/brunnels/xsdata-mfna/pull/2/files) for more detail

**Comment by tefra** [comment]
Hrm and you only see this in that element not in the request header for example? 

I am trying to troubleshoot this one....

**Comment by brunnels** [comment]
I think the request header is only used in the request and it appears to work I never tested it.  I always set remove unused elements to true, but that could be the default.  I'll check the MFNA cli docs that has all the same operations to see.  I'll test Monday to see if setting it to false changes anything in the responses that return a Row.

**Comment by tefra** [comment]
Any luck @brunnels?

**Comment by brunnels** [comment]
Sorry, I'm on holiday this week.  I will be able to test Monday.

**Comment by brunnels** [comment]
Sorry for the delay.  I got super busy with work and then vacation hit.

I just tested and setting removedUnusedElements=false in the header doesn't change.

I'm going to try using the new substitution generator config to see if that will get around the problem.

**Comment by brunnels** [comment]
@tefra Looks like there's a check that calls `self.field_name` that would get the substitution from
 `<Substitution type="field" search="nasFault" replace="error"/>` but it's not actually used so the substitution won't work.  https://github.com/tefra/xsdata/blob/master/xsdata/formats/dataclass/filters.py#L286

Is that intended behavior or can you also allow substitutions there?

**Comment by tefra** [comment]
Please open a new issue 

> @tefra Looks like there's a check that calls `self.field_name` that would get the substitution from `<Substitution type="field" search="nasFault" replace="error"/>` but it's not actually used so the substitution won't work. https://github.com/tefra/xsdata/blob/master/xsdata/formats/dataclass/filters.py#L286
> 
> Is that intended behavior or can you also allow substitutions there?

Please open a new issue, that's pretty irrelevant to this one.  What about the original issue do you still think it's a bug?

**Comment by brunnels** [comment]
@tefra I don't know what is "right".  Should the name be the output fault name `<wsdl:fault name="error" message="nas:nasFaultMessage"/>` or the name of the complexType `<complexType name="nasFault">`?  MFNA is responding with `error`, not `nasFault`.  

Here's what is generated in the login_output.py:

```python
                nas_fault: Optional[NasFault] = field(
                    default=None,
                    metadata={
                        "name": "nasFault", # I think this should be error and error is what I receive from MFNA
                        "type": "Element",
                        "namespace": "http://microfocus.com/nas/2020/08",
                    }
```

**Comment by tefra** [comment]
I tried soapUI and wsimport to generate java stubs, both generate it with name `NasFault` I am not sure how to proceed with this one @brunnels have you tried to ask the authors of the schema?


![Screenshot from 2022-03-09 22-28-01](https://user-images.githubusercontent.com/2098915/157530291-207dfe94-7ec9-4bf0-8449-ef7c721e6163.png)

**Comment by brunnels** [comment]
They're not going to fix if it is broken I'm sure.  I'll just fix it in a post generation processor.  Thank you for looking at this.
