### ISSUE TITLE
wsdl generation output dataclass missing namespace

### ISSUE THREAD

**Issue by brunnels** [tefra/xsdata#612]
Here's the wsdl parts for loginResponse

```xml
    <wsdl:message name="loginResponse">
        <part name="Result" type="nas:Result"/>
    </wsdl:message>
    <wsdl:portType name="NetworkManagementApi">
        <wsdl:operation name="login">
            <wsdl:documentation></wsdl:documentation>
            <wsdl:input message="nas:loginRequest"/>
            <wsdl:output message="nas:loginResponse"/>
            <wsdl:fault name="error" message="nas:nasFaultMessage"/>
        </wsdl:operation>
    </wsdl:binding>
```

Results in 
```python
@dataclass
class LoginResponse:
    class Meta:
        name = "loginResponse"

    result: Optional[Result] = field(
        default=None,
        metadata={
            "name": "Result",
            "type": "Element",
            "namespace": "",
        }
    )
```

but should have `"namespace": "http://microfocus.com/nas/2020/08"` in order for parser to be able to parse response [envelope](https://github.com/brunnels/xsdata-mfna/blob/main/test_login.py#L31).

**Comment by tefra** [comment]
Thank you @brunnels, I still don't have many rpc style wsdl samples

This is a very ambiguous case, I still believe the definition should be using the element attribute instead of the type, both are correct of course but I thought the type was only reserved for native xsd types and complex (unqualified) types.

```xml
<part name="Result" element="nas:Result"/>
```

The fix is on master

**Comment by tefra** [comment]
Are you sure about this one @brunnels? I trust soap ui and this is the sample response, it generates 

```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns="http://microfocus.com/nas/2020/08">
 <soapenv:Header/>
 <soapenv:Body>
    <ns:loginResponse>
       <Result>
          <ns:Status>gero et</ns:Status>
       </Result>
    </ns:loginResponse>
 </soapenv:Body>
</soapenv:Envelope>
```

Which is spot on what xsdata generates

```python
from issue.models import LoginResponse
from issue.models import Result
from issue.models import NetworkManagementApiLoginOutput
from xsdata.formats.dataclass.serializers import XmlSerializer

output = NetworkManagementApiLoginOutput()
output.body = NetworkManagementApiLoginOutput.Body()
output.body.login_response = LoginResponse()
output.body.login_response.result = Result()
output.body.login_response.result.status = "pame"
serializer = XmlSerializer()
serializer.config.pretty_print = True
print(serializer.render(output))


```

```xml 
<?xml version="1.0" encoding="UTF-8"?>
<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">
  <soap-env:Body>
    <ns1:loginResponse xmlns:ns1="http://microfocus.com/nas/2020/08">
      <Result>
        <ns1:Status>pame</ns1:Status>
      </Result>
    </ns1:loginResponse>
  </soap-env:Body>
</soap-env:Envelope>


```

**Comment by brunnels** [comment]
Maybe I did not state the issue correctly?  

On the main branch I generated the client in the [mfna directory](https://github.com/brunnels/xsdata-mfna/tree/main/mfna) with `xsdata -mll 120 --relative-imports -ss clusters -p mfna mfna-partial.wsdl`

If I run [these tests](https://github.com/brunnels/xsdata-mfna/blob/main/test_login.py) on the main branch, they fail.

If I run the same tests from the [generate-fixes branch](https://github.com/brunnels/xsdata-mfna/tree/generate-fixes) they pass.

[Here are the changes](https://github.com/brunnels/xsdata-mfna/pull/2/files) I made to get them to pass.

With the namespace as an empty string in the `LoginResponse` dataclass metadata the `test_success` test fails with `AssertionError: None is not an instance of <class 'mfna.result.Result'>` because it is unable to parse the loginResponse.

**Comment by tefra** [comment]
I hear you @brunnels and I understand what you are saying but soap ui is also generating the same models as xsdata

![Screenshot from 2021-11-15 15-19-14](https://user-images.githubusercontent.com/2098915/141788804-63a45316-266c-4fb1-9a29-92759a0035ca.png)

Either both xsdata and soapUI are doing it wrong or I am missing something, that's why I wanted a source with official request/responses

**Comment by brunnels** [comment]
I wish MFNA had more docs but this is the actual response I'm receiving from our MFNA server.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header/>
  <SOAP-ENV:Body>
    <nas:loginResponse xmlns:nas="http://microfocus.com/nas/2020/08">
      <nas:Result>
        <nas:Status>200 Logged in</nas:Status>
        <nas:Text>s229dc048-746e-471e-aaf8-66f7317d89d7</nas:Text>
      </nas:Result>
    </nas:loginResponse>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

It looks like the thing that matters is that  `<Result></Result>` will parse but the namespaced response from MFNA `<nas:Result></nas:Result>` will not.

I created [3 additional tests](https://github.com/brunnels/xsdata-mfna/blob/main/test_login.py#L120) to verify the soapUI output parses, that the xsdata output parses, and that removing the namespace from `Result` of the MFNA response parses.

**Comment by brunnels** [comment]
AFAIK, MFNA is using java AXIS or AXIS2 for their SOAP implementation so it's probable that other AXIS implementations will exhibit the same behavior.

**Comment by brunnels** [comment]
I just double checked and the xsdata and soapUI generated responses fail the tests if the namespace is added to the dataclass.

I guess if MFNA incorrectly adds the namespace then I can subclass `Client` and modify the `send` method to convert the response bytes to string and remove the namespace from `Result` there before using `parser.from_string`.

**Comment by tefra** [comment]
Is that wsdl an official copy?

```xml
    <wsdl:message name="activate_deviceResponse">
        <part name="Result" type="nas:Result"/> # the issue is here, it should be element and not type
    </wsdl:message>
```

it should have been

```xml
    <wsdl:message name="activate_deviceResponse">
        <part name="Result" element="nas:Result"/>
    </wsdl:message>
```

element means qualified, type means unqualified as far as I know, but in your case there an element and a complex type named `Result`. I am not really sure what the clients are supposed to do in this case... I 'll try to read once more the spec...

**Comment by brunnels** [comment]
that's straight from the server after install so hasn't been modified.  I will probably just use sed to fix the wsdl rather than modify the client.send method

**Comment by brunnels** [comment]
I guess we can close this and point the blame at MFNA or axis.

**Comment by tefra** [comment]
I want to try something @brunnels, I think I can add a validation during the processing to catch these cases and correct them

**Comment by tefra** [comment]
Hey @brunnels, I added the late validation for these cases that should take care of the issue, I found a source that said that even though message element exists the type can also point to an element or complex type.

Thanks for reporting and helping me troubleshoot this one!

**Comment by brunnels** [comment]
Glad to help and thank you for this great library.  It's the best thing out
there for modern SOAP code generation.  Everything else is ancient, broken,
or both.

**Comment by brunnels** [comment]
@tefra/xsdata
***@***.***> Thanks
again for the awesome library and support.  I will test everything monday
and let you know.
