### ISSUE TITLE
wsdl generation - add ability to exclude portType name from generated classes and files

### ISSUE THREAD

**Issue by brunnels** [tefra/xsdata#613]
Can you please add a generator flag to omit the portType name from generated file names and class names?  Something like `--omit-port_type_name` or something more elegant.

```xml
    <wsdl:portType name="NetworkManagementApi">
        <wsdl:operation name="login">
            <wsdl:documentation></wsdl:documentation>
            <wsdl:input message="nas:loginRequest"/>
            <wsdl:output message="nas:loginResponse"/>
            <wsdl:fault name="error" message="nas:nasFaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
```

I did this with a custom `Filters` class and it seems to work even with reserved keywords.  I didn't immediately see a way to access the wsdl portType name from the `Filters` class so I hardcoded it for testing but I may have missed it.

```python
class PortTypeFilters(Filters):
    def safe_name(
            self, name: str, prefix: str, name_case: Callable, **kwargs: Any
    ) -> str:
        if name:
            name = name.replace("NetworkManagementApi_", "")
        return super().safe_name(name, prefix, name_case, **kwargs)

    def class_name(self, name: str) -> str:
        alias = self.class_aliases.get(name)
        if alias:
            return alias

        name = self.safe_name(
            name.replace("NetworkManagementApi", ""),
            self.class_safe_prefix,
            self.class_case
        )
        return name
```

**Comment by tefra** [comment]
I would prefer something more generic like a search and replace in the class names, instead of adding something so specific to the wsdl mapper and I have been thinking this one for while now since I needed recently as well but it's not in my top priorities right now.


In the mean time, we already have the aliases config that can achieve the same, it might be a bit tedious to add one entry per operation but it's there

https://xsdata.readthedocs.io/en/latest/api/codegen.html

**Comment by brunnels** [comment]
Is there any command or debug that would output the default generator config xml for a wsdl file?  Then it would be easy enough to do a search and replace on the config to customize it as required.

**Comment by tefra** [comment]
I am not sure what you mean but this is [how](https://xsdata.readthedocs.io/en/latest/codegen.html#initialize-config) you initialize a config

```
$ xsdata init-config
```


https://xsdata.readthedocs.io/en/latest/codegen.html#initialize-config

**Comment by tefra** [comment]
hey @brunnels can you check #624  and let me know what you think?

**Comment by tefra** [comment]
hey @brunnels I just pushed an update for the generator config to introduce a search & replace process that completely repalces the older fixed aliases. Give it a look https://xsdata.readthedocs.io/en/latest/api/codegen.html

Maybe something like this could do the trick, you can also try to play with regex patterns the process is now based on `re.sub` https://docs.python.org/3/library/re.html#re.sub

```xml
  <Substitutions>
    <Substitution type="class" search="NetworkManagementApi" replace=""/>
  </Substitutions>
``` 

Thanks for the suggestion!
