### ISSUE TITLE
Unescaping HTML

### ISSUE THREAD

**Issue by pashashocky** [tefra/xsdata#615]
What is the unescaping of html procedure used within xsdata?

I've noticed that performing the following on my machine:
```
from html import unescape
unescape('&#150; test')  # returns '– test'
```

Processing some html within an xml field with xsdata would actually have `\x96 test` and not `– test`. So I would then have to apply additional post processing on the output string from the output object of xsdata.
```
'\x96 test'.encode('raw_unicode_escape').decode('cp1252')
```

Thank you.

**Comment by tefra** [comment]
xsdata is using behind the scenes the lxml or the builtin xml python module, so it's not doing any explicit (un)escape.

**Comment by tefra** [comment]
Re-open if you have any further questions.
