### ISSUE TITLE
XML Rendering missing NS for toplevel, bogus xsi:types

### ISSUE THREAD

**Issue by hcw70** [tefra/xsdata#620]
When creating back the XML from an xsdata object tree like this:
```
def RenderToXML(doc: MessageDb):
    """
    Renders the given Message Database to xml text,
    pretty printed
    :param doc:     The document to process
    :return:    String representing the resulting XML document
    """
    from xsdata.formats.dataclass.serializers import XmlSerializer
    from xsdata.formats.dataclass.serializers.config import SerializerConfig

    config = SerializerConfig(pretty_print=True, ignore_default_attributes=True)
    serializer = XmlSerializer(config=config)
    nsmap = { None:  msgdb.NAMESPACE , "db" : msgdb.NAMESPACE }
    txt = serializer.render(doc, ns_map=nsmap)

    return txt

```
I get a missing namespace declaration for the toplevel element:
```
<?xml version="1.0" encoding="UTF-8"?>
<MessageDb xmlns:db="http://deuta.de/config/DeutaMsgDatabase/v3" used-msgdb-version="3.0.0">
  <db:module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="DataTypes" xsi:type="TModule">
...
```
since for the element MessageDb there is no ns statement. 
Subsequentely this XML fails to be parsed back into xsdata.

Also there is a `xsi:type` declaration on every element, which is not needed most of the time in my document, since most elements are
not polymorphic.

Actually i want the result document look like the "original" document:
```

<?xml version="1.0" encoding="UTF-8"?>
<MessageDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://deuta.de/config/DeutaMsgDatabase/v3"
    used-msgdb-version="3.0.0">

    <module name="DataTypes">
...

```
with xsi:type only where needed.

Any hints on this?

**Comment by tefra** [comment]
Firsty don't add the same namespace as default and prefixed pick on or the other

```python
{ None:  msgdb.NAMESPACE , "db" : msgdb.NAMESPACE }
```

Secondly, the xsi:type is automatically added when the type of the object is derived from the defined type of the dataclass field, if you think it's added incorrectly please provide some schemas and samples so I can investigate furthe.

**Comment by hcw70** [comment]
When i only have thr "None" entry in the nsmap, i get:
```

<?xml version="1.0" encoding="UTF-8"?>
<MessageDb xmlns="" used-msgdb-version="3.0.0">
  <ns1:module xmlns:ns1="http://deuta.de/config/DeutaMsgDatabase/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="DataTypes" xsi:type="TModule">
    <ns1:annotation xsi:type="TAnyContent">Module annotation</ns1:annotation>
...
```
so i get a "ns1" NS on all elements, expect the toplevel.
When i only use the "db" NS, i get:
```
<?xml version="1.0" encoding="UTF-8"?>
<MessageDb xmlns:db="http://deuta.de/config/DeutaMsgDatabase/v3" used-msgdb-version="3.0.0">
  <db:module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="DataTypes" xsi:type="TModule">
    <db:annotation xsi:type="TAnyContent">Module annotation</db:annotation>
...
```
so i have "db" on all elements expect the toplevel.
In both cases i get an undefined / missing NS for the toplevel element.

Regarding XSI:Type, it may be related that i use "cooked" classes (derived from xsdata generated classes) for all instances,
`
    config = ParserConfig(process_xinclude=True, class_factory = msgdb.classFactory)

`instead of "raw" classes (generated by xsdata).

Could this also be the reason for the wrong toplevel element handling?

**Comment by tefra** [comment]
1. Yeah if you use a "default" namespace but the root element namespace doesn't match you get that effect `xmlns=""` , please use a default namespace only when the root element namespace is the same.

> Could this also be the reason for the wrong toplevel element handling?
 Yes exactly if you are using subclasses you will get the xsi:type attribute I am afraid, can you post here an small excerpt here to check if there anything we can do?

**Comment by hcw70** [comment]
> > In both cases i get an undefined / missing NS for the toplevel element.
> 
> Yeah if you use a "default" namespace but the root element namespace doesn't match you get that effect `xmlns=""` , please use a default namespace only when the root element namespace is the same. 

I am not sure i fully understand this sentence. 
I use this in the XSD:
```

<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    elementFormDefault="qualified"
    xmlns="http://deuta.de/config/DeutaMsgDatabase/v3"
    xmlns:d="http://deuta.de/config/DeutaMsgDatabase/v3"
    xmlns:xml="http://www.w3.org/XML/1998/namespace"
    targetNamespace="http://deuta.de/config/DeutaMsgDatabase/v3">

    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2005/08/xml.xsd"/>

    <xs:element name="MessageDB" type="TMessageDB">
...
    </xs:element/>

    <xs:complexType name="TMessageDB">
...
    </xs:complexType>

```
and this in the instance XML:
```
<MessageDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://deuta.de/config/DeutaMsgDatabase/v3" used-msgdb-version="3.0.0">
    <module name="DataTypes">
        <annotation>Module annotation</annotation>
...

```
And this in the xsdata parsing:
```

def CreateFromDocument(xml_text) -> MessageDb:
    """Parse the given XML and use the document element to create a
    Python instance.

    Also resolves MessageDB specific reference attributes,
    see also :class:`TBase` and :class:`TMessageDB` for attributes


    :param xml_text: An XML document.  This should be data (Python 2
        str or Python 3 bytes), or a text (Python 2 unicode or Python 3
        str).
    """
    elements = etree.fromstring(bytes(xml_text, encoding='utf-8'))
    try:
        xmlschema.assertValid(elements)
    except etree.DocumentInvalid as lxml_err:
        txt = str(lxml_err)
        raise msgdb.ValidationError(txt)

    import lxml
    from xsdata.formats.dataclass.parsers import XmlParser
    from xsdata.formats.dataclass.parsers.config import ParserConfig
    from xsdata.formats.dataclass.context import XmlContext
    from xsdata.formats.dataclass.parsers.handlers import LxmlEventHandler

    context = XmlContext()
    config = ParserConfig(process_xinclude=True, class_factory = msgdb.classFactory)
    parser = XmlParser(config=config, context=context, handler=LxmlEventHandler)
    doc = parser.parse(elements, MessageDb)

    doc.postLoad()
    return doc

```

> Did the generator miss the namespace for the root element?

IMHO not, see
```
@dataclass
class MessageDb(TMessageDB):
    class Meta:
        name = "MessageDB"
        namespace = "http://deuta.de/config/DeutaMsgDatabase/v3"

```


> 
> > Could this also be the reason for the wrong toplevel element handling?
> 
> Yes exactly if you are using subclasses you will get the xsi:type attribute I am afraid, can you post here an small excerpt here to check if there anything we can do?

Most subclasses are currently empty stubs like:
```
class MessageDb(raw_msgdb.MessageDb, TMessageDB):
    pass
```
but will get validation functions soon.
But maybe since this, MessageDb is a different class than raw_msgdb.MessageDb (similair for TMessageDB).

**Comment by tefra** [comment]
When you subclass like that I am afraid you have to repeat the Meta options of the original class, that's not inherited by design!

Why do you need to those subclasses @hcw70 ?

**Comment by hcw70** [comment]
> When you subclass like that I am afraid you have to repeat the Meta options of the original class, that's not inherited by design!

Ok, that is unfortunate. Maybe this is the reason for the empty toplevel NS thing.
Strangely other elements NS is correct. Maybe i can fix this by manually inherit / rewrite the Meta for the toplevel only. 

> 
> Why do you need to those subclasses @hcw70 ?
I want to add custom functions to the generated data classes, like validation, derived attributes and reference resolving.

**Comment by tefra** [comment]
> Ok, that is unfortunate. Maybe this is the reason for the empty toplevel NS thing. Strangely other elements NS is correct. > > Maybe i can fix this by manually inherit / rewrite the Meta for the toplevel only.

It should work, I think

**Comment by hcw70** [comment]
Ok, adding:
```

class MessageDb(raw_msgdb.MessageDb, TMessageDB):
    class Meta:
        name = "MessageDB"
        namespace = "http://deuta.de/config/DeutaMsgDatabase/v3"
    pass
```


to the toplevel element only solves one of my two serialization problems:
 

```
<?xml version="1.0" encoding="UTF-8"?>
<MessageDB xmlns="http://deuta.de/config/DeutaMsgDatabase/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" used-msgdb-version="3.0.0">
  <module name="DataTypes" xsi:type="TModule">
    <annotation xsi:type="TAnyContent">Module annotation</annotation>

```

Any hints how to solve the xsi:type handling?

**Comment by tefra** [comment]
> Ok, adding:
> 
> ```
> 
> class MessageDb(raw_msgdb.MessageDb, TMessageDB):
>     class Meta:
>         name = "MessageDB"
>         namespace = "http://deuta.de/config/DeutaMsgDatabase/v3"
>     pass
> ```
> 
> to the toplevel element only solves one of my two serialization problems:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <MessageDB xmlns="http://deuta.de/config/DeutaMsgDatabase/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" used-msgdb-version="3.0.0">
>   <module name="DataTypes" xsi:type="TModule">
>     <annotation xsi:type="TAnyContent">Module annotation</annotation>
> ```
> 
> Any hints how to solve the xsi:type handling?

Not really @hcw70 that's one of the reasons subclassing the original models is not recommended, the xsi:type is an xml mechanism to extend types and help with roundtrips, I highly recommend to re-think what you are trying to achieve and either move the business logic to helpers or try to add the new methods to the classes during the runtime.

**Comment by hcw70** [comment]
@tefra Adding the validation methods at runtime was my initial approach to this, but this leads to strange class hierarchies where you cant extend checks of base classes easily.
Also the code looks ugly, since the class is different in the text editor than in the runtime since i pushed some functions to the base.

Ok, so i am considering removing most of the XSI:Types by a post-XSLT.
