### ISSUE TITLE
Custom handling of simpleType in code generation

### ISSUE THREAD

**Issue by adament** [tefra/xsdata#623]
First of all thank you very much for a great tool. I am trying to use xsData for a somewhat large xsd resulting in around 4000 classes. Unfortunately this format specifies its own custom date type as a string type with a custom restriction
```
<xs:simpleType name="date">
<xs:restriction base="xs:string">
<xs:pattern value="\d{8}" />
</xs:restriction>
</xs:simpleType>
```
which results in date string fields on all the classes with a pattern in the metadata. Is it already or would it be possible to hook into the code generator and tell it to output fields using `datetime.date` with a custom format which could then be parsed / written using the converter functionality? I hope in this way to end up with a more ergonomic api than passing around dates as strings, and the size of the xsd makes maintaining custom modifications to the output of the code generator intractable.

It looks to me that to implement this feature one needs to replace or supplement the `DataType` enum with somethings that supports more dynamic information. Is that correct?

**Comment by tefra** [comment]
Hi @adament,

xsdata bindings support custom datetime formats see [here](https://xsdata.readthedocs.io/en/latest/data-types.html#working-with-date-strings) but the generator has no way to map that pattern to a date format

I am open to suggestions

**Comment by tefra** [comment]
If someone has any suggestion please re-open a new issue...
