### ISSUE TITLE
Convert XML sample into cannonical python representation code

### ISSUE THREAD

**Issue by vlcinsky** [tefra/xsdata#626]
# Motivation
We maintain set of XML samples conforming to specific XML schema.

We are considering to generate these samples by python code using xsdata and xsdata generated package.

It would be helpful to have an option to generate the python representation by converting XML samples into it.

# Context
The python package allowing to build XML objects depends on XML schema and on backing object library:
- Default backing library is based on dataclasses.
- Another one is based on attrs lib (if you install xsdata-attrs).
- In future we may expect pydantic based or others.

If we load an XML sample into xsdata based objects, we may:
- serialize it to XML
- serialize it to JSON
- use repr or str to print something close to Python code

# Proposed approach - pycode serializer
Currently, we use XmlSerializer
```python
from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig
```
If the backing library provides PycodeSerializer, we can get the python code generated.

Such a serializer would be optional (so new backing libraries would not be obliged to provide that).

To get the python code, one would find in documentation example similar to https://xsdata.readthedocs.io/en/latest/json.html#serialize-json-to-string or we could even add section Python code binding, which would not only serialize.

The code would be similar to:
```python
from tests.fixtures.books.books import *
from xsdata.models.datatype import XmlDate

from xsdata.formats.dataclass.context import XmlContext
from xsdata.formats.dataclass.parsers import XmlParser

from xsdata.formats.dataclass.serializers import PycodeSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig


xmlpath = Path("books.xml")
xml_str = xmlpath.read_text(encoding="utf-8")

parser = XmlParser(context=XmlContext())
books = parser.from_string(xml_str, Book)

config = SerializerConfig()
serializer = PycodeSerializer(context=XmlContext(), config=config)

pycode_str = serializer.render(books)

print(pycode_str)
```
and the generated python code would be:

```python
from tests.fixtures.books.books import *
from xsdata.models.datatype import XmlDate

Books(
   book=[
       BookForm(
           id="bk001",
           author="Hightower, Kim",
           title="The First Book",
           genre="Fiction",
           price=44.95,
           review="An amazing story of nothing.",
       ),
       BookForm(
           id="bk002",
           author="Nagata, Suanne",
           title="Becoming Somebody",
           price=33.95,
           pub_date=XmlDate(2001, 1, 10),
           review="A masterpiece of the fine art of gossiping.",
       ),
   ]
)

Even better support would be using CLI (but it is not really necessary).
```

**Comment by tefra** [comment]
Sounds intresting and I can see myself using this, I definitely needed something like that in the past, but I am not so sure how it fits in the xml & json bindings context, it could be a completely unrelated library that can print valid python code from any python object or dataclass.

**Comment by vlcinsky** [comment]
A code, which would process any python object or dataclass into valid python code would be very straightforward and great. But I am not sure it is as simple as it sounds. I would expect it would be as complex as pickling or as deepcopy code. I will be happy if anyone proves me wrong.

With PycodeSerializer we would give all the control to the author of given library creating the classes used to represent input (XML or JSON) data.

**Comment by tefra** [comment]
I would gladly accept any contributions on the subject, but it's really not a top priority for a binding library...

**Comment by tefra** [comment]
Re-opening this one

**Comment by tefra** [comment]
Hi @vlcinsky I know it's been a while, but the first version is now on master, give it a try

**Comment by vlcinsky** [comment]
@tefra excellent.

My first tests show, that the code looks good, it has only one issue with the `lang` parameter.

I assume the reason could be, that the `lang` is defined on XML level itself and not as part of XSD. If I comment the `lang` parameter out, things work well.

I will create a tests case for it.

**Comment by tefra** [comment]
> @tefra excellent.
> 
> My first tests show, that the code looks good, it has only one issue with the `lang` parameter.
> 
> I assume the reason could be, that the `lang` is defined on XML level itself and not as part of XSD. If I comment the `lang` parameter out, things work well.
> 
> I will create a tests case for it.

Can you open a new issue with an example? I can take a look

**Comment by vlcinsky** [comment]
The example is part of existing code - try to save and run the "expected result".

Here is what I have created and modified (commented out the `lang` parameter) to make it working:
```python
from tests.fixtures.books.books import BookForm, Books
from xsdata.models.datatype import XmlDate

books = Books(
    book=[
        BookForm(
            author="Hightower, Kim",
            title="The First Book",
            genre="Fiction",
            price=44.95,
            pub_date=XmlDate(2000, 10, 1),
            review="An amazing story of nothing.",
            id="bk001",
            # lang="en"
        ),
        BookForm(
            author="Nagata, Suanne",
            title="Becoming Somebody",
            genre="Biography",
            price=33.95,
            pub_date=XmlDate(2001, 1, 10),
            review="A masterpiece of the fine art of gossiping.",
            id="bk002",
            # lang="en"
        ),
    ]
)
```
