### ISSUE TITLE
Automatic initialisation similar to JAXB

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#628]
In order to use the "append" function on route_points, xsData currently requires that an unambiguous object is still initialised manually. If possible I would like to know if it is feasible that the commented out line could be omitted.

```python
from netex import ServiceFrame, RoutePointsInFrameRelStructure, RoutePoint, LocationStructure2, Pos

service_frame = ServiceFrame()
# service_frame.route_points = RoutePointsInFrameRelStructure()

route_point = RoutePoint(location=LocationStructure2(pos=Pos(0, 0)))
service_frame.route_points.route_point.append(route_point)
```

**Comment by tefra** [comment]
How is jaxb doing that? I 've never heard that before...

**Comment by skinkie** [comment]
> How is jaxb doing that? I 've never heard that before...

In JAXB I basically do serviceFrame.getRoutePoints().add(). The getRoutePoints checks if the list is already initialised.

**Comment by tefra** [comment]
You are using this [plugin](https://github.com/dmak/jaxb-xew-plugin) right? 

It doesn't really fit python or xsdata we don't have getters/setters, any suggestions?

**Comment by skinkie** [comment]
> You are using this [plugin](https://github.com/dmak/jaxb-xew-plugin) right?

I have never seen this one. But there are several in place that also allow ".withRoutePoint()" in order to instantiate them.
 
> It doesn't really fit python or xsdata we don't have getters/setters, any suggestions?

If it does not work, just close it. Try/except is bad practice any case.

**Comment by tefra** [comment]
Yeah it's not really doable in python
