### ISSUE TITLE
Abstract stuff has not fully been filtered

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#629]
From the NeTEx schema;

```python
@dataclass
class Route2(LinkSequenceVersionStructure):
    """
    Dummy supertype for Route.
    """
    class Meta:
        name = "Route_"
        namespace = "http://www.netex.org.uk/netex"
```
```xsd
    <xsd:element name="Route_" type="LinkSequence_VersionStructure" abstract="true" substitutionGroup="LinkSequence">
        <xsd:annotation>
            <xsd:documentation>Dummy supertype for Route.</xsd:documentation>
        </xsd:annotation>
    </xsd:element>
```

**Comment by tefra** [comment]
The filter I applied was for the field type annoations, not from generating those abstract classes

**Comment by skinkie** [comment]
> The filter I applied was for the field type annoations, not from generating those abstract classes

Would it be feasible to filter them as well?

**Comment by tefra** [comment]
I am open to suggestions, other schemas actually depend on abstract types

**Comment by skinkie** [comment]
> I am open to suggestions, other schemas actually depend on abstract types

How do they depend on them? Are they instantiated from an abstract type?

**Comment by tefra** [comment]
As extensions

**Comment by tefra** [comment]
Thanks for reporting @skinkie I added a more strict check as to what models should be generated, now only global non abstract types will be generated and any complex type, or enumerations that are actually referened in the other models


That should remove another ~2k lines from the netex output :rocket:
