### ISSUE TITLE
Allow serializer to skip "default" values

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#630]
At this moment xsData exports the all default values. Is it already possible to skip the default values?

**Comment by tefra** [comment]
For attributes, I recently added the SerializerConfig.ignore_default_attributes, for elements I am afraid it's not possible.

https://xsdata.readthedocs.io/en/latest/api/reference/xsdata.formats.dataclass.serializers.config.SerializerConfig.html#serializerconfig

**Comment by skinkie** [comment]
Thanks! That does the job.
