### ISSUE TITLE
key-identity references

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#632]
Within JAXB, if key-identity constraints are modeled correctly, and their references result into code that 'resolves' the reference to the object that is referred to becomes visible. Hence it is not required to create an index, for all objects that can be referenced, the references just become that object. Is this something can can be supported within xsData/python is such way that a reference can be accessed directly?

While for the railML schema, this has been modeled quite good, NeTEx does not support the standaard keyref pairs, because it uses compound keys. The _combination_ of one or multiple keys should refer to an object that exists.

Resolving keyrefs sounds like something that would make the datamodel easier to use.

**Comment by tefra** [comment]
Can you share an api example of what you mean, I 've never worked with keyrefs.

**Comment by skinkie** [comment]
You mean in JAXB?

**Comment by tefra** [comment]
Anything just something to help me understand the request
