### ISSUE TITLE
Custom Element as object within the tree 

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#635]
My favorite NeTEx schema has the ability to create extensions, for these extension to add any XML-element. Using Element('Something') in xsData I end up with the warning: 

```
ConverterWarning: No converter registered for `<class 'xml.etree.ElementTree.Element'>`
  warnings.warn(f"No converter registered for `{datatype}`", ConverterWarning)
```

In effect the element is then rendered as:

```xml
<Extensions>&lt;Element 'MaxLength' at 0x7faf7ecfe040&gt;</Extensions>
```

What is the proper way to do this?

**Comment by tefra** [comment]
You need to use one of the buildin generic models, the AnyElement

https://github.com/tefra/xsdata/blob/c98ea6fba67932ef8eba610cb2b2e1ac29ebc72a/xsdata/formats/dataclass/models/generics.py#L15-L24


Note to self: docs!!!

**Comment by skinkie** [comment]
@tefra a FAQ, because the problem remains searchability.

**Comment by tefra** [comment]
> @tefra a FAQ, because the problem remains searchability.

We will get there, https://xsdata.readthedocs.io/en/latest/faq.html
