### ISSUE TITLE
xpath like querying through object structure

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#637]
I am currently using partial deserialisation of a document, because this is the only way that allows me to ask for all objects of the same type. Especially for complex schema's where the location of the Element is known, but would still require to iterate over all list (or worse: choices).

Could you envision a way that would allow to query over the structure similar to xpath? Or less generic: ask for all the same object types and return this as a list?

**Comment by tefra** [comment]
Please come up with an api suggestion for this one... or an example from another library in any language.

Closing until then...
