### ISSUE TITLE
\n character is escaped to &#13;

### ISSUE THREAD

**Issue by Przemek625** [tefra/xsdata#638]
I noticed that during generating `xml` the new lines character `\n` is escaped to `&#13;`.

Example:

`text = "a\nb" 
`
will be converted to:

`<some-tag>a&#13;b</some-tag>
`
Why does it happen? Is there a way to get \n instead of &#13;?

**Comment by tefra** [comment]
xsdata is not doing any escaping, if something like that happens its something from lxml, or the builtin xml python, which writer are you using?

Can you also provide python, lxml versions and maybe a snippet because I can't really reproduce it

```
        config = SerializerConfig(pretty_print=True)
        serializer = XmlSerializer(config=config, writer=XmlEventWriter)
        books.book[0].title = "foo\nbar"
        actual = serializer.render(books)
        print(actual) 
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ns0:books xmlns:ns0="urn:books">
  <book id="bk001" lang="en">
    <author>Hightower, Kim</author>
    <title>foo
bar</title>
    <genre>Fiction</genre>
    <price>44.95</price>
    <pub_date>2000-10-01</pub_date>
    <review>An amazing story of nothing.</review>
  </book>
</ns0:books>
```

**Comment by Przemek625** [comment]
`I use xsdata==21.1, and python3.8, lxml==4.6.3`

`text = 'language certificate required; Language of studies 2 and its recommended language skills level (CERF level) Polish – C1 \r\n(courses for regular students)\r\n'`

```
from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig

target =  MyModel()
target.other_info_terms = text
xml_serializer = XmlSerializer(config=SerializerConfig())
rendered_xml = xml_serializer.render(target)
```

'<?xml version="1.0" encoding="UTF-8"?>\n<MyModel><ns0:other-info-terms xmlns:ns0="https://github.com/get-sechema.xsd">language certificate required; Language of studies 2 and its recommended language skills level (CERF level) Polish – C1 &#13;\n(courses for regular students)&#13;\n</ns0:other-info-terms></MyModel>'

Thank you for your help. This snippet might not fully work, because I did not add my true model, but maybe the information that I provided would be enough. Please let me know.

**Comment by tefra** [comment]
lxml in order to be compliant with the w3c xml 1.1 is escaping carriage returns, any xml parser, including the lxml is supposed to translate those back to their original form.

Here's a good [reading](https://stackoverflow.com/questions/2265966/xml-carriage-return-encoding) 

I am guessing the parser from the other side doesn't translate those entities for you? There is not much I can do since this is lxml's behavior but I just checked that the python buildin writer doesn't escape anything, you could switch to that writer.

```
from xsdata.formats.dataclass.serializers.writers import LxmlEventWriter  # default based on lxml
from xsdata.formats.dataclass.serializers.writers import XmlEventWriter  # based on native python xml module

serializer = XmlSerializer(config=config, writer=XmlEventWriter)
```
