### ISSUE TITLE
Imports raise SyntaxError with FieldName as originalCase

### ISSUE THREAD

**Issue by fteule** [tefra/xsdata#646]
Hi,
I some cases I detected that generated bindings could be invalid when I set in the config FieldName to originalCase.
The generation ends successfully but when I import the module an exception is raised:
```
In [1]: import SampleBindings.my_schema
Traceback (most recent call last):

  File "/home/user/xsdata/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-c0390bf7dfdc>", line 1, in <module>
    import SampleBindings.my_schema

  File "/home/user/SampleBindings/__init__.py", line 1, in <module>
    from SampleBindings.my_schema import (

  File "/home/user/SampleBindings/my_schema.py", line 12
    @value: Optional[float] = field(
          ^
SyntaxError: invalid syntax
```
If I set in configuration FieldName to pascalCase, the field is correctly generated as "Value".

I prepared a sample package that reproduce problem:
[Sample.tar.gz](https://github.com/tefra/xsdata/files/7939908/Sample.tar.gz)

I tried to change safePrefix value but it doesn't change this behavior.

Thank you for this library

**Comment by tefra** [comment]
I can confirm the issue @fteule thanks for reporting!

**Comment by tefra** [comment]
Hey @fteule give the pr #647 a try, I have to check a few things but it should also resolve your issue

**Comment by fteule** [comment]
Hi,

Thanks for this correction but I encounter an other mistake with it
I prepared a new package : 
[Sample.tar.gz](https://github.com/tefra/xsdata/files/7950614/Sample.tar.gz)
 my DM.

For information my data package is the same that in #643 
We are clearly interested by recursive mode :)

**Comment by tefra** [comment]
Please don't use the same convention for both class and field names, in the generated models we have a field with the same name and type as another class.

Its the cause of the issue and it's pretty impossible to solve, the genrator would have to cross check all field names with all class names and start appending suffixes and thus loosing the whole point of the `originalCase` convention. 


```python
class unit(Enum):
    M = "m"
    KG = "kg"
    VALUE = "%"
    NA = "NA"


@dataclass
class myComplexType2:
    ....
    unit: Optional[unit] = field(
   ....
```

**Comment by tefra** [comment]
The fix for the initial issue is on master and will be on the next release!

**Comment by fteule** [comment]
perfect, thanks for all !
