### ISSUE TITLE
substitutionGroup not detected during model generation

### ISSUE THREAD

**Issue by THM-MA** [tefra/xsdata#648]
I try to use XSDATA to parse Business Process Model and Notation (BPMN) 2.0.2 diagrams.
https://www.omg.org/spec/BPMN/2.0.2/

The XS schema contains a _substitutionGroup_ Element that is not detected during model generation. When parsing a valid BPMN XML file using the generated models an "Unknown property" occurs.

A working example with full error description and details (schema, generated model, parser code, name of substitutionGroup) can be found here:

https://github.com/THM-MA/xsdata-substGrp

I've already tried different structure styles (filenames, namespaces, clusters, usw.) to avoid namespace conflicts without success.

The XSDATA documentation 21.8 (2021-08-03) mentions _„Updated fields derived from xs:substitutionGroups to optional”_. May this be the problem?

Any help is highly appreciated!

Thanks
Thomas

**Comment by tefra** [comment]
@THM-MA amazing job reporting this issue, it really helps with troubleshooting.

**Comment by tefra** [comment]
Amazing case @THM-MA I have no such examples in either my samples or the w3c test suite!

The fix is on master and will be included in the next release, thanks for the detailed report :love_you_gesture:
