### ISSUE TITLE
Hashes for objects with lists

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#649]
In #536 we discussed the ability to do a hash(on_object). I have noticed using 'unsafe hash' that every object gets a hash function and will fail if such data class has an unhashable type somewhere (such as a list). Using safe hash, the object becomes unhashable itself, and prevent such behavior.

**Comment by tefra** [comment]
True, what should the generator do @skinkie instead?

**Comment by skinkie** [comment]
I think there are practically two situations.
1) you are parsing an object and typically want to have them as-is
2) you are creating an object and when done with it, freeze it

Ideally hashing would just replace the list with a tuple when the hash function is called. I also fail to see why this problem isn't generically solved in Python.

**Comment by tefra** [comment]
I think it's pretty straight forward, if someone needs hashes for list objects they should enable the `frozen` feature I don't see any simple solution for this one.
