### ISSUE TITLE
Unknown property error, when parsing inherited dataclasses with different namespaces

### ISSUE THREAD

**Issue by THM-MA** [tefra/xsdata#654]
I try to use XSDATA to parse Business Process Model and Notation (BPMN) 2.0.2 diagrams.

https://www.omg.org/spec/BPMN/2.0.2/

The XS schema contains a waypoint Element that is not detected during parsing due to a namespace conflict caused by the parser class XmlMetaBuilder.

A working example with full error description and details (schema, generated dataclasses, parser code) can be found here:

https://github.com/THM-MA/XSDATA-waypoint

After debugging for several hours I truly believe that this is a parser bug.

Any help is highly appreciated!

Thank you so much for your support and this wonderful piece of software
Thomas

**Comment by tefra** [comment]
Thanks for the excellent report @THM-MA and for the effort to troubleshoot it, I am on it!

**Comment by tefra** [comment]
Thanks again @THM-MA amazing work on reporting the issue.

The xsd suite is very interesting and has some very rare at least to me features, I took the liberty of adding it to the samples repo.
https://github.com/tefra/xsdata-samples/tree/master/bpmn

**Comment by THM-MA** [comment]
Retest successful. Thank you so much @tefra for your kind support.

The BPMN 2.0 XSDs are a truly complex beast to tame, I also learned lots of new stuff from it.

Let me know if i can value the work you put into your excellent XSDATA package by providing some further text cases or something similar.
