### ISSUE TITLE
element badly becomes list because of bad max_occurs merge

### ISSUE THREAD

**Issue by rvalyi** [tefra/xsdata#666]
Consider an xsd element like (it's one of the numerous Brazilian invoice taxes):
`<xs:element name="IPI" type="TIpi" minOccurs="0"/>`
(full schema here: https://github.com/akretion/nfelib/blob/master-xsdata/schemas/nfe/v4_0/leiauteNFe_v4.00.xsd )

in fact because it has **no explicit maxOccurs** attribute, it's a **single element**. A valid XML invoice here contains for instance:
![2022-03-19_14-17](https://user-images.githubusercontent.com/16926/159138431-9ef8695e-2281-4ed5-bca4-1baa4c4e9cba.png)
( full example here: https://github.com/akretion/nfelib/blob/master-xsdata/tests/nfe/v4_00/leiauteNFe/26180875335849000115550010000016871192213331-nfe.xml )

But xsdata will transform this element as a list:
![2022-03-19_14-29](https://user-images.githubusercontent.com/16926/159138461-6b7752b5-d824-41b6-a794-3fdc7b7cf61c.png)

Let me now explains what happens:

So despite it is constraints to this type="TIpi", it should behave exactly like other tax elements such as ICMS, PIS COFINS who got their restriction type described inside them like:

![2022-03-19_14-20](https://user-images.githubusercontent.com/16926/159138520-5ce26949-e8d3-4b77-aa19-4c76fd054e2c.png)

But what happens with IPI is that inside xsdata/codegen/handlers/attribute_merge.py
you try to merge the attr maxOccurs with the restriction maxOccurs of the TIpi type. As there is no maxOccurs
you set it to both to 1:
![2022-03-19_14-22](https://user-images.githubusercontent.com/16926/159138514-5fdbe1fb-bdfe-4019-994c-4d6ada3f4d70.png)

At the end you have maxOccurs=2 and now you'll interpret the element as a list in xsdata/codegen/models.py:
![2022-03-19_14-13](https://user-images.githubusercontent.com/16926/159138526-e80830d8-721e-4a58-8c52-107f9c22a283.png)

And as a result you generate the ipi element badly as a list instead of a single complexType:
![2022-03-19_14-29](https://user-images.githubusercontent.com/16926/159138461-6b7752b5-d824-41b6-a794-3fdc7b7cf61c.png)

I'm sbumitting a PR with a fix attempt.

**Comment by tefra** [comment]
Hi @rvalyi,

You have to enable [compound fields](https://xsdata.readthedocs.io/en/latest/examples/compound-fields.html) for your case.

In your schema, you have a choice of two sequences where one element is repeated in both of them, this has two issues, first of all a model can't have two fields with the same name, so it has to merge them, but it what order, remember in sequences the order matters.

```xml
<choice>
    <sequence>
        <element name="a" />
        <element name="b" />
    </sequence>
    <sequence>
        <element name="b" />
        <element name="c" />
        <element name="a" /> <!-- Yeap this is valid -->
    </sequence>
</choice>
```

Your solution will work for your case but it wouldn't work for other cases like this, or in your case if the element `IPI` was a list in one of the sequences

```xml
<xsd:element name="root" >
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="e" type="xsd:string" />
                        <xsd:element name="whatever" type="xsd:string" />
			<xsd:element name="e" type="xsd:string" />
			<xsd:element name="e" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>
```

There are a few more bizzare cases like that with sequences, that's why the compound field was introduced in order to solve all of these. The compound fields is grouping the fields together. The compound fields is simlar to how java and xjc is dealing with these.

**Comment by tefra** [comment]
I would love if someone could come up with a better proposal that compound fields, but for the time being it solves all those issues, in a somewhat elegant way.

**Comment by rvalyi** [comment]
Ok, thank you very much I'll try tomorrow and confirm if it works.

**Comment by rvalyi** [comment]
OK I see the effect of --compound-fields. Indeed it seems there is not such issue with the IPI element with it.

That being said I'll need to study this option quite a lot more to see if I will use it or not. The reason is I'm migrating a part of the open source Brazilian localization if the Odoo ERP from generateDS to xsdata and we had no such compound-fields thing on generateDS. We don't use only the binding but also my Odoo ERP datamodel generator (inspired from your plantuml plugin) https://github.com/akretion/xsdata-odoo and I had some custom code to work around choices.

Looking quickly on the generated code with --compound-fields it seems it doesn't deal with the existing xsd choices elements the same way that these choices elements that are introduced by the --compound-fields option. Like if I use it on  https://github.com/akretion/nfelib/blob/master-xsdata/schemas/nfe/v4_0/leiauteNFe_v4.00.xsd I will find no choice container for the "ICMS" tax element.

So eventually I go with a simple override. I'll study more and let you know...

**Comment by rvalyi** [comment]
all right @tefra in my use case I'll still go with my patch instead of the `--compound-field` option. I tested across a dozen of schemas for the Brazilian electronic invoicing with around 40 000 lines of generated Python code and the only occurrence of this issue is in this single field and my patch fixes it without any side effect in our case (from the diff).

So the `--compound-field` option is not really a good option for us, or at least not in the near future, because it deepen the nesting in several other places. Yes it works, but in our case, we are not only interested in the Python bindings but also in the corresponding generated Odoo ERP data models. As these models are persistent, it's interesting they are the flattest possible instead (these Odoo models would stay as flat as without the option). So using the `--compound-field` option would force us to complexify significantly the code for serializing and deserializing Odoo ERP objects for no practical benefit.

I would like to also mention that generateDS had some sort of support for the choice xsd elements you can see in this kind of schema: https://github.com/akretion/nfelib/blob/master-xsdata/schemas/nfe/v4_0/leiauteNFe_v4.00.xsd
had your `--compound-field` option been generating choice management the same way as for these xsd choice tags, then we might have adopted it (these choice element are only useful for automatic UI atop of the models, we can work our way around them later on retrieving them from the source XML).

But in any case thank your for your precious answers and let me know if there is interest in dealing with these choice tags.
