### ISSUE TITLE
Add validators

### ISSUE THREAD

**Issue by tefra** [tefra/xsdata#676]
Let's add proper model validations...

**Comment by johnnybakucz** [comment]
I used xsdata in one of my projects and would be happy to contribute here if any help is needed. This issue may align well with my skill and interests.

Could you please provide me with some more details about the issue? Additionally, if there are any specific guidelines or preferences you have for addressing this problem, please let me know.

**Comment by tefra** [comment]
With the introduction of custom decorators and bases classes, see [here](https://xsdata.readthedocs.io/en/latest/examples/extending-models.html), I am tempted to start a completely new project based on the [typed-dataclass](https://pypi.org/project/typed-dataclass/)

**Comment by rvalyi** [comment]
BTW we use these custom base class in https://github.com/akretion/nfelib for custom schema based validation and it works just great. So thank you @tefra .

**Comment by tefra** [comment]
This will be an xsdata plugin coming later this year
