### ISSUE TITLE
parser.parse(None, Model)

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#677]
Allow a None to be passed, and return None.

**Comment by tefra** [comment]
Can you explain why this is even needed?

**Comment by skinkie** [comment]
Because an xpath query may return None (there are no objects).

**Comment by tefra** [comment]
Sounds valid!

**Comment by tefra** [comment]
The abstract class signature is going to change from 

```python
def parse(self, source: Any, clazz: Optional[Type[T]] = None) -> T:
```

```python 
def parse(self, source: Any, clazz: Optional[Type[T]] = None) -> Optional[T]:
```

Which might cause issues for a lot of people, currently if the parser fails to create the binding model it fails with an exception. If we change the return type then everyone will have to check that the output is not `None` for all cases.

I am not so sure about this one...

**Comment by skinkie** [comment]
Is returning None, for a None input not more elegant? But I see your point. The question is, if the pattern below can be prevented.

```python
try:
  if object:
    object = parse()
except Exception:
  pass
```

**Comment by tefra** [comment]
It's not a very common pattern, I think most parsers out there fail early if the source is not acceptable, we don't even do that now in xsdata 😮‍💨 that needs some more elegant error handling, instead of relying on lxml or whatever underlying library is used.

```python
XmlParser().parse(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chris/projects/xsdata/xsdata/formats/dataclass/parsers/bases.py", line 53, in parse
    result = handler.parse(source)
  File "/Users/chris/projects/xsdata/xsdata/formats/dataclass/parsers/handlers/lxml.py", line 45, in parse
    ctx = etree.iterparse(source, EVENTS, recover=True, remove_comments=True)
  File "src/lxml/iterparse.pxi", line 78, in lxml.etree.iterparse.__init__
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

Personally it would extend the parser and add a new method like `try_parse`, I am not sure if that fits into the default parser though, have you seen something similar in other libraries/languages?

**Comment by skinkie** [comment]
Lets say this happens basically when I scan for "do you have some stoppoints for me" (xpath) so I can obviously split that in to the 'no, then don't try to parse it' but I currently have it as a one liner. Thats why I was hoping eating None and spitting it out would be generic enough.

**Comment by tefra** [comment]
I really don't see how this could be part of the core library, you should either extend the xml parser, or create some sort of project util method.

In the future the parse signature will change to dissallow None for source
