### ISSUE TITLE
Unable to parse time with nanoseconds

### ISSUE THREAD

**Issue by neriusmika** [tefra/xsdata#678]
I have documents containing XmlTime fields with nanoseconds, e.g. `03:35:25.482845071Z`. Currently, `DateTimeParser` can't parse such values. I think it would be nice to strip time to microseconds instead of returning the value as a string.

**Comment by tefra** [comment]
The update is on master, thanks for reporting @neriusmika

**Comment by neriusmika** [comment]
Thank you for the fix :tada:
