### ISSUE TITLE
Partial parsing causes the original XML tree to lose elements

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#683]
I am using partial parsing where I talke lxml.etree.parse(...) and feed parser.parse(tree.find(xpath), ObjectType). I have just noticed that if I take this aproach _anything_ that is parsed is removed from the element tree.

Is there a way not to do that?

**Comment by tefra** [comment]
That's how the lxml handler, frees up memory, while doing iterwalk/iterparse.

https://github.com/tefra/xsdata/blob/a98b9269d86262d68f74d29382365fbb2cf499ef/xsdata/formats/dataclass/parsers/handlers/lxml.py#L61-L69

If memory is not an issue, maybe try to clone the tree before, with `deepcopy`
https://lxml.de/tutorial.html

**Comment by skinkie** [comment]
I missed your reply. Is it possible to have a conditional clear()?

**Comment by tefra** [comment]
From [lxml](https://lxml.de/tutorial.html) regarding `iterparse`

>It also allows you to .clear() or modify the content of an Element to save memory. So if you parse a large tree and you want to keep memory usage small, you should clean up parts of the tree that you no longer need.

If I add a condition there, it will evaluate in each event, which even for small files could have a performance impact.

Either extend the lxml event handler and modify the default behavior, or copy and preserve the tree/element before passing it to the parser.

https://github.com/tefra/xsdata/blob/master/xsdata/formats/dataclass/parsers/handlers/lxml.py#L49
