### ISSUE TITLE
jsonschema

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#684]
Since JSON to xsData is already possible heuristically, would jsonschema be something that would be in scope to directly parse?

**Comment by tefra** [comment]
The generator can already work with raw json documents, I guess we have to add the json schema spec


Personal Note:
https://github.com/json-schema-org/JSON-Schema-Test-Suite

**Comment by tefra** [comment]
The only scary thing is that some draft version if I remember correctly broke backwards compatibility but we could start from the latest one.

**Comment by tlambert03** [comment]
This is definitely something I would also be interested in.  Might potentially look into it if you're not already doing it @tefra ?

**Comment by tefra** [comment]
Go for it @tlambert03
