### ISSUE TITLE
[Feature Request]: allow setting write method of lxml xml writer

### ISSUE THREAD

**Issue by sandersantema** [tefra/xsdata#714]
I'd like to be able to configure the method with which lxml writes xml, the various methods are documented in the lxml [documentation](https://lxml.de/apidoc/lxml.etree.html#lxml.etree.tostring).

For the time being I've manually added the setting myself after line 41 in `xsdata/formats/dataclass/serializers/writers/lxml.py`:
```
        xml = tostring(
            self.handler.etree,
            method="c14n",
            # encoding=self.config.encoding,
            pretty_print=self.config.pretty_print,
            xml_declaration=False,
        ).decode()
```

When using the `c14n` method setting encoding isn't allowed.

**Comment by tefra** [comment]
lxml has a lot of features, it's hard to support all of them out of the box. As a rule of thumb I am trying to maintain the two writers xml and lxml with the same subset of features.


You can always overide the default writer and add your custom configuration. The writers api is stable and I don't see any api changes any time soon.
