### ISSUE TITLE
Relationships, bigger than memory processing, databases: code annotation

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#715]
xsData does a very good job in converting structured schemas into programming code which assists both the deseralisation as the serialisation of XML-documents. The actual handling of documents is different per specification. It could be markup (e.g. XHTML), lists of objects of various amounts of types (e.g. GML) or a serialisation of a structured database (e.g. NeTEx).

The XML Schema defines unique constraints and a specific xs:ID. The latter, xs:ID, would be analogue to a _primary key_. The purpose of xs:unique is place dependent, but allows compound keys; a combination of multiple fields, when applied to the root-element it can function as a unique per selector, but when applied to children it can make sure that a key, in a key-value pair, would only exists once in a specific list, but not through the document. The XML-structure in a file is a tree, but becomes a graph when key-reference-identities point to key-identity-constraints. From a different perspective objects in a hierarchy may define some inheritance, which from a child-element perspective is almost always lost: a child cannot reach its parent nor can inheritance be defined (the child object will take by default the version of parent object, when the version of the child object is not defined).

At this point in time very few code generation is capable of handling xs:ID relationships within files. When working it allows the developer to directly step into the referenced object. I have not seen any code generation which is capable of indexed or just-in-time handling of key-reference-identities. Practically meaning that the document must be indexed and some external function must be called to resolve the reference. Monkey Patching / Reflection might be a possibility to come up with a specific implementation targeted for a single schema when interaction with the code generator is not possible.

When xsData's deserialisation is used as a sort of API the questions will pop up: Is there any way to do queries? Can you go beyond the memory? As discussed here before, lxml would allow xpath queries on a document. xsData is capable of deserialisation of a subtree. The downside: at this moment means that a part of the XML document is changed, element.clear(). The operation cannot be done twice. Would it be possible to queries without complete deserialisation? Or better: would it be possible to do processing via a database?

Due to the nature of XML it is difficult to state what element would constitute as _an independent object_, and what is in _essence_ a complex attribute container. It obviously does not mean that such a container, when having an identifier, cannot receive an incoming relationship. It can obviously be stated that an object subtree that does not have the possibility of receiving incoming relationships would therefore be attributes, but if one of these objects would be generally speaking "interesting to query" the xs:ID or a root level unique constraint might define its preference.

Practically speaking I am looking for a discussion that may lead into the development of a storage mechanism for bigger than memory documents.

**Comment by tefra** [comment]
My first reaction would be to somehow dump the data to bigquery or some bigdata db what can import stuff either from parquet or avro format and then use sql queries directly there. 

I haven't heard of a way to run queries against xml documents and xpath queries is not really a viable solution for your use case.

**Comment by skinkie** [comment]
Historically XQuery is the query language against XML documents. But why wouldn't there be a place for a query language against dataclasses? My objection against 'bigdata db' is that it takes a document, hence it requires deserialisation every time. I wonder if there is a generic strategy to pump an object store into. One of the key things that 'just a dataformat' do not solve are the referential relationships between objects.

**Comment by tefra** [comment]
Feel free to re-open...

Spring cleaning
