### ISSUE TITLE
Xsd 1.1 and Conditional inclusion

### ISSUE THREAD

**Issue by untereiner** [tefra/xsdata#717]
Hi! 
I was wondering if xsdata handles [Conditional inclusion](https://www.w3.org/TR/xmlschema11-1/#cip) ?

It is not much implemented but it allows evolutions of entities in schemas

**Comment by tefra** [comment]
xsdata doesn't handle conditional inclusions, It will generate all elements, attributes, etc always.

**Comment by tefra** [comment]
I am closing this one for now @untereiner, I would gladly accept a pr for this one
