### ISSUE TITLE
Assigning XML data to str attribute fails

### ISSUE THREAD

**Issue by eric-spitler** [tefra/xsdata#721]
I have an XSD where a particular attribute has no type defined, thereby defaulting to the `str` primitive after binding class generation. When using the binding to convert from XML to dataclasses, I receive the following error:
```log
xsdata.exceptions.XmlContextError: Primitive node doesn't support child nodes!
```

It appears that even though `xsdata` could set the XML into the `str` node, it is expecting/requiring the XML to go into a dataclass, despite the bound attribute's type definition. I was able to resolve the error by creating a new dataclass and replacing the auto-generated attribute, but this technically doesn't match the XSD.

Over-simplified XSD element and example XML (imagine the XML as single attribute of a larger binding instance):
```xsd
<xs:element ref="ts:someXml">
  <xs:annotation>
    <xs:documentation>Some documentation</xs:documentation>
    <xs:appinfo>
      <xs:qualifier label="Foo">More documentation</xs:qualifier>
    </xs:appinfo>
  </xs:annotation>
</xs:element>
```

```python
    some_xml: Optional[str] = field(
        default=None,
        metadata={
            "name": "someXml",
            "type": "Element",
            "required": True,
        }
    )
```

```xml
<ns:someXml>
  <ns:someChild type="bar">
    <ns:someCollection>
      <ns:someCollectionItem>lorem ipsum</ns:someCollectionItem>
      <ns:someCollectionItem>dolor</ns:someCollectionItem>
    </ns:someCollection>
  </ns:someChild>
</ns:someXml>
```

**Comment by eric-spitler** [comment]
I apologize but I cannot provide complete examples due to the proprietary nature of the XSD and XML.

**Comment by tefra** [comment]
yeah xsdata maps missing elements to simple sting nodes,
https://github.com/tefra/xsdata/blob/master/xsdata/codegen/handlers/process_attributes_types.py#L134

To support that xml output, change the field manually to something like this, in order to accept any content

```python
some_xml = Optional[object] = field(
        default=None,
        metadata={
            "type": "Wildcard",
            "namespace": "##any",
        }
    )
```

**Comment by eric-spitler** [comment]
That it pretty close to the workaround I put in. Thanks for confirming the behavior, which it seems is intentional and not a bug.
