### ISSUE TITLE
case  if attr.is_tokens: appears two times

### ISSUE THREAD

**Issue by untereiner** [tefra/xsdata#722]
HI,

This if case appears two times [here](https://github.com/tefra/xsdata/blob/f0a1eb9d5899e3243ad2cb66d4f1adabea7d5ecd/xsdata/formats/dataclass/filters.py#L593) and line 599.

Is it  normal ?

**Comment by tefra** [comment]
It's not very clear, yeah, it's to support simple tokens and lists of simple tokens

`List[str]` and `List[List[str]]` is there an issue?

**Comment by untereiner** [comment]
I don't have any problem. I was just wondering because it didn't get it. Thanks
