### ISSUE TITLE
Support requests sessions

### ISSUE THREAD

**Issue by mannickutd** [tefra/xsdata#726]
WSDL connections might require SSL connections.

class SessionTransport(DefaultTransport):

    def __init__(self, session: Optional[Session] = None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if session is None:
            session = Session()
        self.session = session

    def get(self, url: str, params: Dict, headers: Dict) -> bytes:
        return self.handle_response(self.session.get(
            url, params=params, headers=headers, timeout=self.timeout,
        ))

    def post(self, url: str, data: Any, headers: Dict) -> Any:
        return self.handle_response(self.session.post(
            url, data=data, headers=headers, timeout=self.timeout,
        ))
        
  session = Session()
  session.cert = ('crt', 'key')

**Comment by tefra** [comment]
Looks good, care to submit a pull request?

**Comment by tefra** [comment]
The update is on master!
