### ISSUE TITLE
Lack of a pin to docformatter < v1.5.1 causing CLI error 'Install cli requirements "pip install xsdata[cli]"' 

### ISSUE THREAD

**Issue by koiosjojo** [tefra/xsdata#728]
Docformatter's current release v1.5.1 removed the format_code definition along with some other conventions utilized downstream in xsdata and is causing generic errors to fire. Think this can be solved easily by pinning setup to < 1.5.1

**Comment by tefra** [comment]
On it

**Comment by dotlambda** [comment]
It would be nice to see xsdata support the latest version of docformatter. That simplifies packaging for Linux distros.

**Comment by tefra** [comment]
I am working on it unfortunately they removed the easy access to format docstrings programmatically
