### ISSUE TITLE
Q: Optional for attributes in generated classes

### ISSUE THREAD

**Issue by Murtagy** [tefra/xsdata#740]
This xml
```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <soap:Body>
    <el is_selected="true">
    </el>
  </soap:Body>
</soap:Envelope>
```
Produces this class
```

@attr.s
class El:
    class Meta:
        name = "el"
        namespace = ""

    is_selected: Optional[bool] = attr.ib(
        default=None,
        metadata={
            "type": "Attribute",
        }
    )
    value: str = attr.ib(
        default=""
    )

```

Can we achieve somehow that is_selected is not marked Optional?

It seems that 
https://xsdata.readthedocs.io/en/latest/faq/why-non-nullable-fields-are-marked-as-optional.html
mentions this problem, but changing the backend to attrs and uusing kw_only doesn't change the annotation

**Comment by Murtagy** [comment]
I imagine creating a parser, than "training" it over a few datas. Currently the tool seems helpful in generating initial template, but not much further than that.
So the annotation could be as strict as possible until you feed the parser another example with more loose data

**Comment by tefra** [comment]
Hey @Murtagy I updated the method xml/json codegen to calculate the min occurs correctly, the update is on master give it a try!

**Comment by Murtagy** [comment]
> Hey @Murtagy I updated the method xml/json codegen to calculate the min occurs correctly, the update is on master give it a try!

Nice, I will come back to you later next week

**Comment by Murtagy** [comment]
@tefra, this seems to work - now the structure or the layout is more concrete.

```
@dataclass
class El:
    class Meta:
        name = "el"
        namespace = ""

    is_selected: Optional[bool] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        }
    )
    value: str = field(
        default="",
        metadata={
            "required": True,
        }
    )
```

The signature still provides optionals. In my idea by generating a parser for this document I should be able to do:
```
if document.body.el.is_selected is True:
     # do something
      pass
```
This is not legal though - body is Optional, el is Optional and is_selected is not boolean.
I will receive a dozen of mypy errors and I would agree with type checker here, as it validly assumes that None could be there and it has no child elements.
Is that a constraint that could be bypassed in any way?
