### ISSUE TITLE
default substitution "Class"->"Type" does infix substitution

### ISSUE THREAD

**Issue by froh** [tefra/xsdata#742]
When I create a python class model from the [Ecore.xsd](https://git.eclipse.org/c/emf/org.eclipse.emf.git/plain/plugins/org.eclipse.emf.ecore/model/Ecore.xsd), the [xsdata.models.config.py:GeneratorConfig.create()](https://github.com/tefra/xsdata/blob/040692db47e6e51028fd959c793e757858c392d7/xsdata/models/config.py#L443) default substitution will mangle names EClass and EClassifier to EType and ETypeifier.

anchoring the search wit `^`and `$`like so `^Class$` fixed the problem.

`<Substitution type="class" search="^Class$" replace="Type"/>`

**Comment by tefra** [comment]
I admit the documentation lacks some examples for this case but yeah substitutions support regular expressions

https://xsdata.readthedocs.io/en/latest/api/reference/xsdata.models.config.GeneratorSubstitution.html#xsdata.models.config.GeneratorSubstitution

**Comment by froh** [comment]
point being:  the *default* value doesn't anchor the "class", and _that_ **default** is unexpected.  I simply used xsdata, and found an identifyer "ETypeifier" and scratched my head "whut on earth is going on here"?  and I head to search for a nasty while to find how it happens and where to fix it.

**Comment by tefra** [comment]
I ''ll update the default examples, to set them as reg expressions to avoid confusions.

**Comment by tefra** [comment]
Thanks for the report @froh the updated example should be much easier to understand

```
<Substitution type="class" search="(.*)Class$" replace="\1Type"/>
```
