### ISSUE TITLE
Respect order under specific tag

### ISSUE THREAD

**Issue by schef** [tefra/xsdata#745]
Hi guys,
I really like this software and I am using it to manipulate [musescore](https://musescore.org) score file.
The issue that I am having is that the order of my musical elements is important but fortunately I have figured it out how to preserve it.

I use `xsdata --package msmodel ./msmodel_examples/` to generate the model. Here is what i get:

```
@dataclass
class Voice:
    class Meta:
        name = "voice"

    chords: List[Chord] = field(
        default_factory=list,
        metadata={
            "name": "Chord",
            "type": "Element",
            }
        }
    )

    rests: List[Rest] = field(
        default_factory=list,
        metadata={
            "name": "Rest",
            "type": "Element",
            }
        }
    )
```
and this would be the desired output:
```
@dataclass
class Voice:
    class Meta:
        name = "voice"

    content: List[object] = field(
        default_factory=list,
        metadata={
            "type": "Elements",
            "choices": (
                {
                    "name": "Chord",
                    "type": Chord,
                },
                {
                    "name": "Rest",
                    "type": Rest,
                },
            )
        }
    )
```
Is it possible to instruct `xsdata --package` to generate such a model? The other thing I would want to now is how to call the same function from python.

Thanks :)

**Comment by tefra** [comment]
Do you have a sample xml file?

If the parser detects elements that need to be in a sequeuence `<a/><b/><a/>` it will add the sequence flag for you but this needs to be part of the xml content. After that you only need to enable the config for compound-fields `xsdata generate --compound-fields`

**Comment by schef** [comment]
Here is the [sample](https://github.com/tefra/xsdata/files/10800455/github_example.zip). The field I am interested in are tags under `/museScore/Score/Staff/Measure/voice`.

**Comment by tefra** [comment]
For that example the ordering works as expected @schef, It either has only chords/rests or they appear in sequencial order

`<chord/><rest/><chord/><rest/>` which is covered by the sequence flag


```python
@dataclass
class Voice:
    class Meta:
        name = "voice"

    chord: List[Chord] = field(
        default_factory=list,
        metadata={
            "name": "Chord",
            "type": "Element",
            "sequential": True,
        }
    )
    rest: List[Rest] = field(
        default_factory=list,
        metadata={
            "name": "Rest",
            "type": "Element",
            "sequential": True,
        }
    )
```

**Comment by schef** [comment]
In my case it is important which rest comes after which chord..the order is
correct for chords and the rests but the index information is missing when
comes what..

Is there option for that?

**Comment by tefra** [comment]
I used the sample you provided to generate the models, I parsed it and serialized it back and th result was exactly the same.

Can you provide a sample that fails?

**Comment by schef** [comment]
You are right! It looks the same? Where is the sequence kept?

**Comment by tefra** [comment]
Fields in the same sequence appear in sequential order `<a/><b/><a/><b/>` 

https://www.w3schools.com/xml/el_sequence.asp

For example
```xml
<xs:element name="pets">
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="dog" type="xs:string"/>
      <xs:element name="cat" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>
```


```Pets(dogs=['doggie', 'doggo'], cats=['purr', 'furr'])```

Will produce

<pets>
     <dog>doggie</dog>
     <dog>doggie</dog>
     <dog>doggie</dog>
</pets>

**Comment by tefra** [comment]
The xml document code generator can detect sequences 🤞 for easy cases

**Comment by schef** [comment]
Is it possible to get the sequence number from the code? When i want to iterate through the elements I'm not sure how to get the order?

**Comment by tefra** [comment]
You would have to write your own algorithm for that I am afraid, here are some excellent examples 
https://stackoverflow.com/questions/7529376/pythonic-way-to-mix-two-lists

**Comment by schef** [comment]
Thanks
