### ISSUE TITLE
custom type for generated class not formatted as expected 

### ISSUE THREAD

**Issue by GFuhr** [tefra/xsdata#752]
Hello,

First of all, thank you for this more than usefull package. I have an ugly xsd (can't share sorry) for which after the parsing and generating the classes, the types are not okay. It's not due to xsdata but to the xsd which put everything as str.

I was able using the pipeline of the cli to replace when needed the '{http://www.w3.org/2001/XMLSchema}string' for the attrs.type[0].qname with the correct type, as example List[int] but then when I generate the python class I have something like : 
```
@dataclass
class myclass:

        data: Optional[ListInt] = field(
            default=None
        )
```

and not the expected : 
```
@dataclass
class myclass:

        data: Optional[List[int]] = field(
            default=None
        )
```

so my question is, how to avoid that? I thought the problem was due to some jinja2 sanetizer but since I have the issue with print and write I'm not sure

Thanks in advance

**Comment by tefra** [comment]
Hi @GFuhr can you please share more info, a snippet or something?

Also what does this mean?

> I was able using the pipeline of the cli to replace when needed the '{[http://www.w3.org/2001/XMLSchema}string](http://www.w3.org/2001/XMLSchema%7Dstring)' for the attrs.type[0].qname with the correct type, as example List[int] but then when I generate the python class I have something like

**Comment by tefra** [comment]
It's hard to add/modify the types in the generator, your best bet and less hacky would be to modify the xsd and simply change/update the `maxOccurs="unbounded"`.

If you still want to go with a hackish way, you could modify the restriction.

`class.attrs[].restrictions.max_occurs=sys.maxsize`

**Comment by GFuhr** [comment]
I can't change the xsd  so I found a way to do it using inheritance of the Filter class and other class associated with to use my own Filter.type_name member function.
