### ISSUE TITLE
lxml parser consumes xml elements

### ISSUE THREAD

**Issue by leo-b** [tefra/xsdata#753]
Hi!

I noticed that the lxml dataclass parser modifies (i.e. consumes) the lxml tree while parsing:

```
from lxml import etree
from xsdata.formats.dataclass.parsers import XmlParser
from tests.fixtures.artists import metadata
import copy


if __name__ == '__main__':
    parser = XmlParser()
    with open("tests/fixtures/artists/art002.xml") as f:
        tree = etree.parse(f)
        # tree2 = copy.deepcopy(tree)

        print(f"before: {tree.getroot().getchildren()}")
        # [<Element {http://musicbrainz.org/ns/mmd-2.0#}artist at 0x7fbe09916940>]

        obj = parser.parse(tree, metadata.Metadata)

        print(f"after: {tree.getroot().getchildren()}")
        # []
```

Is this behavior intended?

**Comment by tefra** [comment]
Yes, in order to avoid excess memory usage.

**Comment by leo-b** [comment]
Sure, removing parsed elements by default completely makes sense.

However, an option to keep the xml tree intact would be useful for my usecase, where I also need to access the original xml.
(But I can deepcopy the tree before parsing it, of course.)

**Comment by tefra** [comment]
deepcopy the tree is an option of course, an alternative would be to override the lxml handler and skip the clear here
https://github.com/tefra/xsdata/blob/7d93ade74a1701e49ca95c18c9c44701313c1541/xsdata/formats/dataclass/parsers/handlers/lxml.py#L68
