### ISSUE TITLE
generate class hierarchy from xsd:complexType/sequence/group, instead of flattening the groups?

### ISSUE THREAD

**Issue by froh** [tefra/xsdata#764]
Hi,

this snippet of an AUTOSAR-00043-strict.xsd xmls schema will be transformed into a python class which has the referenced groups  flattened in:

 ```xsd
  <xsd:complexType abstract="false" mixed="false" name="BSW-SYNCHRONOUS-SERVER-CALL-POINT">
      <xsd:annotation>
         <xsd:documentation>Represents a synchronous procedure call point via the BSW Scheduler.</xsd:documentation>
         <xsd:appinfo source="tags">mmt.qualifiedName="BswSynchronousServerCallPoint"</xsd:appinfo>
         <xsd:appinfo source="stereotypes">atpObject</xsd:appinfo>
      </xsd:annotation>
      <xsd:sequence>
         <xsd:group ref="AR:AR-OBJECT"/>
         <xsd:group ref="AR:REFERRABLE"/>
         <xsd:group ref="AR:BSW-MODULE-CALL-POINT"/>
         <xsd:group ref="AR:BSW-SYNCHRONOUS-SERVER-CALL-POINT"/>
      </xsd:sequence>
      <xsd:attributeGroup ref="AR:AR-OBJECT"/>
   </xsd:complexType>
 
```

becomes ...

```python
@dataclass
class BswSynchronousServerCallPoint:
    class Meta:
        name = "BSW-SYNCHRONOUS-SERVER-CALL-POINT"

    short_name: Optional[Identifier] = field( ... )
    short_name_fragments: Optional["BswSynchronousServerCallPoint.ShortNameFragments"] = field( ... )
    context_limitation_refs: Optional["BswSynchronousServerCallPoint.ContextLimitationRefs"] = field( ... )
    variation_point: Optional[VariationPoint] = field( ... )
    called_entry_ref: Optional["BswSynchronousServerCallPoint.CalledEntryRef"] = field( ... )
    called_from_within_exclusive_area_ref: Optional["BswSynchronousServerCallPoint.CalledFromWithinExclusiveAreaRef"] = field( ... )
    s: Optional[str] = field( ... )
    t: Optional[str] = field( ... )

    @dataclass
    class ShortNameFragments:
        short_name_fragment: List[ShortNameFragment] = field( ...  )

    @dataclass
    class ContextLimitationRefs:
        context_limitation_ref: List["BswSynchronousServerCallPoint.ContextLimitationRefs.ContextLimitationRef"] = field( ... )

        @dataclass
        class ContextLimitationRef(Ref):
            dest: Optional[BswDistinguishedPartitionSubtypesEnum] = field( ... )

    @dataclass
    class CalledEntryRef(Ref):
        dest: Optional[BswModuleClientServerEntrySubtypesEnum] = field( ... )

    @dataclass
    class CalledFromWithinExclusiveAreaRef(Ref):
        dest: Optional[ExclusiveAreaNestingOrderSubtypesEnum] = field( ... )

```

I'd instead love to see something along these lines:

```python
@dataclass
class BswSynchronousServerCallPoint(ArObject, ShortNameFragments, ...):
    class Meta:
        name = "BSW-SYNCHRONOUS-SERVER-CALL-POINT"
```

is there a good way to hook into the generator to achieve this?

If I'm not mistaken this pattern of a sequence/group is a recommended pattern to model multiple inheritance.

**Comment by tefra** [comment]
Not really, only head elements and some complex types are generated everything else is flattened, that's the only to stay consistent and compatible between all the possibilities. Think of this scenario, in this case xsdata wouldn't be able to serialize the result correct as we rely on the ordering of the fields in dataclasses.

```xml
    <xsd:sequence>
        <xsd:element ref="whatver"/>
        <xsd:group ref="BaseClass"/>
     </xsd:sequence>
```

**Comment by froh** [comment]
if this is enabled (something like --mixed-in-bases) then 'bases aka embedded groups go before elements, else an error is raised'

in my narrow case the xml schema is generated.  the mixed-in bases (xsd:group) always precede the elements.

I found a beauty in the wild, freely accessible on github [autosar-00047-strict.xsd](https://github.com/autosaros/Standards/blob/master/Adaptive%20Platform/19.03/MethodologyAndManifests/AUTOSAR_TR_XMLSchemaSupplement/AUTOSAR_00047_STRICT.xsd)

There even are no elements if there are mixed-in bases.  instead the elements of the newly defined "class" actually are  gathered in the last group, which goes by the same name as the just defined complexType.

Now I'm happily willing to enable this myself.

What I was rather hoping for was to understand how to hook into and control xsdata class generation, and I don't get it, or I don't get it sufficiently yet.

xsdata reads the xml schema.  then magic happens :-) .  and then more magic happens :-) . and then code is generated using jinja2 templates.

what I do get is that the schema is walked, starting from the roots, recursively, in [SchemaMapper.map()](https://github.com/tefra/xsdata/blob/dac0b81a7a09f819edce2dd0c1b83350bb43820b/xsdata/codegen/mappers/schema.py#L33)

I also _think_ the flattening happens in this innocent looking function  [SchemaMapper.element_children()](https://github.com/tefra/xsdata/blob/dac0b81a7a09f819edce2dd0c1b83350bb43820b/xsdata/codegen/mappers/schema.py#L139)  is that so?

If so, I also get that changing this to generate parent classes instead might be a _major_ brain surgery.  because now we'd need to gather _two_ things:  first the 'bases' and then the remaining true elements.

Now before I go deeper into that, would you agree it fits well with dataclasses, because dataclasses gather all attributes from the bases and would it also sit well with parsing, as that uses the dataclasses.fields()?

**Comment by froh** [comment]
Hi,

so I started looking into this alternate, i.e. hierarchical generated class model.

Is it right that the transform from xml schema roughly goes like

1. read the xml schema into  a class hierarchy based off `xsdata.models.xsd.Schema` (via xsdata.codegen.transformer.SchemaTransformer.process_sources)
2. transform the xml schema into a class hierarchy in the xsdata.codegen.alayzer.ClassAnalyzer
    * the heart of this is xsdata.codegen.container.ClassContainer.process()
    * the flattening is done via xsdata.codegen.-handlers.FlattenAttributeGroups()
4. serialize the thus generated classes
    * very straightforward

I'd love to reuse most of this logic, because it does very very neat things to  to e.g. Enums and name mangling.

now here is my teensy little challenge:

the interaction between that handlers, what do they do and what do they expect is something.  quite something :-) 

how would you suggest I approach this?

I'd love to extend this in a way that works for mainline.
