### ISSUE TITLE
dataclass metadata minOccurs maxOccurs not generated on xsd element

### ISSUE THREAD

**Issue by Hazedd** [tefra/xsdata#768]
Hi,
thx for the awesome lib!. im working on a complex xsd's and im not getting the metadata minOccurs and maxOccurs in the generated dataclasses... i have seen output that has minOccurs and maxOccurs, so i assume it should work out of the box... but not sure if it's me or it's a bug in this version of xsdata.

py: 3.10
xsdata: 22.12

generating:
```console
xsdata ../xsd/124/IMSpoor-1.2.4-Communication.xsd --package models.imx.124 --structure-style clusters
```

```xml
<xs:element name="Signal">
	<xs:annotation>
		...
	</xs:annotation>
	<xs:complexType>
		<xs:complexContent>
			<xs:extension base="tPointTrackAsset">
				<xs:sequence>
					<xs:element ref="IlluminatedSign" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="ReflectorPost" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="StopConnection" minOccurs="0"/>
					<xs:element name="DepartureCondition" type="tDepartureCondition" minOccurs="0" maxOccurs="unbounded">
						<xs:annotation>
							...
						</xs:annotation>
					</xs:element>
					<xs:element ref="ATPType" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					...
```

results in:

```python
@dataclass
class Signal(TPointTrackAsset):
    ....

    class Meta:
        namespace = "http://www.prorail.nl/IMSpoor"

    illuminated_sign: List[IlluminatedSign] = field(
        default_factory=list,
        metadata={
            "name": "IlluminatedSign",
            "type": "Element",
        }
    )
    reflector_post: List[ReflectorPost] = field(
        default_factory=list,
        metadata={
            "name": "ReflectorPost",
            "type": "Element",
        }
    )
    ...

```

**Comment by Hazedd** [comment]
[xsd124.zip](https://github.com/tefra/xsdata/files/11032464/xsd124.zip)

**Comment by tefra** [comment]
Because they are implied for list elements they are omitted from the final output, in an attempt to minimize the final output

https://github.com/tefra/xsdata/blob/master/xsdata/codegen/models.py#L155-L160

**Comment by tefra** [comment]
Because they are implied for list elements they are omitted from the final output, in an attempt to minimize the final output

https://github.com/tefra/xsdata/blob/master/xsdata/codegen/models.py#L155-L160
