### ISSUE TITLE
Handle entity definitions

### ISSUE THREAD

**Issue by RobertBaruch** [tefra/xsdata#769]
[Entities ](https://www.w3schools.com/xml/xml_dtd_entities.asp)define shortcuts to special characters.

For example, in my DTD, I can define:

```xml
<!ENTITY hcirc "&#x0125;">
```

And then in the actual XML file (provided that the `DOCTYPE` points to a file that eventually includes the entity definitions), for example:

```xml
<rad>anar&hcirc;i</rad>
```

This should be parsed into `anarĥi` but it seems to just parse to `anar` (quitting at the `&`)

**Comment by RobertBaruch** [comment]
This includes [character entities](https://www.tutorialspoint.com/xml/xml_character_entities.htm) such as in `<rad>anar&#x0125;i</rad>`, which also fails to parse.

**Comment by tefra** [comment]
Hey @RobertBaruch can you please provide a sample or point me somewhere, I don't have many samples dtd and none of them include entities

**Comment by RobertBaruch** [comment]
Here's a set of four XML files that work together. The file `vokosgn.dtd` contains all the entity definitions.

[vokoxml.zip](https://github.com/tefra/xsdata/files/11592951/vokoxml.zip)

Here's a sample using this set of DTDs:
[abak.zip](https://github.com/tefra/xsdata/files/11592955/abak.zip)

**Comment by tefra** [comment]
Hey @RobertBaruch 

Thank you for the samples, I added a new option in the parser config to load external dtd files.
This option works only with the lxml handler (the default).


https://github.com/tefra/xsdata-samples/blob/master/voko/output/abak.xml

```
parser = XmlParser(config=ParserConfig(load_dtd=True))
```
