### ISSUE TITLE
Signal for circular references

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#770]
Some past tickets were about 'resolving' circular references. How easy would it be to get a list of circular references from the XSD?

**Comment by tefra** [comment]
I can add a debug message here and all from the cli to change the log level
https://github.com/tefra/xsdata/blob/28dea6840ba29c6a7c5d36b1c3340fe2b0798656/xsdata/codegen/handlers/process_attributes_types.py#L199

**Comment by tefra** [comment]
I added the debug message and a debug flag on the cli to print debug messages, give it a try
