### ISSUE TITLE
Support Python 3.10 Union operators (int | None)

### ISSUE THREAD

**Issue by loopj** [tefra/xsdata#771]
[PEP 604](https://peps.python.org/pep-0604/) introduced the concept of Union operators, which landed in Python 3.10.

This means you can write `int | None` instead of `Optional[int]`, etc.

Unfortunately the introduction of this new operator breaks certain type checks:
```python
>>> get_origin(Optional[int])
typing.Union
>>> get_origin(int | None)
<class 'types.UnionType'>
```

Currently this means if you are trying to use `XmlSerializer` or `XmlParser` on a dataclass which has a field using this new operator, you'll get the following error:

> TypeError: issubclass() arg 1 must be a class

I'm pretty sure the following code is the issue:
https://github.com/tefra/xsdata/blob/master/xsdata/formats/dataclass/typing.py#L37

I think the fix should be as simple as importing `UnionType` from `types` and adjusting this line as follows:

```diff
-        if origin is Union:
+        if origin is Union or origin is UnionType:
```

**Comment by zariiii9003** [comment]
See #681

**Comment by loopj** [comment]
Thanks, closing as dup
