### ISSUE TITLE
XSData field metadata naming conflicts with Pydantic/FastAPI OpenAPI docs

### ISSUE THREAD

**Issue by hamilton-earthscope** [tefra/xsdata#772]
# Description

First of all, I want to say that I love this project and it's been working great for us for serialization/deserialization of XML files.

We're now trying to build a FastAPI app around the same types defined in our XSD and want to use the XSData-generated classes to do this.

Currently, the generated classes break FastAPI's OpenAPI documentation generation due to naming conflicts in the generated dataclass's field metadata.

Example class:

```py
@dataclass(kw_only=True)
class GainType:
    value: float = field(
        metadata={
            "name": "Value",
            "type": "Element", # breaks expected behavior
            "namespace": "http://www.fdsn.org/xml/station/1",
            "required": True, # breaks expected behavior
        }
    )
```

I propose adding an XSData namespace `xsdata_` to the beginning of all metadata fields used by XSData to avoid conflicts between multiple packages using dataclass metadata in different ways; e.g. change the above to

```py
@dataclass(kw_only=True)
class GainType:
    value: float = field(
        metadata={
            "xsdata_name": "Value",
            "xsdata_type": "Element",
            "xsdata_namespace": "http://www.fdsn.org/xml/station/1",
            "xsdata_required": True,
        }
    )
```

Renaming the `type` and `required` fields fixes the OpenAPI documentation generation. But for consistency, I think we should add the namespace to all XSData field metadata names.

# Reproducion

1. FDSN StationXML schema ([available here](https://www.fdsn.org/xml/station/fdsn-station-1.2.xsd))

1. Set up python env

   ```shell
   python3.10 -m venv venv && source venv/bin/activate
   pip install xsdata[cli]==22.12 fastapi==0.95.0 uvicorn==0.18.3
   ```

1. Generate bindings using XSData CLI

   ```shell
   xsdata generate https://www.fdsn.org/xml/station/fdsn-station-1.2.xsd --kw-only --repr --eq --unnest-classes
   ```

1. Set up a simple FastAPI app using these classes

   ```py
   # reproduction.py
   from fastapi import FastAPI

   from generated.fdsn_station_1_2 import ChannelType

   app = FastAPI()

   @app.post("/foo", response_model=ChannelType)
   async def foo(body: ChannelType):
       return body
   ```

1. Start up the application

   ```shell
   python -m uvicorn reproduction:app --port 8000
   ```

1. Visit the docs page in your browser http://localhost:8000/docs

   FastAPI generates an error message on the web page:

   ```
   Failed to load API definition.

   Errors
   Fetch error
   Internal Server Error /openapi.json
   ```

   in the console you get output like

   ```
     File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
   pydantic.error_wrappers.ValidationError: 96 validation errors for OpenAPI
   components -> schemas -> AzimuthType -> properties -> value -> required
     value is not a valid list (type=type_error.list)
   components -> schemas -> AzimuthType -> $ref
     field required (type=value_error.missing)
   components -> schemas -> ChannelType -> properties -> code -> required
     value is not a valid list (type=type_error.list)
   components -> schemas -> ChannelType -> properties -> latitude -> required
     value is not a valid list (type=type_error.list)
   components -> schemas -> ChannelType -> properties -> longitude -> required
     value is not a valid list (type=type_error.list)
   components -> schemas -> ChannelType -> properties -> elevation -> required
     value is not a valid list (type=type_error.list)
   components -> schemas -> ChannelType -> properties -> depth -> required
     value is not a valid list (type=type_error.list)
   components -> schemas -> ChannelType -> properties -> location_code -> required
     value is not a valid list (type=type_error.list)

   ...
   (many more lines)
   ```

1. This cryptic error message is saying that the `required` field in the generated dataclasses `field(metadata={'required': True})` is expected to be a list.

1. Replace all occurences of this in the generated output by renaming the field `required` to `xsdata_required`:

   ```shell
   sed -i -e 's/"required"/"xsdata_required"/g' generated/fdsn_station_1_2.py
   ```

1. Restart FastAPI app and visit [the docs](http://localhost:8000/docs) again

   The docs do load now! Sweet! only one issue, the `field(metadata={'type': 'Element'})` is causing the following:

   ```json
   {
     // ... truncated for brevity
     "latitude": "Unknown Type: Element",
     "longitude": "Unknown Type: Element",
     "elevation": "Unknown Type: Element",
     "depth": "Unknown Type: Element",
     "azimuth": "Unknown Type: Element",
     "dip": "Unknown Type: Element",
     "water_level": "Unknown Type: Element"
   }
   ```

1. Replace all occurences of this in the generated output by renaming the field `type` to `xsdata_type`:

   ```shell
   sed -i -e 's/"type"/"xsdata_type"/g' generated/fdsn_station_1_2.py
   ```

1. Restart FastAPI app and visit [the docs](http://localhost:8000/docs) again

   docs load and OpenAPI spec is generated as expected!

# Summary

I assume that just making these changes to the generated dataclasses would break XSData's XML de/serialzation as its expecting specifically named metadata.

Making this change would allow XSData to not only de/serialize XML to/from JSON classes, but also seamlessly interop with FastAPI to generate OpenAPI docs using the XSD's types.

Thanks for all the work you do on this library!

Note: the same issue exists on the `xsdata-pydantic` library - however even without using Pydantic's dataclass substitute decorator, FastAPI can handle stdlib dataclasses directly after these naming changes.

**Comment by skinkie** [comment]
I would rather see FastAPI-XML to work as it advertises.

https://github.com/cercide/fastapi-xml/issues/2

**Comment by tefra** [comment]
My secret desire is to generate native pydantic classes and skip the dataclasses middleware...

**Comment by skinkie** [comment]
@tefra my secret desire is not having this generator to be python independent. There is no reason why this wouldn't work for any other language.

**Comment by tefra** [comment]
After summer time, I plan to attack this one more time, to use pure pydantic models, v2 sounds really interesting.

**Comment by tefra** [comment]
I am closing this one because it belongs [here](https://github.com/tefra/xsdata-pydantic/)

**Comment by tlambert03** [comment]
this is also something I've fixed in my v2 support mentioned in https://github.com/tefra/xsdata-pydantic/pull/18#issuecomment-1637128238
