### ISSUE TITLE
infinite loop with Mexican electronic invoicing schema

### ISSUE THREAD

**Issue by rvalyi** [tefra/xsdata#776]
Hello, I was trying `xsdata generate` with this xsd file http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd and sadly it creates an endless loop apparently, it seems related to the catCFDI.xsd include. if you try xsdata generate simply with this http://www.sat.gob.mx/sitio_internet/cfd/catalogos/catCFDI.xsd file you alreay get the infinite loop.
Any idea?

xsdata, version 22.12

**Comment by tefra** [comment]
Thanks for reporting @rvalyi 

That's a hell of enumeration with 90k plus members, during the processing of the classes, there is a handler that tries to merge duplicate fields and it's a bit complicated because it has to merge restrictions and data types, but for enumerations this overhead is not really needed we can skip these steps and just focus on the enumeration values.

The fix is on master, the generator now finishes in a reasonable amount of time,
I also suggest using the `-ss clusters` to split the files into separate modules.

```console
xsdata http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd -ss clusters
========= xsdata v22.12 / Python 3.9.16 / Platform darwin =========

Parsing schema http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd
Parsing schema http://www.sat.gob.mx/sitio_internet/cfd/catalogos/catCFDI.xsd
Compiling schema http://www.sat.gob.mx/sitio_internet/cfd/catalogos/catCFDI.xsd
Builder: 21 main and 0 inner classes
Parsing schema http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI/tdCFDI.xsd
Compiling schema http://www.sat.gob.mx/sitio_internet/cfd/tipoDatos/tdCFDI/tdCFDI.xsd
Builder: 15 main and 0 inner classes
Compiling schema http://www.sat.gob.mx/sitio_internet/cfd/4/cfdv40.xsd
Builder: 1 main and 25 inner classes
Analyzer input: 37 main and 25 inner classes
Analyzer output: 18 main and 25 inner classes
Generating package: init
Generating package: generated.c_forma_pago
Generating package: generated.c_moneda
Generating package: generated.c_tipo_de_comprobante
Generating package: generated.c_exportacion
Generating package: generated.c_metodo_pago
Generating package: generated.c_codigo_postal
Generating package: generated.c_periodicidad
Generating package: generated.c_meses
Generating package: generated.c_tipo_relacion
Generating package: generated.c_regimen_fiscal
Generating package: generated.c_pais
Generating package: generated.c_uso_cfdi
Generating package: generated.c_clave_prod_serv
Generating package: generated.c_clave_unidad
Generating package: generated.c_objeto_imp
Generating package: generated.c_impuesto
Generating package: generated.c_tipo_factor
Generating package: generated.comprobante
```

**Comment by rvalyi** [comment]
Hello @tefra I confirm you really fixed the issue with your latest changes, so kudos! And yes the huge enumeration on the xsd file is something crazy anyway.
