### ISSUE TITLE
xsi-type added to subclasses during serialization

### ISSUE THREAD

**Issue by mementum** [tefra/xsdata#782]
I use xsdata to generate `soap` bindings and then

```python
from dataclasses import dataclass
from generated.mod import Body

@dataclass
class Body(Body):
   ...
```

This `Body` will automatically add some elements to itself.

When I serialize an `Envelope` containing a subclassed `Body` the output will look like this:

```xml
...
 <soapenv:Body xsi:type="Body">
...
```

Ooops!. `Body` has gained an `xsi:type` attribute. Which I have narrowed down to:

https://github.com/tefra/xsdata/blob/4dc9b41f6e85616927f74bddead80ebee33a995b/xsdata/formats/dataclass/serializers/xml.py#L246-L249

My solution would be to change the logic to this:

```python
 def xsi_type(self, var: XmlVar, value: Any, namespace: NoneStr) -> Optional[str]: 
     """Get xsi:type if the given value is a derived instance.""" 
     if not value or issubclass(value.__class__, var.types):
         return None 
```

But not being sure of potentially unexpected side effects, I'd rather report it here than issue a pull-request.

**Comment by tefra** [comment]
Can you please share the wsdl? Are you overriding the default Body class?

**Comment by tefra** [comment]
I am guessing you are trying to extend the Body class from #783 right? That's why you are getting the xsi-type

**Comment by mementum** [comment]
There is no `wsdl`. `xsdata` is being used to parse `.xsd` defintions which include `soap`.

> I am guessing you are trying to extend the Body class from https://github.com/tefra/xsdata/issues/783 right? That's why you are getting the xsi-type

That the problem: it is not an *extension*, it is subclassing to control the initialization phase and adding support for the `<<` operator (`__lshift__` magic method). There is nothing which touches a single byte of the `soap`/`xsd` definition and that's why it seems odd to get a custom `xsi-type`.

Solution. Using the decorator proposed in #783, this part of the decorator

```python
  cls.Meta.userclass = True
```

it is being used in a subclass of `XmlSerializer` to detect that my python code is not an xml restriction/extension but just a regular python class.

```python
from __future__ import annotations
from dataclasses import dataclass
from typing import Any

from xsdata.formats.dataclass.models.elements import XmlVar
from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.xml import NoneStr


# -----------------------------------------------------------------------------
@dataclass
class XmlSerializer(XmlSerializer):
    '''Serialize fetching a "userclass" attribute from Meta, which if "True"
    indicates a Python subclass and avoids adding a "xsi-type" indication,
    because the subclass is NOT a restriction of the base class (xml-like)
    '''
    def xsi_type(self, var: XmlVar, value: Any, namespace: NoneStr) -> NoneStr:
        """Get xsi:type if the given value is a derived instance."""
        try:
            if value.Meta.userclass:
                return None
        except AttributeError:  # either "Meta" or "userclass" failed to be there
            pass

        return super().xsi_type(var, value, namespace)
```
