### ISSUE TITLE
Manipulating XSDs

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#794]
Given that xsdata is a transformation of an XML Schema into Dataclasses, I wonder how far could you push the manipulation of the original schema? Obviously `xsdata generate -p xsd XMLSchema.xsd` gives Python dataclasses for the XML Schema so a single file can be deserialised, that having said the generated binding knows nothing about the XSD specification other than syntax and semantics. How far is xsData from transforming its intermediate presentation back into the original XSD?

A use-case would be to extract profiles from XML Schemas. Hence using a full schema as basis for cutting out everything that is not in use for that specific implementation.

**Comment by tefra** [comment]
It's impossible to go back to the "original" schema, a lot of information is lost in the process because of the processing xsdata is doing to simplify the final models, thus the output xsd would match the models.

**Comment by skinkie** [comment]
Ok clear.
