### ISSUE TITLE
AttributeError during build_xsi_cache for _ObjectPropertyMethods

### ISSUE THREAD

**Issue by eric-spitler** [tefra/xsdata#795]
Python = 3.11.0
Xsdata = 23.5

https://github.com/tefra/xsdata/blob/4a02fa6126c9d9e3d91c2f3e360a26d1c9b897a7/xsdata/formats/dataclass/context.py#L91-L94

This is raising an `AttributeError` in Python 3.11.0 as `__module__` is not a string
```
clazz            = <class '_ObjectProxyMethods'>
clazz.__module__ = <property object at 0x7f540d6cc4a0>
```

When I use `inspect.getsource(clazz)` in a debug session, I get
```
TypeError: <class '_ObjectProxyMethods'> is a built-in class
```

Unfortunately, I cannot provide examples of the XSDs being used due to ownership concerns.

Locally, I was able to successfully use xsdata on the XSDs after making this change:
```python
for clazz in self.get_subclasses(object):
    # This is new! 
    if isinstance(clazz.__module__, str) and clazz.__module__.startswith("_pytest"): 
        continue 
```

**Comment by tefra** [comment]
I have to find a nicer way to catch these cases and exclude them

**Comment by tefra** [comment]
hey @eric-spitler 

Can you give this one a try and let me know if it works for you?
https://github.com/tefra/xsdata/pull/796

**Comment by eric-spitler** [comment]
The updated code is working with my XSD / XML data

**Comment by tefra** [comment]
The update is on master
