### ISSUE TITLE
Conflicting Enum values leading to attribute error on reference

### ISSUE THREAD

**Issue by tlambert03** [tefra/xsdata#805]
First off, thanks for the awesome library.  The structure is lovely and I'm very much enjoying using it.

I came across an issue in one of the XSD files I'm trying to process, wherein two enumerations conflict if handled with case-insensitivity (e.g. `value = "MW"` vs `value = "mW"`).

Here is a minimal `example.xsd`  

```xml
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="2">

    <xsd:complexType name="LightSource">
        <xsd:attribute name="PowerUnit" use="optional" default="mW" type="UnitsPower"></xsd:attribute>
    </xsd:complexType>

    <xsd:simpleType name="UnitsPower">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value = "MW"></xsd:enumeration>
            <xsd:enumeration value = "mW"></xsd:enumeration>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>
```

and the result after running `xsdata generate xsdata generate example.xsd`:

```py
from dataclasses import dataclass, field
from enum import Enum

class UnitsPower(Enum):
    MW = "MW"
    M_W_1 = "mW"


@dataclass
class LightSource:
    power_unit: UnitsPower = field(
        default=UnitsPower.M_W,
        metadata={
            "name": "PowerUnit",
            "type": "Attribute",
        }
    )
```

Note the incorrect `default=UnitsPower.M_W` in the dataclass.  Which, is correctly caught by mypy:

```bash
$ mypy generated
generated/power.py:13: error: "Type[UnitsPower]" has no attribute "M_W"  [attr-defined]
Found 1 error in 1 file (checked 2 source files)
```

xsdata: version 23.5
macos
python 3.11

Thanks!
(PS.  Happy to fix this myself if you'd like to roughly guide me to where either enums are generated or looked up in refs)

**Comment by tefra** [comment]
12k tests in the w3c test suite and I didn't have this occur once, is that schema part of a public suite? I would love to add it in the samples repo

**Comment by tlambert03** [comment]
it is!

My example was extracted from: http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd
([oxygen docs here](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome.html) if you're curious)

It's a big project that I've been working on for a while (my converted types are at https://github.com/tlambert03/ome-types)... Before finding xsdata, I rolled my own (disgusting) code to convert the xsd to pydantic types.  Now I'm in the process of porting everything to xsdata (because, it's really amazing ❤️).  Would love to have it added to your samples, and happy to continue helping however I can
