### ISSUE TITLE
Feature request: support output path cli flag

### ISSUE THREAD

**Issue by tlambert03** [tefra/xsdata#807]
The output directory of xsdata appears to be hardcoded as the current working directory:

https://github.com/tefra/xsdata/blob/11dbca80c6e59f5235f283cb69e3df3fb87e0cb8/xsdata/utils/package.py#L6-L9

While one can always temporarily `cd` around to change the output path, it would be nice to support a flag in the cli and a config.output option that sets the output path of the generated top level package folder.

**Comment by rvalyi** [comment]
Hello @tlambert03 . Did you try the --package=... option? Isn't it what you need?

**Comment by tlambert03** [comment]
Not quite, `package` will add an `__init__` file to every folder from `package` down.   So `--package=generated.sub.module` will create: 
```txt
generated/
├── __init__.py
├── sub/
│   ├── __init__.py
│   ├── module
│   │   ├── __init__.py
│   │   ├── module.py
```

(which makes sense, given the name `package`)... 

However, if you, for example, have a `src` layout (or generally just want to put the output *anywhere* other than the current working directory) you might want something like:

`xsdata -o other/directory --package module` 
```
other/
├── directory/
│   ├── module
│   │   ├── __init__.py
│   │   ├── module.py
```

**Comment by tefra** [comment]
Hear me out:

I already think xsdata is doing more than it should like formatting docstrings. 
As far as I see people already apply further transformations like pyupgrade or black to the generated models.

Adding another option for changing directories it doesn't really make sense to me, when people already have build scripts that take care of the whole model generation part.

**Comment by tlambert03** [comment]
okiedoke, i'll continue using my workaround
