### ISSUE TITLE
Q: possible to extend SchemaMapper?

### ISSUE THREAD

**Issue by tlambert03** [tefra/xsdata#812]
I have an application where I _think_ I need to extend `SchemaMapper.build_class_attribute`.  (specifically, I'd like to grab something out of an `<xsd:appinfo>` element that provides naming suggestions for an enumeration).

from looking through the code, it looks like ``SchemaMapper.build_class_attribute` would be the last place where I have both the `ElementBase` object, and the target `Class` we're building.   But it looks like the transformer directly calls  `classes = SchemaMapper.map(schema)`, so I don't appear to be able to extend it without a temporary monkey patch.  

do you have a suggestion?

**Comment by tefra** [comment]
There is this ticket here 
https://github.com/tefra/xsdata/issues/763

It's not hard to carry it, but there are too many possibilities and I am not sure what to do to cover all of them

**Comment by tefra** [comment]
Feel free to submit a hook or something you can you use to plugin your custom logic
