### ISSUE TITLE
Feature: allow passing sort key to XmlMeta.get_attribute_vars via XmlSerializer Config

### ISSUE THREAD

**Issue by tlambert03** [tefra/xsdata#813]
C14N canonicalization specifies that attributes should be serialized in a specific order.  But doing so currently requires going pretty deep into overriding `XMLSerializer.next_attribute` to resort what comes out of `meta.get_attribute_vars()`:

https://github.com/tefra/xsdata/blob/d39e9aa62d72ef298915b00e8133a42dfaa1fe38/xsdata/formats/dataclass/serializers/xml.py#L388

XmlMeta already does perform sorting  but it's hard coded by var index.
https://github.com/tefra/xsdata/blob/d39e9aa62d72ef298915b00e8133a42dfaa1fe38/xsdata/formats/dataclass/models/elements.py#L376-L378

Would you be amenable to a PR that added an `attribute_sort_key` to the `SerializerConfig`, that would be passed through to `XmlMeta.get_attribute_vars` via `XmlSerializer.next_attribute`?

**Comment by tefra** [comment]
Why don't you modify the classes and change the ordering there?

**Comment by tlambert03** [comment]
I did.  I just thought it was also perhaps a reasonable feature that you might welcome a PR for?

**Comment by tefra** [comment]
I have tried really hard to avoid having to specify the ordering of the fields and only rely on the definition ordering. Often with massive headaches with dataclasses issues like fields with default values can't follow optional fields.

Unless there is a reasonable need, I would like to avoid it.

**Comment by tlambert03** [comment]
Yep i understand why it would be your default.  For my pydantic base model  generator, that's not a limitation. But if you're not interested in passing through the sort key function that's ok, I'll continue patching on my end.  Thanks
