### ISSUE TITLE
xs:decimal improperly converted to scientific notation

### ISSUE THREAD

**Issue by eric-spitler** [tefra/xsdata#817]
xsdata version tested = 23.6
Python versions tested = 3.8, 3.9, 3.10, 3.11
----

When an XSD Element has type `xs:decimal` type
```xsd
<xs:element name="MyDecimal" type="xs:decimal">
```
and the input value is up to 6 decimal places
```xml
<MyDecimal>0.000000</MyDecimal>
<MyDecimal>0.000001</MyDecimal>
```
it parses and validates fine.

However, if the value is more than 6 decimal places and the first 6 are zeros
```xml
<MyDecimal>0.000000123456789</MyDecimal>
```
then validation fails because the value gets converted to scientific notation which is not allowed for `xs:decimal`
```log
xmlschema.validators.exceptions.XMLSchemaDecodeError: failed validating '1.23456789E-7' with XsdAtomicBuiltin(name='xs:decimal'):

Reason: invalid value '1.23456789E-7' for xs:decimal
```

If there is a non-zero number in one of the first places, then many places may be used and validate successfully
```xml
<MyDecimal>0.100000123456789</MyDecimal>
<MyDecimal>0.00000123456789</MyDecimal>
<MyDecimal>1.00000000000000</MyDecimal>
<MyDecimal>0.00000100000000</MyDecimal>
```

**Comment by eric-spitler** [comment]
Doing some debugging, I found the conversion to scientific notation happens at `xsdata.formats.converter.DecimalConverter` in the `deserialize` method. The method calls `Decimal(value)` (the Python built-in `Decimal` class) and converts properly.

I realize now that the issue is not with the conversion to Decimal, but with the validation in `xmlschema` not properly setting the format in its workflow.

I will open an issue on their Github and close this one.
https://github.com/sissaschool/xmlschema

**Comment by eric-spitler** [comment]
Upon further analysis, the value I was passing to `xmlschema` for validation had already been serialized by `xsdata.fomats.converter.DecimalConverter.serialize()`
https://github.com/tefra/xsdata/blob/d39e9aa62d72ef298915b00e8133a42dfaa1fe38/xsdata/formats/converter.py#L323-L327


The use of `str()` is producing scientific notation, making the serialized value invalid for `xs:decimal`.
If you instead use string formatting `{:f}`, then all decimal places are printed.
```python
    def serialize(self, value: Decimal, **kwargs: Any) -> str:
        if value.is_infinite():
            return str(value).replace("Infinity", "INF")

        return '{:f}'.format(value)
```

```python
>>> from decimal import Decimal
>>> str_value = '0.' + '0'*200
>>> dec_value = Decimal(str_value)
>>> rendered = '{:f}'.format(dec_value)
>>> print(str_value)
0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
>>> print(dec_value)
0E-200
>>> print(rendered)
0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
>>> assert rendered == str_value
>>>
```

**Comment by tefra** [comment]
excellent report @eric-spitler thank you!
