### ISSUE TITLE
numpy docstring format incorrect

### ISSUE THREAD

**Issue by tlambert03** [tefra/xsdata#818]
The current numpy template doesn't match the dumpy docstring style guide (and therefore doesn't get parsed correctly by most docstring parsers)

The template has `name : docstring`

https://github.com/tefra/xsdata/blob/d39e9aa62d72ef298915b00e8133a42dfaa1fe38/xsdata/formats/dataclass/templates/docstrings.numpy.jinja2#L6-L8

but the [style guide](https://github.com/tefra/xsdata/blob/d39e9aa62d72ef298915b00e8133a42dfaa1fe38/xsdata/formats/dataclass/templates/docstrings.numpy.jinja2#L6-L8) specifies either

```
name : type
    docstring
```

or, if there is no type:

```
name
    docstring
```

example:

```
Parameters
----------
x : type
    Description of parameter `x`.
y
    Description of parameter `y` (with type not specified).
```

**Comment by tefra** [comment]
Thanks for reporting @tlambert03

The fix is on main!

**Comment by tlambert03** [comment]
Is there a reason you're opting to leave out the type there?  I know the type is right there in the dataclass, but many docs generators (Sphinx auto doc, or mkdocstrings) look only in the docstring.

I can make a PR for that if you're not opposed

**Comment by pawamoy** [comment]
> look only in the docstring

mkdocstrings gives priority to the type in the docstring, and if there is no type in the docstring, it uses the type annotation in the signature. For dataclasses it's a bit different but IIRC we do support getting type annotations from the parameters, not only the docstrings.

**Comment by tlambert03** [comment]
you do, but it also requires a specific format.  and sphinx-autodoc doesn't.  So it would be best to have it in the docstring

**Comment by tefra** [comment]
In all docstring styles, we omit the type reference, it doesn't make sense to repeat it. For sphinx-autodoc you can also add [sphinx-autodoc-typehints](https://pypi.org/project/sphinx-autodoc-typehints/) to generate the typehints correctly.


Example from xsdata docs
https://xsdata.readthedocs.io/en/latest/api/reference/xsdata.models.config.GeneratorOutput.html
