### ISSUE TITLE
Multiple WSDL files on the generator path will conflate the WSDL definitions in a single file

### ISSUE THREAD

**Issue by plaflamme** [tefra/xsdata#823]
When there are multiple WSDL files in the generator path, the bindings get created correctly, but they all end up in the same file instead of being in distinct files (i.e.: `wsdl_1.py` and `wsdl_2.py`)

**Comment by tefra** [comment]
@plaflamme it depends on the structure style you have selected, I think even in your pr there are two modules generated, hello.py and bye.py

1. if you go with `filenames`, each wsdl will get it's own python module.
2. if you go with `namespaces` and both wsdl files have the same target namespace then they will be generated in the same file
3. If you want each classes to be written in strongly connected clusters go for  `clusters`

**Comment by plaflamme** [comment]
@tefra Thanks for the clarification. But I believe in my example PR what actually happens is that both WSDL files ended up in `bye.py` The fact that `hello.py` is still there is because I didn't delete the previously generated file. I believe that if you delete `hello.py` it will not be re-generated: instead `bye.py` is generated with both `bye.wsdl` and `hello.wsdl`'s content (I added a commit to my branch to demonstrate this)

When I use `--ss filenames` I only get one file for all my wsdls, not one per wsdl which is what I would expect.

**Comment by tefra** [comment]
@plaflamme no the hello.py is generated again, most the service methods go the the bye.py because of the duplicate class names only the first occurrence wins

**Comment by plaflamme** [comment]
@tefra indeed, `hello.py` is re-generated, sorry about that. That said, the service methods end up in `bye.py` but I'm not sure it's because of duplication.

I took at look at your example and when I run `xsdata generate -r uAPI_WSDLschema_Release-V22.3.1.9440` it correctly generates a file per wsdl, except that only one of them has all the service definitions and input/output types. In my case, that was in the `generated/air_v52_0/air.py` file.

I've created a repository with the source files and the generated files I obtained [here](https://github.com/plaflamme/test-xsdata). The `air.py` file has service methods from the [`Vehicle.wsdl`](https://github.com/plaflamme/test-xsdata/blob/main/uAPI_WSDLschema_Release-V22.3.1.9440/vehicle_v52_0/Vehicle.wsdl) file [here](https://github.com/plaflamme/test-xsdata/blob/main/generated/air_v52_0/air.py#L33584-L33671) for example. I would have expected those lines (and the Input/Output types) to be defined in `vehicle.py` [here](https://github.com/plaflamme/test-xsdata/blob/main/generated/vehicle_v52_0/vehicle.py).

Perhaps it is my expectation that is wrong? Should I not have expected those definitions to be in `vehicle.py` in this case?

**Comment by tefra** [comment]
:facepalm: confirmed

Thanks for your report @plaflamme I am on it

**Comment by tefra** [comment]
@plaflamme I still have to run a few tests but I think the pr addresses this issue

**Comment by plaflamme** [comment]
@tefra I just tested that PR on my codebase and it does indeed fix my issue, thanks!
