### ISSUE TITLE
List-elements are indistinguishable from lists of elements

### ISSUE THREAD

**Issue by martinwiesmann** [tefra/xsdata#850]
I found another minor bug, which would be very nice to have fixed:

A list-element with unbounded number of entries is indistinguishable from a list of simple elements. Whereas if the number of entries are limited, you'll get the (min/max)length property, with which it is possible to deduce that this is a list-element, and not a list of elements. At least it is possible for number elements, since those usually do not have a length property. If the element is a string this work-around won't work, since string element can have a length property. 

An example:

XSD unbounded:
```
<xs:simpleType name="listOfDouble">
	<xs:list itemType="xs:double"/>
</xs:simpleType>

<xs:complexType name="twoDMassParamsPeakCatalogMassAperture">
	<xs:sequence>
		<!--<xs:element name="InputCatalog" type="wl:catalogWL"/>-->
		<xs:element name="ApPeakRadius" type="dtd:listOfDouble">
			<xs:annotation>
				<xs:documentation> Which radius are used for aperture mass detection. </xs:documentation>
			</xs:annotation>
		</xs:element>
	</xs:sequence>
</xs:complexType>
```

Corresponding dataclass, ApPeakRadius is just a list of float elements
```
@dataclass
class TwoDMassParamsPeakCatalogMassAperture:
    """
    Parameters for Peak Counting using Mass aperture on shear data.

    :ivar ApPeakRadius: Which radius are used for aperture mass
        detection.
    """
    class Meta:
        name = "twoDMassParamsPeakCatalogMassAperture"

    ApPeakRadius: List[float] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "",
            "required": True,
            "tokens": True,
        }
    )
```

XSD with max number of entries equals two:
```
<xs:simpleType name="listOf2Double">
	<xs:annotation>
		<xs:documentation>Space separated list of 2 double values, used for array2D.</xs:documentation>
	</xs:annotation>
	<xs:restriction base="listOfDouble">
		<xs:length value="2"/>
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="matrixDouble2x2">
	<xs:annotation>
		<xs:documentation>A 2x2 double matrix</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="DoubleRow1" type="dtd:listOf2Double"/>
		<xs:element name="DoubleRow2" type="dtd:listOf2Double"/>
	</xs:sequence>
</xs:complexType>
```

Corresponding dataclass, DoubleRow1 and DoubleRow2 are lists of float elements as well, but they contain the length property and it can thus be inferred that they should be list-elements and not elements of lists.
```
@dataclass
class MatrixDouble2x2:
    """
    A 2x2 double matrix.
    """
    class Meta:
        name = "matrixDouble2x2"

    DoubleRow1: List[float] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "",
            "required": True,
            "length": 2,
            "tokens": True,
        }
    )
    DoubleRow2: List[float] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "",
            "required": True,
            "length": 2,
            "tokens": True,
        }
    )
```

**Comment by tefra** [comment]
I am a bit confused, what should be the correct generated class?

**Comment by martinwiesmann** [comment]
The correct generated class should somehow distinguish between these two cases, a list-element or a list of elements.

E.g.

```
<?xml version="1.0" ?>
<ns1:DpdDqcDynamicFlags xmlns:ns1="http://ecdm.euclid-ec.org/schema/dpd/dqc/dynamicflags">
	<Data>
		<ListElement>1.2 3.4 3.0 9.4 1.1</ListElement >
		<List>1</List >
		<List>2</List >
		<List>3</List >
		<List>4</List >
		<List>5</List >
	</Data>
```

But I don't see this distinction, and thus it is impossible to infer which of the cases was in the original xsd. Except if I overlooked something.

And I am not quite sure how the distinction would look like exactly. Maybe a new boolean keyword like 'listelement'.

**Comment by martinwiesmann** [comment]
I am sorry, but is the keyword 'tokens' exactly that boolean keyword I was suggesting? If yes, then I am sorry for not reading the manual properly before asking and this issue can be closed.
