### ISSUE TITLE
Serializer render particularities

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#860]
I have noticed recently that the rendering of some elements at this moment in time looks different than I have remembered before, but I might mixed up the JAXB output.

For some elements I noticed that empty lists are rendered as `<Blabla/>`. When explicitly marking blabla=None, the elements are removed from the output.

**Comment by tefra** [comment]
Any examples?

**Comment by skinkie** [comment]
You mean python code that generates it?

**Comment by tefra** [comment]
Yes

**Comment by skinkie** [comment]
If you take the NeTEx XSD, the rendering of the following (without the None) leads to
```xml
                            <PaymentMethods/>
                            <PurchaseMoment/>
```

```
                line = Line(id="blabla"
                            payment_methods=None,
                            purchase_moment=None
                            )
```

**Comment by tefra** [comment]
First of all, the payment__methods and purchase_moment are derived from `xs:token` you can't set these arguments to `None`

```
    payment_methods: List[PaymentMethodEnumeration] = field(
        default_factory=list,
        metadata={
            "name": "PaymentMethods",
            "type": "Element",
            "namespace": "http://www.netex.org.uk/netex",
            "tokens": True,
        }
    )
```

xsdata always generated thoses as empty elements if the list is empty

**Comment by skinkie** [comment]
How to omit 'empty tokes' when minOccurs=0? Should this be a new serializer option, similar to `ignore_default_attributes`?

**Comment by tefra** [comment]
We need some more research on this, is it and xsd thing when it should and when it shouldn't generate an empty tokens element?

**Comment by skinkie** [comment]
https://www.w3.org/TR/xmlschema-1/#Complex_Type_Definition_details search for "then empty". But I don't know why an element without any content (thus: empty list / enumeration) would be rendered _at all_, this wouldn't happen for a regular xs:string.

**Comment by tefra** [comment]
Thanks for reporting @skinkie, it turns out I was missing a condition there to ignore elements with `minOccurs==0`


Netex [output](https://github.com/tefra/xsdata-samples/commit/4f3f35aad49513f02cdbd7f45d87b71475d40f2d)

**Comment by skinkie** [comment]
@tefra lovely, this will certainly help to generate cleaner files.
