### ISSUE TITLE
Loss of Fractional Part in Numbers When Converting Between JSON and Dataclass

### ISSUE THREAD

**Issue by Xtreemrus** [tefra/xsdata#862]
First of all, thank you so much for the library; it's a lifesaver :)

I've encountered an issue with the conversion chain from XML -> Dataclass -> JSON, and then back from the resulting JSON to Dataclass, where I noticed that the fractional part of numbers is getting lost.

Here's a short example that demonstrates this behavior:

```python
from dataclasses import dataclass, field
from xsdata.formats.dataclass.parsers import JsonParser
from typing import Optional, Union

parser = JsonParser()

@dataclass
class Account:
    summ_current: Optional[Union[float, int]] = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
        }
    )

json_str = """{"summ_current": 6353.45}"""

print(parser.from_string(json_str, Account))
# print result: Account(summ_current=6353)
```

As you can see, after parsing the JSON string, the `summ_current` attribute loses its fractional part and is incorrectly set as an integer (6353) instead of the expected float (6353.45). Could you please look into this issue?

**Comment by tefra** [comment]
Confirmed, the converter ignores the fact that the value is already float

**Comment by tefra** [comment]
Thanks for reporting  @Xtreemrus  the fix is on main!
