### ISSUE TITLE
Is there a way to add some logic to metadata fields so it correctly reflects the schema

### ISSUE THREAD

**Issue by mdhaisne** [tefra/xsdata#865]
Hello ! 

I'm new to this project and I have some questions regarding the output dataclasses. In my XSD I have some `xsd:simpleType` with `xsd:restriction` like `xsd:minInclusive` etc. I can clearly see that it is exported in the metadata but it does not seem to come with the logic behind that. 
By this, I mean that I can still use a value lower that my `xsd:minInclusive` and the dataclass that I've instanciate is OK. But this lead to an invalid XML when serializing later.
So I still have to assert the output xml against the based schema. It sounds incoherent to me as I'd expect the generated dataclasses to reflect the schema and its restrictions. (And I wouldn't have to use the schema later to re-assert that the datamodel is correct)

My question; Is there a way to add some logic to metadata fields ? So it prevents the objects to be created when a restriction isn't respected. 

For now, I'm using `xsdata-attrs` to enforce the non-optional fields. So I know which property is optional or not when creating instanciate an object from the generated dataclasses.

Maybe it is related to other issues or I've missed something in the documentation, sorry for the noise if so.

Thanks for you help !!

Regards

**Comment by tefra** [comment]
The metadata are just informative for now, I am planning to create a validation plugin.

https://github.com/tefra/xsdata/issues/595

**Comment by mdhaisne** [comment]
Okay thanks !
