### ISSUE TITLE
Question: "Resource not found" when generating from remote xsd

### ISSUE THREAD

**Issue by afuetterer** [tefra/xsdata#866]
Hi,

I am not sure, if I am doing something wrong here. If I run:
`xsdata http://www.openarchives.org/OAI/2.0/oai_dc.xsd`

I get 
```console
xsdata http://www.openarchives.org/OAI/2.0/oai_dc.xsd
========= xsdata v23.8 / Python 3.12.0 / Platform linux =========

Parsing schema http://www.openarchives.org/OAI/2.0/oai_dc.xsd
Compiling schema http://www.openarchives.org/OAI/2.0/oai_dc.xsd
Builder: 2 main and 0 inner classes
Analyzer input: 2 main and 0 inner classes
Analyzer output: 2 main and 0 inner classes
Generating package: init
Generating package: generated.oai_dc
Warnings: 16
warning: Resource not found http://dublincore.org/schemas/xmls/simpledc20021212.xsd
warning: Reset absent type: title
warning: Reset absent type: creator
warning: Reset absent type: subject
warning: Reset absent type: description
warning: Reset absent type: publisher
warning: Reset absent type: contributor
warning: Reset absent type: date
warning: Reset absent type: type
warning: Reset absent type: format
warning: Reset absent type: identifier
warning: Reset absent type: source
warning: Reset absent type: language
warning: Reset absent type: relation
warning: Reset absent type: coverage
warning: Reset absent type: rights
```

Can I somehow fix the "Resource not found" warnings? Or is the xsd the problem here?

Any help would be appreciated.

**Comment by tefra** [comment]
The url redirects first to 

`https://dublincore.org/schemas/xmls/simpledc20021212.xsd` and then `https://www.dublincore.org/schemas/xmls/simpledc20021212.xsd`,  our cli doesn't follow redirects.

I am on it

**Comment by afuetterer** [comment]
Thanks for your respinse. I see, so it's a strange XSD after all.

Can I work around this by storing all XSDs locally and then calling generate?

**Comment by tefra** [comment]
Yes, you can download the xsds and update the links to relative paths

**Comment by afuetterer** [comment]
Excellent, thank you. 
Should I close this issue or do you want it open, because the CLI should eventually follow those kinds of redirects?

**Comment by tefra** [comment]
Actually urllib.request.open follows the redirects by default, the server responds with 403 because the request has no headers, leave it open, I will add a fix.

**Comment by tefra** [comment]
thanks for reporting @afuetterer the fix is on main

**Comment by afuetterer** [comment]
Awesome, thank you very much.

**Comment by afuetterer** [comment]
PS: It works like a charm!
