### ISSUE TITLE
Wildcard / AnyElement with custom namespace

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#870]
I think it should be added to the documentation how to set a custom namespace on the AnyElement.

https://xsdata.readthedocs.io/en/latest/examples/working-with-wildcards.html

It is trivial, as long as you know it.

```
AnyElement(qname="{http://www.netex.org.uk/netex}MaxLength", text="BISON:DisplayTextLength")
```

**Comment by tefra** [comment]
Oh there is no explicit example, will do!
