### ISSUE TITLE
PycodeSerializer does not escape strings containing unicode characters

### ISSUE THREAD

**Issue by SrirachaHorse** [tefra/xsdata#876]
When using `PycodeSerializer`, strings containing unicode characters are not correctly escaped by the serializer, leading to invalid Python code.

For example, take this schema, and generate it with `xsdata generate schema.xsd`:

```xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="2">
  <xsd:element name="foo" type="xsd:string"/>
</xsd:schema>
```

Once generated, run this script - `Foo`'s value is displayed as `"\"`, which does not correctly escape the backslash.

```python
from xsdata.formats.dataclass.serializers import PycodeSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig

from generated import Foo

data = Foo(value='\\')
serializer = PycodeSerializer()
print(serializer.render(data))
```

Output:
```python
from generated.schema import Foo


obj = Foo(
    value="\"
)
```

Attempting to run this generated script results in an error: 

```
  File "result.py", line 5
    value="\"
            ^
SyntaxError: EOL while scanning string literal
```

The same issue is present if instead using `serializer.write()` to write the script to a file.

**Comment by tefra** [comment]
@SrirachaHorse regarding this issue, did you have any other example that failed besides the `"\\"`?

I have cases like this, that were valid python syntax and makes sense to keep them unescaped

```
 class S(Enum):
-    A_A = "Aƻa"
-    B_B = "bƻB"
+    A_A = "A\u01bba"
+    B_B = "b\u01bbB"
```

**Comment by tefra** [comment]
thank you! I am going to revert the unicode escape then but ensure the code serializer wont break on this cases
