### ISSUE TITLE
Use ruff to format generated code

### ISSUE THREAD

**Issue by tefra** [tefra/xsdata#889]
I wanted to use black when I started this project in order to format the generated files but big projects was too slow and I didn't want to add another dependency in xsdata.

Present day, I am so tired trying to format things manually in the code or the templates.

With the new ruff format beta, I think I want to remove all the clutter from xsdata and be done with it.

**Comment by rvalyi** [comment]
for information, in my Odoo class generator that is based on xsdata I extended the generator and I used Black to format the code:
https://github.com/akretion/xsdata-odoo/blob/master/xsdata_odoo%2Fgenerator.py#L265

So far so good and could probably have worked as well with Ruff.
