### ISSUE TITLE
New substitution group code opportunities

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#904]
What is the reason that the new substitution group code generates:

```
class JourneysInFrameRelStructure(ContainmentAggregationStructure):
    class Meta:
        name = "journeysInFrame_RelStructure"

    choice: List[
        Union[
            VehicleJourney,
            DatedVehicleJourney,
            NormalDatedVehicleJourney,
            ServiceJourney,
            DatedServiceJourney,
            DeadRun,
            SpecialService,
            TemplateServiceJourney,
        ]
    ] = field(
```

<xsd:element name="VehicleJourney" abstract="false" substitutionGroup="VehicleJourney_" id="VehicleJourney">
<xsd:element name="DeadRun" abstract="false" substitutionGroup="VehicleJourney_">
<xsd:element name="DatedVehicleJourney" abstract="false" substitutionGroup="Journey_">
<xsd:element name="NormalDatedVehicleJourney" abstract="false" substitutionGroup="Journey_">
<xsd:element name="ServiceJourney" abstract="false" substitutionGroup="VehicleJourney_">
<xsd:element name="DatedServiceJourney" abstract="false" substitutionGroup="ServiceJourney_">
<xsd:element name="DeadRun" abstract="false" substitutionGroup="VehicleJourney_">
<xsd:element name="DatedSpecialService" abstract="false" substitutionGroup="Journey_">
<xsd:element name="TemplateServiceJourney" abstract="false" substitutionGroup="ServiceJourney_">

But misses the opportunities to make the choice named "Journey_" (being the most abstract type).

Is this due the the choice being?
```
                                <xsd:choice maxOccurs="unbounded">
                                        <xsd:element ref="VehicleJourney"/>
                                        <xsd:element ref="DatedVehicleJourney"/>
                                        <xsd:element ref="NormalDatedVehicleJourney"/>
                                        <xsd:element ref="ServiceJourney"/>
                                        <xsd:element ref="DatedServiceJourney"/>
                                        <xsd:element ref="DeadRun"/>
                                        <xsd:element ref="SpecialService"/>
                                        <xsd:element ref="TemplateServiceJourney">
                                                <xsd:annotation>
                                                        <xsd:documentation>A VEHICLE JOURNEY with a set of frequencies that may be used to represent a set of similar journeys differing only by their time of departure.</xsd:documentation>
                                                </xsd:annotation>
                                        </xsd:element>
                                </xsd:choice>
```

Instead of something like this?
```
                                <xsd:sequence>
                                        <xsd:element ref="Journey_" maxOccurs="unbounded"/>
                                </xsd:sequence>
```

**Comment by skinkie** [comment]
For this one:
```
                        <xsd:extension base="containmentAggregationStructure">
                                <xsd:choice maxOccurs="unbounded">
                                        <xsd:element ref="OperatingPeriodRef"/>
                                        <xsd:element ref="OperatingPeriod" maxOccurs="1">
                                                <xsd:annotation>
                                                        <xsd:documentation>An Named operating period.</xsd:documentation>
                                                </xsd:annotation>
                                        </xsd:element>
                                        <xsd:element ref="UicOperatingPeriod"/>
                                </xsd:choice>
                        </xsd:extension>
```
It is also not very obvious why this choice is named _operating_period_ref_.

I would almost argue: leave choice alone, unless the choice is in fact a choice between the same abstract type.

**Comment by tefra** [comment]
In the first case the compound field is a direct repeatable choice element, no substituted fields there.

In the second case are you talking about [this](https://github.com/tefra/xsdata-samples/blob/main/netex/models/operating_periods_rel_structure.py) the element is named `operating_period_ref_or_operating_period_or_uic_operating_period`


The `useSubstitutionGroups` refers to compound fields that were creating by substitution groups

**Comment by skinkie** [comment]
Situation two is rendered like this at my side. I have included #855.

```
@dataclass(kw_only=True)
class OperatingPeriodsRelStructure(ContainmentAggregationStructure):
    class Meta:
        name = "operatingPeriods_RelStructure"

    operating_period_ref: List[
        Union[
            UicOperatingPeriodRef,
            OperatingPeriodRef,
            OperatingPeriod,
            UicOperatingPeriod,
        ]
    ] = field(
```

**Comment by tefra** [comment]
In that case, since the field `UicOperatingPeriodRef` was added because of its substitution group the compound field gets the name from the group which is `OperatingPeriodRef`

**Comment by skinkie** [comment]
> In that case, since the field `UicOperatingPeriodRef` was added because of its substitution group the compound field gets the name from the group which is `OperatingPeriodRef`

Would there be a way te keep the choice for 'true choices' and use the 'subsitution group naming' only for those? Obviously it would be great if the software could detect the choice is the full set of objects of having the same type, but I think it would be cleaner (for now) to actually show what is a choice.

**Comment by tefra** [comment]
> > In that case, since the field `UicOperatingPeriodRef` was added because of its substitution group the compound field gets the name from the group which is `OperatingPeriodRef`
> 
> Would there be a way te keep the choice for 'true choices' and use the 'subsitution group naming' only for those? Obviously it would be great if the software could detect the choice is the full set of objects of having the same type, but I think it would be cleaner (for now) to actually show what is a choice.


Make senses
