### ISSUE TITLE
XMLDateTime.from_datetime() how to set the UTC (so it renders as "Z") 

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#918]
XMLDateTime.from_datetime() how to set the UTC (so it renders as "Z").

```python
import datetime
from xsdata.models.datatype import XmlDateTime
print(str(XmlDateTime.from_datetime(datetime.datetime.utcnow())))
```
vs
```python
import datetime
from xsdata.models.datatype import XmlDateTime
print(str(XmlDateTime.utcnow()))
```

**Comment by tefra** [comment]
`datetime.utcnow()` doesn't add the tzinfo 
https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow


Either use the `XmlDateTime.utcnow()` or XmlDateTime.from_datetime(datetime.datetime.now(datetime.timezone.utc)))

**Comment by skinkie** [comment]
My actual usecase is that I want to provide an `XmlDateTime.from_datetime(some_utc_timestamp)` and can't get that rendered in UTC.
