### ISSUE TITLE
v24 and #881 break private package names

### ISSUE THREAD

**Issue by tlambert03** [tefra/xsdata#948]
I found another breakage in my code generation as of v24, specifically, added by [this line](https://github.com/tefra/xsdata/pull/881/files#diff-f1c09b10ffdb9dea2adce211aad87e08882a703be2165c8c7e2c163deb69b34cR322) in #881

When `CodeWriter.write`, calls `Generator.normalize_packages`, it ultimately calls `DataclassGenerator.package_name` -> `Filters.package_name` -> `Filters.safe_name` -> `text.variable`

The problem is that `DataclassGenerator.package_name('my.valid._but._private.package')` now returns `'my.valid.but.private.package'` ... so all of my outputs have been changed to a new module name.

**Comment by tlambert03** [comment]
I'm not sure I followed the rationale for #881 in the first place, so I don't know what the appropriate fix would be that would retain the intended change of #881, but it seems that modules in output package names should definitely be allowed to start with an underscore

**Comment by tefra** [comment]
You are right, the modification should only have affected the original name case not everything

**Comment by tefra** [comment]
Hey @tlambert03 give main a try, it should be ok now, if everything checks out from your side I can release a patch version.

**Comment by tlambert03** [comment]
yep that fixes it, thanks!
