### ISSUE TITLE
Improve code generation user-facing error on non-existent source file

### ISSUE THREAD

**Issue by fleimgruber** [tefra/xsdata#955]
When referencing a non-existent source file ("non-existing.xsd"):
```
xsdata generate non-existing.xsd --package some.models -ss single-package
```
only a `CodeGenerationError` is shown:
```
========= xsdata v24.2.1 / Python 3.10.8 / Platform win32 =========

Traceback (most recent call last):
...
xsdata.exceptions.CodeGenerationError: Nothing to generate.
```
when instead a FileNotFoundError would be more informative for the user.

**Comment by fleimgruber** [comment]
@tefra If you think this is a good change then I will create a PR for it.

**Comment by tefra** [comment]
The transformer is very lenient and doesn't fail if an included schema can't be retrieved, but yes I agree that behavior shouldn't be extended to the main resource file

**Comment by fleimgruber** [comment]
@tefra could you give me a quick heads up please on where this is best tested? I looked at the testing and exceptions seem to be captured and printed to the user? Assuming that is true, I went to test for process output (i.e. not testing with `assertRaises`) of runner invocation results and could not find the expected traceback containing `xsdata.exceptions.CodeGenerationError` as in OP, but only the line `========= xsdata v24.2.1 / Python 3.10.8 / Platform win32 =========`. Please see also https://github.com/fleimgruber/xsdata/commit/41ce482666c5977c17cbcf4a3cb1882cc5156940.

**Comment by tefra** [comment]
A proper warning will now be generated

```

**Comment by tefra** [comment]
```
