### ISSUE TITLE
Render XML without namespace

### ISSUE THREAD

**Issue by tebrown** [tefra/xsdata#957]
I have the following model:

```
@dataclass
class Event:
    class Meta:
        name="event"

    location: str = field(metadata=dict(type="Element"))
    city: str = field(metadata=dict(type="Element"))
    priority: int = field(metadata=dict(type="Element"))
    eventNum: Optional[str] = field(metadata=dict(type="Element", required=True, nillable=True), default=None)
```

If I crate an event like so:
`Event( location="123 MAIN ST", city="ANYTOWN", priority=1)`

I want to get the following XML out:
```
 <event>
    <location>123 MAIN ST</location>
    <city>ANYTOWN</city>
    <priority>1</priority>
   <eventNum/>
</event>
```

Unfortunately, I get the full nillable namespace with eventNum `<eventNum xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>`. 

I found that I can convert it to json, and then to xml, but that seems so very wrong to me.

**Comment by tefra** [comment]
Remove the `nillable` property

**Comment by tebrown** [comment]
I would, except I need the data to show up like when there is no actual data in the feed.  Unfortunately, I cannot change the software on the other end that I am sending the data to, and it will not except it if there are missing keys.

**Comment by tebrown** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<event>
  <location>123 MAIN ST</location>
  <city>ANYTOWN</city>
  <priority>1</priority>
</event>
```

Without nillable, I do not get `<event/>`, which I need for the interface.

**Comment by tebrown** [comment]
Wow.. I cannot believe I did not think of that. Thank you SO much!
