### ISSUE TITLE
Feature Request: Code generated modules include a comment stating "autogenerated"

### ISSUE THREAD

**Issue by fleimgruber** [tefra/xsdata#958]
Code modules generated via `xsdata generate ...` contain a docstring at the top saying e.g. `"""Code generated ... DO NOT EDIT."""`. The message is configurable and can be passed as an option to `xsdata generate`. The feature could also be optional as a whole, i.e. no comment is inserted by default (current behaviour) and is only inserted if the option was provided by the user.

**Comment by fleimgruber** [comment]
@tefra If you accept this FR, I would look into a PR for it.

**Comment by tefra** [comment]
https://xsdata.readthedocs.io/en/latest/codegen/config/#includeheader

**Comment by fleimgruber** [comment]
Perfect! Sorry for the noise and not reading the fine manual...
