### ISSUE TITLE
Use of generated classes with subclasses, base classes and mixins

### ISSUE THREAD

**Issue by fleimgruber** [tefra/xsdata#960]
There are two approaches to use generated classes together with user classes:

1. Subclass the generated classes.
2. Derive generated classes from user provided base or mixin classes, mentioned in https://xsdata.readthedocs.io/en/latest/codegen/config/#extension-settings.

The first option does not generate a valid XML serialization from the user class (see also #783), the second option can't use generated classes in the base or mixin classes because that results in circular imports.

What is the recommended way to have both XMl serialization and generated classes in user classes?

**Comment by tefra** [comment]
It's not possible @fleimgruber do you have a use case, why you want a generated class to also be a base class for another generated class?

**Comment by fleimgruber** [comment]
Thanks for the quick reply, I will try to illustrate my use case and sketch with concrete code.

**Comment by fleimgruber** [comment]
The basic idea is to 1. subclass generated classes to provide convenience functions (e.g. `build_b_from`) to initialize class fields and 2. satisfy an external interface (e.g. `change_c`) while 3. having the same behaviour, e.g. serialization, for those child classes.

```python
from autogenerated.models import GenA, GenB, GenC, GenD


def sepecifics_of(s):
    return len(s)


class UserA(GenA):
    @staticmethod
    def build_b_from(user_input):
        return GenB(x=specifics_of(user_input))

    def change_c(self, changed_input):
        self.c = GenC(y=GenD(changed_input))


some_input = "xyz"
another_input = "stu"

a = UserA()
a_data = UserA(b=a.build_b_from(some_input))

a_data.change_c(another_input)
```

In the case of deeply nested schemas, those convenience functions of `UserA` help to construct the domain logic object while hiding the generated bindings API. By implementing external interface methods, `UserA` could be used to swap out another implementation of `a_data`. (`@classmethod` or something similar could be used instead of `@staticmethod` to avoid the first instantiation of `a = UserA()`, but this is just an attempt to illustrate)

In the specific example, subclassing `GenA` from `UserA` via the extensions mechanism would lead to the mentioned circular import.

My current solution is to use `GenA` as a composite object of `UserA` like this:

```python
class UserA:
    def __init__(self, data):
        self._data = data

    def data(self):
        return self._data

    @staticmethod
    def build_b_from(user_input):
        return GenB(x=specifics_of(user_input))

    def change_c(self, changed_input):
        self._data.c = GenC(y=GenD(changed_input))


a = UserA(GenA())
data = GenA(b=a.build_b_from(some_input))
a_data = UserA(data)

a_data.change_c(another_input)
```

where serialization would then be `a_data.data.xml()`.

I hope the use case is clearer now, in any case I think `class UserA(GenA)` is the naive approach that users would most likely try first (as in #783).

**Comment by tefra** [comment]
You can achieve the same with 

```python
class GenA(UserA):
```

**Comment by fleimgruber** [comment]
> class GenA(UserA):

As `UserA` uses `GenB`, this leads to a circular import error.

**Comment by tefra** [comment]
You can continue the same way but you have to repeat the meta class which isn't recommended because you interfere with how types are located during parsing. Or use the mixins approach of xsdata and **update** your code to avoid circular imports.

The way the meta class works can't change and can't be inherited, I am sorry this is final.
