### ISSUE TITLE
Ability to capture namespace mappings on code generation, and render xml with the same mappings

### ISSUE THREAD

**Issue by fleimgruber** [tefra/xsdata#963]
Using code generator -> XML serializer, the namespace prefixes ns0, ns1, etc. are created. Are namespace prefixes saved somewhere during code generation? Is there another more automatic way to specify namespace map for the serializer based on the .xsd information, e.g. as in here for `XmlParser` https://github.com/tefra/xsdata/issues/847#issuecomment-1733007668?

**Comment by tefra** [comment]
No the namespace prefixes are not stored during code generation, your only option is to pass them manually in the serializer

**Comment by saschnet** [comment]
Would it be possible to automatically create a serializer (perhaps only with an optional flag in the cli) that contains such information?

I can imagine that @fleimgruber and me are not the only users that would like to create a namespace map based on the xsd information.
