### ISSUE TITLE
Access unknown attributes

### ISSUE THREAD

**Issue by Krzmbrzl** [tefra/xsdata#965]
So we can parse XMLs that contain attributes that are not mentioned in the associated schema. However, is there a way to access such attributes via the XSData API via some sort of generic dict-like way? E.g. `my_obj["attr"]` or `my_obj.attributes["attr"]`?
Or are unrecognized attributes simply thrown away?

**Comment by tefra** [comment]
Yes the unknown attributes are simply ignored. If you want to catch them you will have an `Attributes` [field](https://xsdata.readthedocs.io/en/latest/models/fields/#attributes) to capture them

**Comment by Krzmbrzl** [comment]
Too bad - but thanks for the quick answer!
