### ISSUE TITLE
Rename (abstract) objects

### ISSUE THREAD

**Issue by skinkie** [tefra/xsdata#983]
In the NeTEx schema abstract objects are suffixed with a "\_". Within xsData this "\_" is being removed when classes are generated. This is obviously XML Schema specific. The effect is most promently seen with Line_ (abstract) and Line. Which become Line1 and Line2.

1. Would it be possible to configure the substitution character? It seems that original_case strips the underscores.
2. I think in general having the ability to tag abstract classes as abstract could make sense too. I would think that just before apply_subsitutions suffixing with a user definable suffix such as "Abstract" could certainly do the job.

**Comment by tefra** [comment]
It's not really a substitution, two types have the same pythonic identifier and the system simply renames them.

I am going to add an additional strategy in the handler to add the abstract suffix in these cases

**Comment by tefra** [comment]
The update is merged, here is the [output](https://github.com/tefra/xsdata-samples/commit/583dbbd7b966e527fbb7952bf4cb5a39465bcca1#diff-f138d445a206f764f732f55b50318dd12971c8ada2d97dffbbe7cb897c55fe68)
