### ISSUE TITLE
Generate full XML examples from given schema

### ISSUE THREAD

**Issue by fleimgruber** [tefra/xsdata#988]
This is a follow-up of the trick mentioned in https://github.com/tefra/xsdata/issues/956#issuecomment-1959682957. An example XML file is parsed and the matching Python bindings example code is emitted. What if the example XML file does not contain some of the elements, i.e. optional attributes, that are defined in the XSD? So to get Python bindings example code for all of the elements that are defined in the XSD, we would need an XML file that contains all those elements. The actual question: Is there a way in `xsdata` to generate such an XML file? Or is there another way to produce such a file?

**Comment by tefra** [comment]
xsdata doesn't have such capabilities, at some point I wanted to try [faker](https://fakepy.readthedocs.io/en/latest/factories.html#dataclasses-example) but yeah that's outside of this library scope
